/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 411d91261be3
 */

import { analyticsGetUserActivity } from "../funcs/analyticsGetUserActivity.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Analytics extends ClientSDK {
  /**
   * Get user activity grouped by endpoint
   *
   * @remarks
   * Returns user activity data grouped by endpoint for the last 30 (completed) UTC days. [Management key](/docs/guides/overview/auth/management-api-keys) required.
   */
  async getUserActivity(
    request?: operations.GetUserActivityRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.ActivityResponse> {
    return unwrapAsync(analyticsGetUserActivity(
      this,
      request,
      options,
    ));
  }
}
