/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 5dda931501e1
 */

import { apiKeysCreate } from "../funcs/apiKeysCreate.js";
import { apiKeysDelete } from "../funcs/apiKeysDelete.js";
import { apiKeysGet } from "../funcs/apiKeysGet.js";
import { apiKeysGetCurrentKeyMetadata } from "../funcs/apiKeysGetCurrentKeyMetadata.js";
import { apiKeysList } from "../funcs/apiKeysList.js";
import { apiKeysUpdate } from "../funcs/apiKeysUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class APIKeys extends ClientSDK {
  /**
   * Get current API key
   *
   * @remarks
   * Get information on the API key associated with the current authentication session
   */
  async getCurrentKeyMetadata(
    request?: operations.GetCurrentKeyRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.GetCurrentKeyResponse> {
    return unwrapAsync(apiKeysGetCurrentKeyMetadata(
      this,
      request,
      options,
    ));
  }

  /**
   * List API keys
   *
   * @remarks
   * List all API keys for the authenticated user. [Management key](/docs/guides/overview/auth/management-api-keys) required.
   */
  async list(
    request?: operations.ListRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListResponse> {
    return unwrapAsync(apiKeysList(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a new API key
   *
   * @remarks
   * Create a new API key for the authenticated user. [Management key](/docs/guides/overview/auth/management-api-keys) required.
   */
  async create(
    request: operations.CreateKeysRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateKeysResponse> {
    return unwrapAsync(apiKeysCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete an API key
   *
   * @remarks
   * Delete an existing API key. [Management key](/docs/guides/overview/auth/management-api-keys) required.
   */
  async delete(
    request: operations.DeleteKeysRequest,
    options?: RequestOptions,
  ): Promise<operations.DeleteKeysResponse> {
    return unwrapAsync(apiKeysDelete(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a single API key
   *
   * @remarks
   * Get a single API key by hash. [Management key](/docs/guides/overview/auth/management-api-keys) required.
   */
  async get(
    request: operations.GetKeyRequest,
    options?: RequestOptions,
  ): Promise<operations.GetKeyResponse> {
    return unwrapAsync(apiKeysGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Update an API key
   *
   * @remarks
   * Update an existing API key. [Management key](/docs/guides/overview/auth/management-api-keys) required.
   */
  async update(
    request: operations.UpdateKeysRequest,
    options?: RequestOptions,
  ): Promise<operations.UpdateKeysResponse> {
    return unwrapAsync(apiKeysUpdate(
      this,
      request,
      options,
    ));
  }
}
