/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c72074b5f165
 */

import { creditsGetCredits } from "../funcs/creditsGetCredits.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Credits extends ClientSDK {
  /**
   * Get remaining credits
   *
   * @remarks
   * Get total credits purchased and used for the authenticated user. [Management key](/docs/guides/overview/auth/management-api-keys) required.
   */
  async getCredits(
    request?: operations.GetCreditsRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.GetCreditsResponse> {
    return unwrapAsync(creditsGetCredits(
      this,
      request,
      options,
    ));
  }
}
