/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 976de6f449fe
 */

import { organizationListMembers } from "../funcs/organizationListMembers.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Organization extends ClientSDK {
  /**
   * List organization members
   *
   * @remarks
   * List all members of the organization associated with the authenticated management key. [Management key](/docs/guides/overview/auth/management-api-keys) required.
   */
  async listMembers(
    request?: operations.ListOrganizationMembersRequest | undefined,
    options?: RequestOptions,
  ): Promise<
    PageIterator<operations.ListOrganizationMembersResponse, { offset: number }>
  > {
    return unwrapResultIterator(organizationListMembers(
      this,
      request,
      options,
    ));
  }
}
