/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 0d5a42c2eac3
 */

import { rerankRerank } from "../funcs/rerankRerank.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Rerank extends ClientSDK {
  /**
   * Submit a rerank request
   *
   * @remarks
   * Submits a rerank request to the rerank router
   */
  async rerank(
    request: operations.CreateRerankRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateRerankResponse> {
    return unwrapAsync(rerankRerank(
      this,
      request,
      options,
    ));
  }
}
