/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 784571af2f69
 */

import { ClientSDK } from "../lib/sdks.js";
import { Analytics } from "./analytics.js";
import { APIKeys } from "./apikeys.js";
import { Beta } from "./beta.js";
import { Chat } from "./chat.js";
import { Credits } from "./credits.js";
import { Embeddings } from "./embeddings.js";
import { Endpoints } from "./endpoints.js";
import { Generations } from "./generations.js";
import { Guardrails } from "./guardrails.js";
import { Models } from "./models.js";
import { OAuth } from "./oauth.js";
import { Organization } from "./organization.js";
import { Providers } from "./providers.js";
import { Rerank } from "./rerank.js";
import { VideoGeneration } from "./videogeneration.js";
// #region imports
import type { $ZodObject, $ZodShape, infer as zodInfer } from "zod/v4/core";
import {
  callModel as callModelFunc,
  type CallModelInput,
} from "../funcs/call-model.js";
import type { ModelResult } from "../lib/model-result.js";
import type { RequestOptions } from "../lib/sdks.js";
import { type Tool, ToolType } from "../lib/tool-types.js";

export { ToolType };
// #endregion imports

export class OpenRouter extends ClientSDK {
  private _analytics?: Analytics;
  get analytics(): Analytics {
    return (this._analytics ??= new Analytics(this._options));
  }

  private _oAuth?: OAuth;
  get oAuth(): OAuth {
    return (this._oAuth ??= new OAuth(this._options));
  }

  private _chat?: Chat;
  get chat(): Chat {
    return (this._chat ??= new Chat(this._options));
  }

  private _credits?: Credits;
  get credits(): Credits {
    return (this._credits ??= new Credits(this._options));
  }

  private _embeddings?: Embeddings;
  get embeddings(): Embeddings {
    return (this._embeddings ??= new Embeddings(this._options));
  }

  private _endpoints?: Endpoints;
  get endpoints(): Endpoints {
    return (this._endpoints ??= new Endpoints(this._options));
  }

  private _generations?: Generations;
  get generations(): Generations {
    return (this._generations ??= new Generations(this._options));
  }

  private _guardrails?: Guardrails;
  get guardrails(): Guardrails {
    return (this._guardrails ??= new Guardrails(this._options));
  }

  private _apiKeys?: APIKeys;
  get apiKeys(): APIKeys {
    return (this._apiKeys ??= new APIKeys(this._options));
  }

  private _models?: Models;
  get models(): Models {
    return (this._models ??= new Models(this._options));
  }

  private _organization?: Organization;
  get organization(): Organization {
    return (this._organization ??= new Organization(this._options));
  }

  private _providers?: Providers;
  get providers(): Providers {
    return (this._providers ??= new Providers(this._options));
  }

  private _rerank?: Rerank;
  get rerank(): Rerank {
    return (this._rerank ??= new Rerank(this._options));
  }

  private _beta?: Beta;
  get beta(): Beta {
    return (this._beta ??= new Beta(this._options));
  }

  private _videoGeneration?: VideoGeneration;
  get videoGeneration(): VideoGeneration {
    return (this._videoGeneration ??= new VideoGeneration(this._options));
  }

  // #region sdk-class-body
  callModel<
    TTools extends readonly Tool[],
    TSharedSchema extends $ZodObject<$ZodShape> | undefined = undefined,
    TShared extends Record<string, unknown> = TSharedSchema extends
      $ZodObject<$ZodShape> ? zodInfer<TSharedSchema> : Record<string, never>,
  >(
    request: CallModelInput<TTools, TShared> & {
      sharedContextSchema?: TSharedSchema;
    },
    options?: RequestOptions,
  ): ModelResult<TTools, TShared> {
    return callModelFunc(this, request, options);
  }
  // #endregion sdk-class-body
}
