/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: db34eab5bd5b
 */

import { videoGenerationGenerate } from "../funcs/videoGenerationGenerate.js";
import { videoGenerationGetGeneration } from "../funcs/videoGenerationGetGeneration.js";
import { videoGenerationGetVideoContent } from "../funcs/videoGenerationGetVideoContent.js";
import { videoGenerationListVideosModels } from "../funcs/videoGenerationListVideosModels.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class VideoGeneration extends ClientSDK {
  /**
   * Submit a video generation request
   *
   * @remarks
   * Submits a video generation request and returns a polling URL to check status
   */
  async generate(
    request: operations.CreateVideosRequest,
    options?: RequestOptions,
  ): Promise<models.VideoGenerationResponse> {
    return unwrapAsync(videoGenerationGenerate(
      this,
      request,
      options,
    ));
  }

  /**
   * Poll video generation status
   *
   * @remarks
   * Returns job status and content URLs when completed
   */
  async getGeneration(
    request: operations.GetVideosRequest,
    options?: RequestOptions,
  ): Promise<models.VideoGenerationResponse> {
    return unwrapAsync(videoGenerationGetGeneration(
      this,
      request,
      options,
    ));
  }

  /**
   * Download generated video content
   *
   * @remarks
   * Streams the generated video content from the upstream provider
   */
  async getVideoContent(
    request: operations.ListVideosContentRequest,
    options?: RequestOptions,
  ): Promise<ReadableStream<Uint8Array>> {
    return unwrapAsync(videoGenerationGetVideoContent(
      this,
      request,
      options,
    ));
  }

  /**
   * List all video generation models
   *
   * @remarks
   * Returns a list of all available video generation models and their properties
   */
  async listVideosModels(
    request?: operations.ListVideosModelsRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.VideoModelsListResponse> {
    return unwrapAsync(videoGenerationListVideosModels(
      this,
      request,
      options,
    ));
  }
}
