/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 7ccac02a65ba
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the @openrouter/sdk SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx analyticsGetUserActivity.example.ts
 */

import { OpenRouter } from "@openrouter/sdk";

const openRouter = new OpenRouter({
  httpReferer: "<value>",
  appTitle: "<value>",
  appCategories: "<value>",
  apiKey: process.env["OPENROUTER_API_KEY"] ?? "",
});

async function main() {
  const result = await openRouter.analytics.getUserActivity();

  console.log(result);
}

main().catch(console.error);
