/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4f855e3ea589
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type BulkAssignKeysToGuardrailGlobals = {
  /**
   * The app identifier should be your app's URL and is used as the primary identifier for rankings.
   *
   * @remarks
   * This is used to track API usage per application.
   */
  httpReferer?: string | undefined;
  /**
   * The app display name allows you to customize how your app appears in OpenRouter's dashboard.
   *
   * @remarks
   */
  appTitle?: string | undefined;
  /**
   * Comma-separated list of app categories (e.g. "cli-agent,cloud-agent"). Used for marketplace rankings.
   *
   * @remarks
   */
  appCategories?: string | undefined;
};

export type BulkAssignKeysToGuardrailRequest = {
  /**
   * The app identifier should be your app's URL and is used as the primary identifier for rankings.
   *
   * @remarks
   * This is used to track API usage per application.
   */
  httpReferer?: string | undefined;
  /**
   * The app display name allows you to customize how your app appears in OpenRouter's dashboard.
   *
   * @remarks
   */
  appTitle?: string | undefined;
  /**
   * Comma-separated list of app categories (e.g. "cli-agent,cloud-agent"). Used for marketplace rankings.
   *
   * @remarks
   */
  appCategories?: string | undefined;
  /**
   * The unique identifier of the guardrail
   */
  id: string;
  bulkAssignKeysRequest: models.BulkAssignKeysRequest;
};

/** @internal */
export type BulkAssignKeysToGuardrailRequest$Outbound = {
  "HTTP-Referer"?: string | undefined;
  appTitle?: string | undefined;
  appCategories?: string | undefined;
  id: string;
  BulkAssignKeysRequest: models.BulkAssignKeysRequest$Outbound;
};

/** @internal */
export const BulkAssignKeysToGuardrailRequest$outboundSchema: z.ZodType<
  BulkAssignKeysToGuardrailRequest$Outbound,
  BulkAssignKeysToGuardrailRequest
> = z.object({
  httpReferer: z.string().optional(),
  appTitle: z.string().optional(),
  appCategories: z.string().optional(),
  id: z.string(),
  bulkAssignKeysRequest: models.BulkAssignKeysRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    httpReferer: "HTTP-Referer",
    bulkAssignKeysRequest: "BulkAssignKeysRequest",
  });
});

export function bulkAssignKeysToGuardrailRequestToJSON(
  bulkAssignKeysToGuardrailRequest: BulkAssignKeysToGuardrailRequest,
): string {
  return JSON.stringify(
    BulkAssignKeysToGuardrailRequest$outboundSchema.parse(
      bulkAssignKeysToGuardrailRequest,
    ),
  );
}
