/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 09a0f06fd33d
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type BulkAssignMembersToGuardrailGlobals = {
  /**
   * The app identifier should be your app's URL and is used as the primary identifier for rankings.
   *
   * @remarks
   * This is used to track API usage per application.
   */
  httpReferer?: string | undefined;
  /**
   * The app display name allows you to customize how your app appears in OpenRouter's dashboard.
   *
   * @remarks
   */
  appTitle?: string | undefined;
  /**
   * Comma-separated list of app categories (e.g. "cli-agent,cloud-agent"). Used for marketplace rankings.
   *
   * @remarks
   */
  appCategories?: string | undefined;
};

export type BulkAssignMembersToGuardrailRequest = {
  /**
   * The app identifier should be your app's URL and is used as the primary identifier for rankings.
   *
   * @remarks
   * This is used to track API usage per application.
   */
  httpReferer?: string | undefined;
  /**
   * The app display name allows you to customize how your app appears in OpenRouter's dashboard.
   *
   * @remarks
   */
  appTitle?: string | undefined;
  /**
   * Comma-separated list of app categories (e.g. "cli-agent,cloud-agent"). Used for marketplace rankings.
   *
   * @remarks
   */
  appCategories?: string | undefined;
  /**
   * The unique identifier of the guardrail
   */
  id: string;
  bulkAssignMembersRequest: models.BulkAssignMembersRequest;
};

/** @internal */
export type BulkAssignMembersToGuardrailRequest$Outbound = {
  "HTTP-Referer"?: string | undefined;
  appTitle?: string | undefined;
  appCategories?: string | undefined;
  id: string;
  BulkAssignMembersRequest: models.BulkAssignMembersRequest$Outbound;
};

/** @internal */
export const BulkAssignMembersToGuardrailRequest$outboundSchema: z.ZodType<
  BulkAssignMembersToGuardrailRequest$Outbound,
  BulkAssignMembersToGuardrailRequest
> = z.object({
  httpReferer: z.string().optional(),
  appTitle: z.string().optional(),
  appCategories: z.string().optional(),
  id: z.string(),
  bulkAssignMembersRequest: models.BulkAssignMembersRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    httpReferer: "HTTP-Referer",
    bulkAssignMembersRequest: "BulkAssignMembersRequest",
  });
});

export function bulkAssignMembersToGuardrailRequestToJSON(
  bulkAssignMembersToGuardrailRequest: BulkAssignMembersToGuardrailRequest,
): string {
  return JSON.stringify(
    BulkAssignMembersToGuardrailRequest$outboundSchema.parse(
      bulkAssignMembersToGuardrailRequest,
    ),
  );
}
