/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 7c210337fdff
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { ClosedEnum, OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type CreateEmbeddingsGlobals = {
  /**
   * The app identifier should be your app's URL and is used as the primary identifier for rankings.
   *
   * @remarks
   * This is used to track API usage per application.
   */
  httpReferer?: string | undefined;
  /**
   * The app display name allows you to customize how your app appears in OpenRouter's dashboard.
   *
   * @remarks
   */
  appTitle?: string | undefined;
  /**
   * Comma-separated list of app categories (e.g. "cli-agent,cloud-agent"). Used for marketplace rankings.
   *
   * @remarks
   */
  appCategories?: string | undefined;
};

/**
 * The format of the output embeddings
 */
export const EncodingFormat = {
  Float: "float",
  Base64: "base64",
} as const;
/**
 * The format of the output embeddings
 */
export type EncodingFormat = OpenEnum<typeof EncodingFormat>;

export type ImageUrl = {
  url: string;
};

export type ContentImageURL = {
  imageUrl: ImageUrl;
  type: "image_url";
};

export type ContentText = {
  text: string;
  type: "text";
};

export type Content = ContentText | ContentImageURL;

export type Input = {
  content: Array<ContentText | ContentImageURL>;
};

/**
 * Text, token, or multimodal input(s) to embed
 */
export type InputUnion =
  | string
  | Array<string>
  | Array<number>
  | Array<Array<number>>
  | Array<Input>;

/**
 * Embeddings request input
 */
export type CreateEmbeddingsRequestBody = {
  /**
   * The number of dimensions for the output embeddings
   */
  dimensions?: number | undefined;
  /**
   * The format of the output embeddings
   */
  encodingFormat?: EncodingFormat | undefined;
  /**
   * Text, token, or multimodal input(s) to embed
   */
  input:
    | string
    | Array<string>
    | Array<number>
    | Array<Array<number>>
    | Array<Input>;
  /**
   * The type of input (e.g. search_query, search_document)
   */
  inputType?: string | undefined;
  /**
   * The model to use for embeddings
   */
  model: string;
  provider?: models.ProviderPreferences | null | undefined;
  /**
   * A unique identifier for the end-user
   */
  user?: string | undefined;
};

export type CreateEmbeddingsRequest = {
  /**
   * The app identifier should be your app's URL and is used as the primary identifier for rankings.
   *
   * @remarks
   * This is used to track API usage per application.
   */
  httpReferer?: string | undefined;
  /**
   * The app display name allows you to customize how your app appears in OpenRouter's dashboard.
   *
   * @remarks
   */
  appTitle?: string | undefined;
  /**
   * Comma-separated list of app categories (e.g. "cli-agent,cloud-agent"). Used for marketplace rankings.
   *
   * @remarks
   */
  appCategories?: string | undefined;
  requestBody: CreateEmbeddingsRequestBody;
};

/**
 * Embedding vector as an array of floats or a base64 string
 */
export type Embedding = Array<number> | string;

export const ObjectEmbedding = {
  Embedding: "embedding",
} as const;
export type ObjectEmbedding = ClosedEnum<typeof ObjectEmbedding>;

/**
 * A single embedding object
 */
export type CreateEmbeddingsData = {
  /**
   * Embedding vector as an array of floats or a base64 string
   */
  embedding: Array<number> | string;
  /**
   * Index of the embedding in the input list
   */
  index?: number | undefined;
  object: ObjectEmbedding;
};

export const ObjectT = {
  List: "list",
} as const;
export type ObjectT = ClosedEnum<typeof ObjectT>;

/**
 * Token usage statistics
 */
export type CreateEmbeddingsUsage = {
  /**
   * Cost of the request in credits
   */
  cost?: number | undefined;
  /**
   * Number of tokens in the input
   */
  promptTokens: number;
  /**
   * Total number of tokens used
   */
  totalTokens: number;
};

/**
 * Embeddings response containing embedding vectors
 */
export type CreateEmbeddingsResponseBody = {
  /**
   * List of embedding objects
   */
  data: Array<CreateEmbeddingsData>;
  /**
   * Unique identifier for the embeddings response
   */
  id?: string | undefined;
  /**
   * The model used for embeddings
   */
  model: string;
  object: ObjectT;
  /**
   * Token usage statistics
   */
  usage?: CreateEmbeddingsUsage | undefined;
};

export type CreateEmbeddingsResponse = CreateEmbeddingsResponseBody | string;

/** @internal */
export const EncodingFormat$outboundSchema: z.ZodType<string, EncodingFormat> =
  openEnums.outboundSchema(EncodingFormat);

/** @internal */
export type ImageUrl$Outbound = {
  url: string;
};

/** @internal */
export const ImageUrl$outboundSchema: z.ZodType<ImageUrl$Outbound, ImageUrl> = z
  .object({
    url: z.string(),
  });

export function imageUrlToJSON(imageUrl: ImageUrl): string {
  return JSON.stringify(ImageUrl$outboundSchema.parse(imageUrl));
}

/** @internal */
export type ContentImageURL$Outbound = {
  image_url: ImageUrl$Outbound;
  type: "image_url";
};

/** @internal */
export const ContentImageURL$outboundSchema: z.ZodType<
  ContentImageURL$Outbound,
  ContentImageURL
> = z.object({
  imageUrl: z.lazy(() => ImageUrl$outboundSchema),
  type: z.literal("image_url"),
}).transform((v) => {
  return remap$(v, {
    imageUrl: "image_url",
  });
});

export function contentImageURLToJSON(
  contentImageURL: ContentImageURL,
): string {
  return JSON.stringify(ContentImageURL$outboundSchema.parse(contentImageURL));
}

/** @internal */
export type ContentText$Outbound = {
  text: string;
  type: "text";
};

/** @internal */
export const ContentText$outboundSchema: z.ZodType<
  ContentText$Outbound,
  ContentText
> = z.object({
  text: z.string(),
  type: z.literal("text"),
});

export function contentTextToJSON(contentText: ContentText): string {
  return JSON.stringify(ContentText$outboundSchema.parse(contentText));
}

/** @internal */
export type Content$Outbound = ContentText$Outbound | ContentImageURL$Outbound;

/** @internal */
export const Content$outboundSchema: z.ZodType<Content$Outbound, Content> = z
  .union([
    z.lazy(() => ContentText$outboundSchema),
    z.lazy(() => ContentImageURL$outboundSchema),
  ]);

export function contentToJSON(content: Content): string {
  return JSON.stringify(Content$outboundSchema.parse(content));
}

/** @internal */
export type Input$Outbound = {
  content: Array<ContentText$Outbound | ContentImageURL$Outbound>;
};

/** @internal */
export const Input$outboundSchema: z.ZodType<Input$Outbound, Input> = z.object({
  content: z.array(
    z.union([
      z.lazy(() => ContentText$outboundSchema),
      z.lazy(() => ContentImageURL$outboundSchema),
    ]),
  ),
});

export function inputToJSON(input: Input): string {
  return JSON.stringify(Input$outboundSchema.parse(input));
}

/** @internal */
export type InputUnion$Outbound =
  | string
  | Array<string>
  | Array<number>
  | Array<Array<number>>
  | Array<Input$Outbound>;

/** @internal */
export const InputUnion$outboundSchema: z.ZodType<
  InputUnion$Outbound,
  InputUnion
> = z.union([
  z.string(),
  z.array(z.string()),
  z.array(z.number()),
  z.array(z.array(z.number())),
  z.array(z.lazy(() => Input$outboundSchema)),
]);

export function inputUnionToJSON(inputUnion: InputUnion): string {
  return JSON.stringify(InputUnion$outboundSchema.parse(inputUnion));
}

/** @internal */
export type CreateEmbeddingsRequestBody$Outbound = {
  dimensions?: number | undefined;
  encoding_format?: string | undefined;
  input:
    | string
    | Array<string>
    | Array<number>
    | Array<Array<number>>
    | Array<Input$Outbound>;
  input_type?: string | undefined;
  model: string;
  provider?: models.ProviderPreferences$Outbound | null | undefined;
  user?: string | undefined;
};

/** @internal */
export const CreateEmbeddingsRequestBody$outboundSchema: z.ZodType<
  CreateEmbeddingsRequestBody$Outbound,
  CreateEmbeddingsRequestBody
> = z.object({
  dimensions: z.int().optional(),
  encodingFormat: EncodingFormat$outboundSchema.optional(),
  input: z.union([
    z.string(),
    z.array(z.string()),
    z.array(z.number()),
    z.array(z.array(z.number())),
    z.array(z.lazy(() => Input$outboundSchema)),
  ]),
  inputType: z.string().optional(),
  model: z.string(),
  provider: z.nullable(models.ProviderPreferences$outboundSchema).optional(),
  user: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    encodingFormat: "encoding_format",
    inputType: "input_type",
  });
});

export function createEmbeddingsRequestBodyToJSON(
  createEmbeddingsRequestBody: CreateEmbeddingsRequestBody,
): string {
  return JSON.stringify(
    CreateEmbeddingsRequestBody$outboundSchema.parse(
      createEmbeddingsRequestBody,
    ),
  );
}

/** @internal */
export type CreateEmbeddingsRequest$Outbound = {
  "HTTP-Referer"?: string | undefined;
  appTitle?: string | undefined;
  appCategories?: string | undefined;
  RequestBody: CreateEmbeddingsRequestBody$Outbound;
};

/** @internal */
export const CreateEmbeddingsRequest$outboundSchema: z.ZodType<
  CreateEmbeddingsRequest$Outbound,
  CreateEmbeddingsRequest
> = z.object({
  httpReferer: z.string().optional(),
  appTitle: z.string().optional(),
  appCategories: z.string().optional(),
  requestBody: z.lazy(() => CreateEmbeddingsRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    httpReferer: "HTTP-Referer",
    requestBody: "RequestBody",
  });
});

export function createEmbeddingsRequestToJSON(
  createEmbeddingsRequest: CreateEmbeddingsRequest,
): string {
  return JSON.stringify(
    CreateEmbeddingsRequest$outboundSchema.parse(createEmbeddingsRequest),
  );
}

/** @internal */
export const Embedding$inboundSchema: z.ZodType<Embedding, unknown> = z.union([
  z.array(z.number()),
  z.string(),
]);

export function embeddingFromJSON(
  jsonString: string,
): SafeParseResult<Embedding, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Embedding$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Embedding' from JSON`,
  );
}

/** @internal */
export const ObjectEmbedding$inboundSchema: z.ZodEnum<typeof ObjectEmbedding> =
  z.enum(ObjectEmbedding);

/** @internal */
export const CreateEmbeddingsData$inboundSchema: z.ZodType<
  CreateEmbeddingsData,
  unknown
> = z.object({
  embedding: z.union([z.array(z.number()), z.string()]),
  index: z.int().optional(),
  object: ObjectEmbedding$inboundSchema,
});

export function createEmbeddingsDataFromJSON(
  jsonString: string,
): SafeParseResult<CreateEmbeddingsData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateEmbeddingsData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateEmbeddingsData' from JSON`,
  );
}

/** @internal */
export const ObjectT$inboundSchema: z.ZodEnum<typeof ObjectT> = z.enum(ObjectT);

/** @internal */
export const CreateEmbeddingsUsage$inboundSchema: z.ZodType<
  CreateEmbeddingsUsage,
  unknown
> = z.object({
  cost: z.number().optional(),
  prompt_tokens: z.int(),
  total_tokens: z.int(),
}).transform((v) => {
  return remap$(v, {
    "prompt_tokens": "promptTokens",
    "total_tokens": "totalTokens",
  });
});

export function createEmbeddingsUsageFromJSON(
  jsonString: string,
): SafeParseResult<CreateEmbeddingsUsage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateEmbeddingsUsage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateEmbeddingsUsage' from JSON`,
  );
}

/** @internal */
export const CreateEmbeddingsResponseBody$inboundSchema: z.ZodType<
  CreateEmbeddingsResponseBody,
  unknown
> = z.object({
  data: z.array(z.lazy(() => CreateEmbeddingsData$inboundSchema)),
  id: z.string().optional(),
  model: z.string(),
  object: ObjectT$inboundSchema,
  usage: z.lazy(() => CreateEmbeddingsUsage$inboundSchema).optional(),
});

export function createEmbeddingsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<CreateEmbeddingsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateEmbeddingsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateEmbeddingsResponseBody' from JSON`,
  );
}

/** @internal */
export const CreateEmbeddingsResponse$inboundSchema: z.ZodType<
  CreateEmbeddingsResponse,
  unknown
> = z.union([
  z.lazy(() => CreateEmbeddingsResponseBody$inboundSchema),
  z.string(),
]);

export function createEmbeddingsResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateEmbeddingsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateEmbeddingsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateEmbeddingsResponse' from JSON`,
  );
}
