/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1443f6afbf40
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CreateAuthKeysCodeGlobals = {
  /**
   * The app identifier should be your app's URL and is used as the primary identifier for rankings.
   *
   * @remarks
   * This is used to track API usage per application.
   */
  httpReferer?: string | undefined;
  /**
   * The app display name allows you to customize how your app appears in OpenRouter's dashboard.
   *
   * @remarks
   */
  appTitle?: string | undefined;
  /**
   * Comma-separated list of app categories (e.g. "cli-agent,cloud-agent"). Used for marketplace rankings.
   *
   * @remarks
   */
  appCategories?: string | undefined;
};

/**
 * The method used to generate the code challenge
 */
export const CreateAuthKeysCodeCodeChallengeMethod = {
  S256: "S256",
  Plain: "plain",
} as const;
/**
 * The method used to generate the code challenge
 */
export type CreateAuthKeysCodeCodeChallengeMethod = OpenEnum<
  typeof CreateAuthKeysCodeCodeChallengeMethod
>;

/**
 * Optional credit limit reset interval. When set, the credit limit resets on this interval.
 */
export const UsageLimitType = {
  Daily: "daily",
  Weekly: "weekly",
  Monthly: "monthly",
} as const;
/**
 * Optional credit limit reset interval. When set, the credit limit resets on this interval.
 */
export type UsageLimitType = OpenEnum<typeof UsageLimitType>;

export type CreateAuthKeysCodeRequestBody = {
  /**
   * The callback URL to redirect to after authorization. Note, only https URLs on ports 443 and 3000 are allowed.
   */
  callbackUrl: string;
  /**
   * PKCE code challenge for enhanced security
   */
  codeChallenge?: string | undefined;
  /**
   * The method used to generate the code challenge
   */
  codeChallengeMethod?: CreateAuthKeysCodeCodeChallengeMethod | undefined;
  /**
   * Optional expiration time for the API key to be created
   */
  expiresAt?: Date | null | undefined;
  /**
   * Optional custom label for the API key. Defaults to the app name if not provided.
   */
  keyLabel?: string | undefined;
  /**
   * Credit limit for the API key to be created
   */
  limit?: number | undefined;
  /**
   * Optional credit limit reset interval. When set, the credit limit resets on this interval.
   */
  usageLimitType?: UsageLimitType | undefined;
};

export type CreateAuthKeysCodeRequest = {
  /**
   * The app identifier should be your app's URL and is used as the primary identifier for rankings.
   *
   * @remarks
   * This is used to track API usage per application.
   */
  httpReferer?: string | undefined;
  /**
   * The app display name allows you to customize how your app appears in OpenRouter's dashboard.
   *
   * @remarks
   */
  appTitle?: string | undefined;
  /**
   * Comma-separated list of app categories (e.g. "cli-agent,cloud-agent"). Used for marketplace rankings.
   *
   * @remarks
   */
  appCategories?: string | undefined;
  requestBody: CreateAuthKeysCodeRequestBody;
};

/**
 * Auth code data
 */
export type CreateAuthKeysCodeData = {
  /**
   * The application ID associated with this auth code
   */
  appId: number;
  /**
   * ISO 8601 timestamp of when the auth code was created
   */
  createdAt: string;
  /**
   * The authorization code ID to use in the exchange request
   */
  id: string;
};

/**
 * Successfully created authorization code
 */
export type CreateAuthKeysCodeResponse = {
  /**
   * Auth code data
   */
  data: CreateAuthKeysCodeData;
};

/** @internal */
export const CreateAuthKeysCodeCodeChallengeMethod$outboundSchema: z.ZodType<
  string,
  CreateAuthKeysCodeCodeChallengeMethod
> = openEnums.outboundSchema(CreateAuthKeysCodeCodeChallengeMethod);

/** @internal */
export const UsageLimitType$outboundSchema: z.ZodType<string, UsageLimitType> =
  openEnums.outboundSchema(UsageLimitType);

/** @internal */
export type CreateAuthKeysCodeRequestBody$Outbound = {
  callback_url: string;
  code_challenge?: string | undefined;
  code_challenge_method?: string | undefined;
  expires_at?: string | null | undefined;
  key_label?: string | undefined;
  limit?: number | undefined;
  usage_limit_type?: string | undefined;
};

/** @internal */
export const CreateAuthKeysCodeRequestBody$outboundSchema: z.ZodType<
  CreateAuthKeysCodeRequestBody$Outbound,
  CreateAuthKeysCodeRequestBody
> = z.object({
  callbackUrl: z.string(),
  codeChallenge: z.string().optional(),
  codeChallengeMethod: CreateAuthKeysCodeCodeChallengeMethod$outboundSchema
    .optional(),
  expiresAt: z.nullable(z.date().transform(v => v.toISOString())).optional(),
  keyLabel: z.string().optional(),
  limit: z.number().optional(),
  usageLimitType: UsageLimitType$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    callbackUrl: "callback_url",
    codeChallenge: "code_challenge",
    codeChallengeMethod: "code_challenge_method",
    expiresAt: "expires_at",
    keyLabel: "key_label",
    usageLimitType: "usage_limit_type",
  });
});

export function createAuthKeysCodeRequestBodyToJSON(
  createAuthKeysCodeRequestBody: CreateAuthKeysCodeRequestBody,
): string {
  return JSON.stringify(
    CreateAuthKeysCodeRequestBody$outboundSchema.parse(
      createAuthKeysCodeRequestBody,
    ),
  );
}

/** @internal */
export type CreateAuthKeysCodeRequest$Outbound = {
  "HTTP-Referer"?: string | undefined;
  appTitle?: string | undefined;
  appCategories?: string | undefined;
  RequestBody: CreateAuthKeysCodeRequestBody$Outbound;
};

/** @internal */
export const CreateAuthKeysCodeRequest$outboundSchema: z.ZodType<
  CreateAuthKeysCodeRequest$Outbound,
  CreateAuthKeysCodeRequest
> = z.object({
  httpReferer: z.string().optional(),
  appTitle: z.string().optional(),
  appCategories: z.string().optional(),
  requestBody: z.lazy(() => CreateAuthKeysCodeRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    httpReferer: "HTTP-Referer",
    requestBody: "RequestBody",
  });
});

export function createAuthKeysCodeRequestToJSON(
  createAuthKeysCodeRequest: CreateAuthKeysCodeRequest,
): string {
  return JSON.stringify(
    CreateAuthKeysCodeRequest$outboundSchema.parse(createAuthKeysCodeRequest),
  );
}

/** @internal */
export const CreateAuthKeysCodeData$inboundSchema: z.ZodType<
  CreateAuthKeysCodeData,
  unknown
> = z.object({
  app_id: z.int(),
  created_at: z.string(),
  id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "app_id": "appId",
    "created_at": "createdAt",
  });
});

export function createAuthKeysCodeDataFromJSON(
  jsonString: string,
): SafeParseResult<CreateAuthKeysCodeData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateAuthKeysCodeData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateAuthKeysCodeData' from JSON`,
  );
}

/** @internal */
export const CreateAuthKeysCodeResponse$inboundSchema: z.ZodType<
  CreateAuthKeysCodeResponse,
  unknown
> = z.object({
  data: z.lazy(() => CreateAuthKeysCodeData$inboundSchema),
});

export function createAuthKeysCodeResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateAuthKeysCodeResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateAuthKeysCodeResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateAuthKeysCodeResponse' from JSON`,
  );
}
