/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: ddb4fa558414
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetCurrentKeyGlobals = {
  /**
   * The app identifier should be your app's URL and is used as the primary identifier for rankings.
   *
   * @remarks
   * This is used to track API usage per application.
   */
  httpReferer?: string | undefined;
  /**
   * The app display name allows you to customize how your app appears in OpenRouter's dashboard.
   *
   * @remarks
   */
  appTitle?: string | undefined;
  /**
   * Comma-separated list of app categories (e.g. "cli-agent,cloud-agent"). Used for marketplace rankings.
   *
   * @remarks
   */
  appCategories?: string | undefined;
};

export type GetCurrentKeyRequest = {
  /**
   * The app identifier should be your app's URL and is used as the primary identifier for rankings.
   *
   * @remarks
   * This is used to track API usage per application.
   */
  httpReferer?: string | undefined;
  /**
   * The app display name allows you to customize how your app appears in OpenRouter's dashboard.
   *
   * @remarks
   */
  appTitle?: string | undefined;
  /**
   * Comma-separated list of app categories (e.g. "cli-agent,cloud-agent"). Used for marketplace rankings.
   *
   * @remarks
   */
  appCategories?: string | undefined;
};

/**
 * Legacy rate limit information about a key. Will always return -1.
 *
 * @deprecated class: This will be removed in a future release, please migrate away from it as soon as possible.
 */
export type RateLimit = {
  /**
   * Rate limit interval
   */
  interval: string;
  /**
   * Note about the rate limit
   */
  note: string;
  /**
   * Number of requests allowed per interval
   */
  requests: number;
};

/**
 * Current API key information
 */
export type GetCurrentKeyData = {
  /**
   * Total external BYOK usage (in USD) for the API key
   */
  byokUsage: number;
  /**
   * External BYOK usage (in USD) for the current UTC day
   */
  byokUsageDaily: number;
  /**
   * External BYOK usage (in USD) for current UTC month
   */
  byokUsageMonthly: number;
  /**
   * External BYOK usage (in USD) for the current UTC week (Monday-Sunday)
   */
  byokUsageWeekly: number;
  /**
   * The user ID of the key creator. For organization-owned keys, this is the member who created the key. For individual users, this is the user's own ID.
   */
  creatorUserId: string | null;
  /**
   * ISO 8601 UTC timestamp when the API key expires, or null if no expiration
   */
  expiresAt?: Date | null | undefined;
  /**
   * Whether to include external BYOK usage in the credit limit
   */
  includeByokInLimit: boolean;
  /**
   * Whether this is a free tier API key
   */
  isFreeTier: boolean;
  /**
   * Whether this is a management key
   */
  isManagementKey: boolean;
  /**
   * Whether this is a management key
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  isProvisioningKey: boolean;
  /**
   * Human-readable label for the API key
   */
  label: string;
  /**
   * Spending limit for the API key in USD
   */
  limit: number;
  /**
   * Remaining spending limit in USD
   */
  limitRemaining: number;
  /**
   * Type of limit reset for the API key
   */
  limitReset: string | null;
  /**
   * Legacy rate limit information about a key. Will always return -1.
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  rateLimit: RateLimit;
  /**
   * Total OpenRouter credit usage (in USD) for the API key
   */
  usage: number;
  /**
   * OpenRouter credit usage (in USD) for the current UTC day
   */
  usageDaily: number;
  /**
   * OpenRouter credit usage (in USD) for the current UTC month
   */
  usageMonthly: number;
  /**
   * OpenRouter credit usage (in USD) for the current UTC week (Monday-Sunday)
   */
  usageWeekly: number;
};

/**
 * API key details
 */
export type GetCurrentKeyResponse = {
  /**
   * Current API key information
   */
  data: GetCurrentKeyData;
};

/** @internal */
export type GetCurrentKeyRequest$Outbound = {
  "HTTP-Referer"?: string | undefined;
  appTitle?: string | undefined;
  appCategories?: string | undefined;
};

/** @internal */
export const GetCurrentKeyRequest$outboundSchema: z.ZodType<
  GetCurrentKeyRequest$Outbound,
  GetCurrentKeyRequest
> = z.object({
  httpReferer: z.string().optional(),
  appTitle: z.string().optional(),
  appCategories: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    httpReferer: "HTTP-Referer",
  });
});

export function getCurrentKeyRequestToJSON(
  getCurrentKeyRequest: GetCurrentKeyRequest,
): string {
  return JSON.stringify(
    GetCurrentKeyRequest$outboundSchema.parse(getCurrentKeyRequest),
  );
}

/** @internal */
export const RateLimit$inboundSchema: z.ZodType<RateLimit, unknown> = z.object({
  interval: z.string(),
  note: z.string(),
  requests: z.int(),
});

export function rateLimitFromJSON(
  jsonString: string,
): SafeParseResult<RateLimit, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RateLimit$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RateLimit' from JSON`,
  );
}

/** @internal */
export const GetCurrentKeyData$inboundSchema: z.ZodType<
  GetCurrentKeyData,
  unknown
> = z.object({
  byok_usage: z.number(),
  byok_usage_daily: z.number(),
  byok_usage_monthly: z.number(),
  byok_usage_weekly: z.number(),
  creator_user_id: z.nullable(z.string()),
  expires_at: z.nullable(
    z.iso.datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  include_byok_in_limit: z.boolean(),
  is_free_tier: z.boolean(),
  is_management_key: z.boolean(),
  is_provisioning_key: z.boolean(),
  label: z.string(),
  limit: z.number(),
  limit_remaining: z.number(),
  limit_reset: z.nullable(z.string()),
  rate_limit: z.lazy(() => RateLimit$inboundSchema),
  usage: z.number(),
  usage_daily: z.number(),
  usage_monthly: z.number(),
  usage_weekly: z.number(),
}).transform((v) => {
  return remap$(v, {
    "byok_usage": "byokUsage",
    "byok_usage_daily": "byokUsageDaily",
    "byok_usage_monthly": "byokUsageMonthly",
    "byok_usage_weekly": "byokUsageWeekly",
    "creator_user_id": "creatorUserId",
    "expires_at": "expiresAt",
    "include_byok_in_limit": "includeByokInLimit",
    "is_free_tier": "isFreeTier",
    "is_management_key": "isManagementKey",
    "is_provisioning_key": "isProvisioningKey",
    "limit_remaining": "limitRemaining",
    "limit_reset": "limitReset",
    "rate_limit": "rateLimit",
    "usage_daily": "usageDaily",
    "usage_monthly": "usageMonthly",
    "usage_weekly": "usageWeekly",
  });
});

export function getCurrentKeyDataFromJSON(
  jsonString: string,
): SafeParseResult<GetCurrentKeyData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCurrentKeyData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCurrentKeyData' from JSON`,
  );
}

/** @internal */
export const GetCurrentKeyResponse$inboundSchema: z.ZodType<
  GetCurrentKeyResponse,
  unknown
> = z.object({
  data: z.lazy(() => GetCurrentKeyData$inboundSchema),
});

export function getCurrentKeyResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetCurrentKeyResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCurrentKeyResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCurrentKeyResponse' from JSON`,
  );
}
