/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 5a16015b4d1f
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetGuardrailGlobals = {
  /**
   * The app identifier should be your app's URL and is used as the primary identifier for rankings.
   *
   * @remarks
   * This is used to track API usage per application.
   */
  httpReferer?: string | undefined;
  /**
   * The app display name allows you to customize how your app appears in OpenRouter's dashboard.
   *
   * @remarks
   */
  appTitle?: string | undefined;
  /**
   * Comma-separated list of app categories (e.g. "cli-agent,cloud-agent"). Used for marketplace rankings.
   *
   * @remarks
   */
  appCategories?: string | undefined;
};

export type GetGuardrailRequest = {
  /**
   * The app identifier should be your app's URL and is used as the primary identifier for rankings.
   *
   * @remarks
   * This is used to track API usage per application.
   */
  httpReferer?: string | undefined;
  /**
   * The app display name allows you to customize how your app appears in OpenRouter's dashboard.
   *
   * @remarks
   */
  appTitle?: string | undefined;
  /**
   * Comma-separated list of app categories (e.g. "cli-agent,cloud-agent"). Used for marketplace rankings.
   *
   * @remarks
   */
  appCategories?: string | undefined;
  /**
   * The unique identifier of the guardrail to retrieve
   */
  id: string;
};

/** @internal */
export type GetGuardrailRequest$Outbound = {
  "HTTP-Referer"?: string | undefined;
  appTitle?: string | undefined;
  appCategories?: string | undefined;
  id: string;
};

/** @internal */
export const GetGuardrailRequest$outboundSchema: z.ZodType<
  GetGuardrailRequest$Outbound,
  GetGuardrailRequest
> = z.object({
  httpReferer: z.string().optional(),
  appTitle: z.string().optional(),
  appCategories: z.string().optional(),
  id: z.string(),
}).transform((v) => {
  return remap$(v, {
    httpReferer: "HTTP-Referer",
  });
});

export function getGuardrailRequestToJSON(
  getGuardrailRequest: GetGuardrailRequest,
): string {
  return JSON.stringify(
    GetGuardrailRequest$outboundSchema.parse(getGuardrailRequest),
  );
}
