/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f1343fbaaed5
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export type GetModelsGlobals = {
  /**
   * The app identifier should be your app's URL and is used as the primary identifier for rankings.
   *
   * @remarks
   * This is used to track API usage per application.
   */
  httpReferer?: string | undefined;
  /**
   * The app display name allows you to customize how your app appears in OpenRouter's dashboard.
   *
   * @remarks
   */
  appTitle?: string | undefined;
  /**
   * Comma-separated list of app categories (e.g. "cli-agent,cloud-agent"). Used for marketplace rankings.
   *
   * @remarks
   */
  appCategories?: string | undefined;
};

/**
 * Filter models by use case category
 */
export const Category = {
  Programming: "programming",
  Roleplay: "roleplay",
  Marketing: "marketing",
  MarketingSeo: "marketing/seo",
  Technology: "technology",
  Science: "science",
  Translation: "translation",
  Legal: "legal",
  Finance: "finance",
  Health: "health",
  Trivia: "trivia",
  Academia: "academia",
} as const;
/**
 * Filter models by use case category
 */
export type Category = OpenEnum<typeof Category>;

export type GetModelsRequest = {
  /**
   * The app identifier should be your app's URL and is used as the primary identifier for rankings.
   *
   * @remarks
   * This is used to track API usage per application.
   */
  httpReferer?: string | undefined;
  /**
   * The app display name allows you to customize how your app appears in OpenRouter's dashboard.
   *
   * @remarks
   */
  appTitle?: string | undefined;
  /**
   * Comma-separated list of app categories (e.g. "cli-agent,cloud-agent"). Used for marketplace rankings.
   *
   * @remarks
   */
  appCategories?: string | undefined;
  /**
   * Filter models by use case category
   */
  category?: Category | undefined;
  /**
   * Filter models by supported parameter (comma-separated)
   */
  supportedParameters?: string | undefined;
  /**
   * Filter models by output modality. Accepts a comma-separated list of modalities (text, image, audio, embeddings) or "all" to include all models. Defaults to "text".
   */
  outputModalities?: string | undefined;
};

/** @internal */
export const Category$outboundSchema: z.ZodType<string, Category> = openEnums
  .outboundSchema(Category);

/** @internal */
export type GetModelsRequest$Outbound = {
  "HTTP-Referer"?: string | undefined;
  appTitle?: string | undefined;
  appCategories?: string | undefined;
  category?: string | undefined;
  supported_parameters?: string | undefined;
  output_modalities?: string | undefined;
};

/** @internal */
export const GetModelsRequest$outboundSchema: z.ZodType<
  GetModelsRequest$Outbound,
  GetModelsRequest
> = z.object({
  httpReferer: z.string().optional(),
  appTitle: z.string().optional(),
  appCategories: z.string().optional(),
  category: Category$outboundSchema.optional(),
  supportedParameters: z.string().optional(),
  outputModalities: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    httpReferer: "HTTP-Referer",
    supportedParameters: "supported_parameters",
    outputModalities: "output_modalities",
  });
});

export function getModelsRequestToJSON(
  getModelsRequest: GetModelsRequest,
): string {
  return JSON.stringify(
    GetModelsRequest$outboundSchema.parse(getModelsRequest),
  );
}
