/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 19535b4511a4
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetUserActivityGlobals = {
  /**
   * The app identifier should be your app's URL and is used as the primary identifier for rankings.
   *
   * @remarks
   * This is used to track API usage per application.
   */
  httpReferer?: string | undefined;
  /**
   * The app display name allows you to customize how your app appears in OpenRouter's dashboard.
   *
   * @remarks
   */
  appTitle?: string | undefined;
  /**
   * Comma-separated list of app categories (e.g. "cli-agent,cloud-agent"). Used for marketplace rankings.
   *
   * @remarks
   */
  appCategories?: string | undefined;
};

export type GetUserActivityRequest = {
  /**
   * The app identifier should be your app's URL and is used as the primary identifier for rankings.
   *
   * @remarks
   * This is used to track API usage per application.
   */
  httpReferer?: string | undefined;
  /**
   * The app display name allows you to customize how your app appears in OpenRouter's dashboard.
   *
   * @remarks
   */
  appTitle?: string | undefined;
  /**
   * Comma-separated list of app categories (e.g. "cli-agent,cloud-agent"). Used for marketplace rankings.
   *
   * @remarks
   */
  appCategories?: string | undefined;
  /**
   * Filter by a single UTC date in the last 30 days (YYYY-MM-DD format).
   */
  date?: string | undefined;
  /**
   * Filter by API key hash (SHA-256 hex string, as returned by the keys API).
   */
  apiKeyHash?: string | undefined;
  /**
   * Filter by org member user ID. Only applicable for organization accounts.
   */
  userId?: string | undefined;
};

/** @internal */
export type GetUserActivityRequest$Outbound = {
  "HTTP-Referer"?: string | undefined;
  appTitle?: string | undefined;
  appCategories?: string | undefined;
  date?: string | undefined;
  api_key_hash?: string | undefined;
  user_id?: string | undefined;
};

/** @internal */
export const GetUserActivityRequest$outboundSchema: z.ZodType<
  GetUserActivityRequest$Outbound,
  GetUserActivityRequest
> = z.object({
  httpReferer: z.string().optional(),
  appTitle: z.string().optional(),
  appCategories: z.string().optional(),
  date: z.string().optional(),
  apiKeyHash: z.string().optional(),
  userId: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    httpReferer: "HTTP-Referer",
    apiKeyHash: "api_key_hash",
    userId: "user_id",
  });
});

export function getUserActivityRequestToJSON(
  getUserActivityRequest: GetUserActivityRequest,
): string {
  return JSON.stringify(
    GetUserActivityRequest$outboundSchema.parse(getUserActivityRequest),
  );
}
