/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: ce11386ad30f
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListGlobals = {
  /**
   * The app identifier should be your app's URL and is used as the primary identifier for rankings.
   *
   * @remarks
   * This is used to track API usage per application.
   */
  httpReferer?: string | undefined;
  /**
   * The app display name allows you to customize how your app appears in OpenRouter's dashboard.
   *
   * @remarks
   */
  appTitle?: string | undefined;
  /**
   * Comma-separated list of app categories (e.g. "cli-agent,cloud-agent"). Used for marketplace rankings.
   *
   * @remarks
   */
  appCategories?: string | undefined;
};

export type ListRequest = {
  /**
   * The app identifier should be your app's URL and is used as the primary identifier for rankings.
   *
   * @remarks
   * This is used to track API usage per application.
   */
  httpReferer?: string | undefined;
  /**
   * The app display name allows you to customize how your app appears in OpenRouter's dashboard.
   *
   * @remarks
   */
  appTitle?: string | undefined;
  /**
   * Comma-separated list of app categories (e.g. "cli-agent,cloud-agent"). Used for marketplace rankings.
   *
   * @remarks
   */
  appCategories?: string | undefined;
  /**
   * Whether to include disabled API keys in the response
   */
  includeDisabled?: boolean | undefined;
  /**
   * Number of API keys to skip for pagination
   */
  offset?: number | undefined;
};

export type ListData = {
  /**
   * Total external BYOK usage (in USD) for the API key
   */
  byokUsage: number;
  /**
   * External BYOK usage (in USD) for the current UTC day
   */
  byokUsageDaily: number;
  /**
   * External BYOK usage (in USD) for current UTC month
   */
  byokUsageMonthly: number;
  /**
   * External BYOK usage (in USD) for the current UTC week (Monday-Sunday)
   */
  byokUsageWeekly: number;
  /**
   * ISO 8601 timestamp of when the API key was created
   */
  createdAt: string;
  /**
   * The user ID of the key creator. For organization-owned keys, this is the member who created the key. For individual users, this is the user's own ID.
   */
  creatorUserId: string | null;
  /**
   * Whether the API key is disabled
   */
  disabled: boolean;
  /**
   * ISO 8601 UTC timestamp when the API key expires, or null if no expiration
   */
  expiresAt?: Date | null | undefined;
  /**
   * Unique hash identifier for the API key
   */
  hash: string;
  /**
   * Whether to include external BYOK usage in the credit limit
   */
  includeByokInLimit: boolean;
  /**
   * Human-readable label for the API key
   */
  label: string;
  /**
   * Spending limit for the API key in USD
   */
  limit: number;
  /**
   * Remaining spending limit in USD
   */
  limitRemaining: number;
  /**
   * Type of limit reset for the API key
   */
  limitReset: string | null;
  /**
   * Name of the API key
   */
  name: string;
  /**
   * ISO 8601 timestamp of when the API key was last updated
   */
  updatedAt: string | null;
  /**
   * Total OpenRouter credit usage (in USD) for the API key
   */
  usage: number;
  /**
   * OpenRouter credit usage (in USD) for the current UTC day
   */
  usageDaily: number;
  /**
   * OpenRouter credit usage (in USD) for the current UTC month
   */
  usageMonthly: number;
  /**
   * OpenRouter credit usage (in USD) for the current UTC week (Monday-Sunday)
   */
  usageWeekly: number;
};

/**
 * List of API keys
 */
export type ListResponse = {
  /**
   * List of API keys
   */
  data: Array<ListData>;
};

/** @internal */
export type ListRequest$Outbound = {
  "HTTP-Referer"?: string | undefined;
  appTitle?: string | undefined;
  appCategories?: string | undefined;
  include_disabled?: boolean | undefined;
  offset?: number | undefined;
};

/** @internal */
export const ListRequest$outboundSchema: z.ZodType<
  ListRequest$Outbound,
  ListRequest
> = z.object({
  httpReferer: z.string().optional(),
  appTitle: z.string().optional(),
  appCategories: z.string().optional(),
  includeDisabled: z.boolean().optional(),
  offset: z.int().optional(),
}).transform((v) => {
  return remap$(v, {
    httpReferer: "HTTP-Referer",
    includeDisabled: "include_disabled",
  });
});

export function listRequestToJSON(listRequest: ListRequest): string {
  return JSON.stringify(ListRequest$outboundSchema.parse(listRequest));
}

/** @internal */
export const ListData$inboundSchema: z.ZodType<ListData, unknown> = z.object({
  byok_usage: z.number(),
  byok_usage_daily: z.number(),
  byok_usage_monthly: z.number(),
  byok_usage_weekly: z.number(),
  created_at: z.string(),
  creator_user_id: z.nullable(z.string()),
  disabled: z.boolean(),
  expires_at: z.nullable(
    z.iso.datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  hash: z.string(),
  include_byok_in_limit: z.boolean(),
  label: z.string(),
  limit: z.number(),
  limit_remaining: z.number(),
  limit_reset: z.nullable(z.string()),
  name: z.string(),
  updated_at: z.nullable(z.string()),
  usage: z.number(),
  usage_daily: z.number(),
  usage_monthly: z.number(),
  usage_weekly: z.number(),
}).transform((v) => {
  return remap$(v, {
    "byok_usage": "byokUsage",
    "byok_usage_daily": "byokUsageDaily",
    "byok_usage_monthly": "byokUsageMonthly",
    "byok_usage_weekly": "byokUsageWeekly",
    "created_at": "createdAt",
    "creator_user_id": "creatorUserId",
    "expires_at": "expiresAt",
    "include_byok_in_limit": "includeByokInLimit",
    "limit_remaining": "limitRemaining",
    "limit_reset": "limitReset",
    "updated_at": "updatedAt",
    "usage_daily": "usageDaily",
    "usage_monthly": "usageMonthly",
    "usage_weekly": "usageWeekly",
  });
});

export function listDataFromJSON(
  jsonString: string,
): SafeParseResult<ListData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListData' from JSON`,
  );
}

/** @internal */
export const ListResponse$inboundSchema: z.ZodType<ListResponse, unknown> = z
  .object({
    data: z.array(z.lazy(() => ListData$inboundSchema)),
  });

export function listResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListResponse' from JSON`,
  );
}
