/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4c71cf4db173
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ListGuardrailsGlobals = {
  /**
   * The app identifier should be your app's URL and is used as the primary identifier for rankings.
   *
   * @remarks
   * This is used to track API usage per application.
   */
  httpReferer?: string | undefined;
  /**
   * The app display name allows you to customize how your app appears in OpenRouter's dashboard.
   *
   * @remarks
   */
  appTitle?: string | undefined;
  /**
   * Comma-separated list of app categories (e.g. "cli-agent,cloud-agent"). Used for marketplace rankings.
   *
   * @remarks
   */
  appCategories?: string | undefined;
};

export type ListGuardrailsRequest = {
  /**
   * The app identifier should be your app's URL and is used as the primary identifier for rankings.
   *
   * @remarks
   * This is used to track API usage per application.
   */
  httpReferer?: string | undefined;
  /**
   * The app display name allows you to customize how your app appears in OpenRouter's dashboard.
   *
   * @remarks
   */
  appTitle?: string | undefined;
  /**
   * Comma-separated list of app categories (e.g. "cli-agent,cloud-agent"). Used for marketplace rankings.
   *
   * @remarks
   */
  appCategories?: string | undefined;
  /**
   * Number of records to skip for pagination
   */
  offset?: number | undefined;
  /**
   * Maximum number of records to return (max 100)
   */
  limit?: number | undefined;
};

export type ListGuardrailsResponse = {
  result: models.ListGuardrailsResponse;
};

/** @internal */
export type ListGuardrailsRequest$Outbound = {
  "HTTP-Referer"?: string | undefined;
  appTitle?: string | undefined;
  appCategories?: string | undefined;
  offset?: number | undefined;
  limit?: number | undefined;
};

/** @internal */
export const ListGuardrailsRequest$outboundSchema: z.ZodType<
  ListGuardrailsRequest$Outbound,
  ListGuardrailsRequest
> = z.object({
  httpReferer: z.string().optional(),
  appTitle: z.string().optional(),
  appCategories: z.string().optional(),
  offset: z.int().optional(),
  limit: z.int().optional(),
}).transform((v) => {
  return remap$(v, {
    httpReferer: "HTTP-Referer",
  });
});

export function listGuardrailsRequestToJSON(
  listGuardrailsRequest: ListGuardrailsRequest,
): string {
  return JSON.stringify(
    ListGuardrailsRequest$outboundSchema.parse(listGuardrailsRequest),
  );
}

/** @internal */
export const ListGuardrailsResponse$inboundSchema: z.ZodType<
  ListGuardrailsResponse,
  unknown
> = z.object({
  Result: models.ListGuardrailsResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Result": "result",
  });
});

export function listGuardrailsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListGuardrailsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListGuardrailsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListGuardrailsResponse' from JSON`,
  );
}
