/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 37ee24c57c33
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ListGuardrailMemberAssignmentsGlobals = {
  /**
   * The app identifier should be your app's URL and is used as the primary identifier for rankings.
   *
   * @remarks
   * This is used to track API usage per application.
   */
  httpReferer?: string | undefined;
  /**
   * The app display name allows you to customize how your app appears in OpenRouter's dashboard.
   *
   * @remarks
   */
  appTitle?: string | undefined;
  /**
   * Comma-separated list of app categories (e.g. "cli-agent,cloud-agent"). Used for marketplace rankings.
   *
   * @remarks
   */
  appCategories?: string | undefined;
};

export type ListGuardrailMemberAssignmentsRequest = {
  /**
   * The app identifier should be your app's URL and is used as the primary identifier for rankings.
   *
   * @remarks
   * This is used to track API usage per application.
   */
  httpReferer?: string | undefined;
  /**
   * The app display name allows you to customize how your app appears in OpenRouter's dashboard.
   *
   * @remarks
   */
  appTitle?: string | undefined;
  /**
   * Comma-separated list of app categories (e.g. "cli-agent,cloud-agent"). Used for marketplace rankings.
   *
   * @remarks
   */
  appCategories?: string | undefined;
  /**
   * The unique identifier of the guardrail
   */
  id: string;
  /**
   * Number of records to skip for pagination
   */
  offset?: number | undefined;
  /**
   * Maximum number of records to return (max 100)
   */
  limit?: number | undefined;
};

export type ListGuardrailMemberAssignmentsResponse = {
  result: models.ListMemberAssignmentsResponse;
};

/** @internal */
export type ListGuardrailMemberAssignmentsRequest$Outbound = {
  "HTTP-Referer"?: string | undefined;
  appTitle?: string | undefined;
  appCategories?: string | undefined;
  id: string;
  offset?: number | undefined;
  limit?: number | undefined;
};

/** @internal */
export const ListGuardrailMemberAssignmentsRequest$outboundSchema: z.ZodType<
  ListGuardrailMemberAssignmentsRequest$Outbound,
  ListGuardrailMemberAssignmentsRequest
> = z.object({
  httpReferer: z.string().optional(),
  appTitle: z.string().optional(),
  appCategories: z.string().optional(),
  id: z.string(),
  offset: z.int().optional(),
  limit: z.int().optional(),
}).transform((v) => {
  return remap$(v, {
    httpReferer: "HTTP-Referer",
  });
});

export function listGuardrailMemberAssignmentsRequestToJSON(
  listGuardrailMemberAssignmentsRequest: ListGuardrailMemberAssignmentsRequest,
): string {
  return JSON.stringify(
    ListGuardrailMemberAssignmentsRequest$outboundSchema.parse(
      listGuardrailMemberAssignmentsRequest,
    ),
  );
}

/** @internal */
export const ListGuardrailMemberAssignmentsResponse$inboundSchema: z.ZodType<
  ListGuardrailMemberAssignmentsResponse,
  unknown
> = z.object({
  Result: models.ListMemberAssignmentsResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Result": "result",
  });
});

export function listGuardrailMemberAssignmentsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListGuardrailMemberAssignmentsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ListGuardrailMemberAssignmentsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListGuardrailMemberAssignmentsResponse' from JSON`,
  );
}
