/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: cc21259f09b8
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListOrganizationMembersGlobals = {
  /**
   * The app identifier should be your app's URL and is used as the primary identifier for rankings.
   *
   * @remarks
   * This is used to track API usage per application.
   */
  httpReferer?: string | undefined;
  /**
   * The app display name allows you to customize how your app appears in OpenRouter's dashboard.
   *
   * @remarks
   */
  appTitle?: string | undefined;
  /**
   * Comma-separated list of app categories (e.g. "cli-agent,cloud-agent"). Used for marketplace rankings.
   *
   * @remarks
   */
  appCategories?: string | undefined;
};

export type ListOrganizationMembersRequest = {
  /**
   * The app identifier should be your app's URL and is used as the primary identifier for rankings.
   *
   * @remarks
   * This is used to track API usage per application.
   */
  httpReferer?: string | undefined;
  /**
   * The app display name allows you to customize how your app appears in OpenRouter's dashboard.
   *
   * @remarks
   */
  appTitle?: string | undefined;
  /**
   * Comma-separated list of app categories (e.g. "cli-agent,cloud-agent"). Used for marketplace rankings.
   *
   * @remarks
   */
  appCategories?: string | undefined;
  /**
   * Number of records to skip for pagination
   */
  offset?: number | undefined;
  /**
   * Maximum number of records to return (max 100)
   */
  limit?: number | undefined;
};

/**
 * Role of the member in the organization
 */
export const Role = {
  OrgAdmin: "org:admin",
  OrgMember: "org:member",
} as const;
/**
 * Role of the member in the organization
 */
export type Role = OpenEnum<typeof Role>;

export type ListOrganizationMembersData = {
  /**
   * Email address of the member
   */
  email: string;
  /**
   * First name of the member
   */
  firstName: string | null;
  /**
   * User ID of the organization member
   */
  id: string;
  /**
   * Last name of the member
   */
  lastName: string | null;
  /**
   * Role of the member in the organization
   */
  role: Role;
};

/**
 * List of organization members
 */
export type ListOrganizationMembersResponseBody = {
  /**
   * List of organization members
   */
  data: Array<ListOrganizationMembersData>;
  /**
   * Total number of members in the organization
   */
  totalCount: number;
};

export type ListOrganizationMembersResponse = {
  result: ListOrganizationMembersResponseBody;
};

/** @internal */
export type ListOrganizationMembersRequest$Outbound = {
  "HTTP-Referer"?: string | undefined;
  appTitle?: string | undefined;
  appCategories?: string | undefined;
  offset?: number | undefined;
  limit?: number | undefined;
};

/** @internal */
export const ListOrganizationMembersRequest$outboundSchema: z.ZodType<
  ListOrganizationMembersRequest$Outbound,
  ListOrganizationMembersRequest
> = z.object({
  httpReferer: z.string().optional(),
  appTitle: z.string().optional(),
  appCategories: z.string().optional(),
  offset: z.int().optional(),
  limit: z.int().optional(),
}).transform((v) => {
  return remap$(v, {
    httpReferer: "HTTP-Referer",
  });
});

export function listOrganizationMembersRequestToJSON(
  listOrganizationMembersRequest: ListOrganizationMembersRequest,
): string {
  return JSON.stringify(
    ListOrganizationMembersRequest$outboundSchema.parse(
      listOrganizationMembersRequest,
    ),
  );
}

/** @internal */
export const Role$inboundSchema: z.ZodType<Role, unknown> = openEnums
  .inboundSchema(Role);

/** @internal */
export const ListOrganizationMembersData$inboundSchema: z.ZodType<
  ListOrganizationMembersData,
  unknown
> = z.object({
  email: z.string(),
  first_name: z.nullable(z.string()),
  id: z.string(),
  last_name: z.nullable(z.string()),
  role: Role$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "first_name": "firstName",
    "last_name": "lastName",
  });
});

export function listOrganizationMembersDataFromJSON(
  jsonString: string,
): SafeParseResult<ListOrganizationMembersData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListOrganizationMembersData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListOrganizationMembersData' from JSON`,
  );
}

/** @internal */
export const ListOrganizationMembersResponseBody$inboundSchema: z.ZodType<
  ListOrganizationMembersResponseBody,
  unknown
> = z.object({
  data: z.array(z.lazy(() => ListOrganizationMembersData$inboundSchema)),
  total_count: z.int(),
}).transform((v) => {
  return remap$(v, {
    "total_count": "totalCount",
  });
});

export function listOrganizationMembersResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ListOrganizationMembersResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ListOrganizationMembersResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListOrganizationMembersResponseBody' from JSON`,
  );
}

/** @internal */
export const ListOrganizationMembersResponse$inboundSchema: z.ZodType<
  ListOrganizationMembersResponse,
  unknown
> = z.object({
  Result: z.lazy(() => ListOrganizationMembersResponseBody$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "Result": "result",
  });
});

export function listOrganizationMembersResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListOrganizationMembersResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListOrganizationMembersResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListOrganizationMembersResponse' from JSON`,
  );
}
