/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: ee2d86453873
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ActivityItem = {
  /**
   * BYOK inference cost in USD (external credits spent)
   */
  byokUsageInference: number;
  /**
   * Total completion tokens generated
   */
  completionTokens: number;
  /**
   * Date of the activity (YYYY-MM-DD format)
   */
  date: string;
  /**
   * Unique identifier for the endpoint
   */
  endpointId: string;
  /**
   * Model slug (e.g., "openai/gpt-4.1")
   */
  model: string;
  /**
   * Model permaslug (e.g., "openai/gpt-4.1-2025-04-14")
   */
  modelPermaslug: string;
  /**
   * Total prompt tokens used
   */
  promptTokens: number;
  /**
   * Name of the provider serving this endpoint
   */
  providerName: string;
  /**
   * Total reasoning tokens used
   */
  reasoningTokens: number;
  /**
   * Number of requests made
   */
  requests: number;
  /**
   * Total cost in USD (OpenRouter credits spent)
   */
  usage: number;
};

/** @internal */
export const ActivityItem$inboundSchema: z.ZodType<ActivityItem, unknown> = z
  .object({
    byok_usage_inference: z.number(),
    completion_tokens: z.int(),
    date: z.string(),
    endpoint_id: z.string(),
    model: z.string(),
    model_permaslug: z.string(),
    prompt_tokens: z.int(),
    provider_name: z.string(),
    reasoning_tokens: z.int(),
    requests: z.int(),
    usage: z.number(),
  }).transform((v) => {
    return remap$(v, {
      "byok_usage_inference": "byokUsageInference",
      "completion_tokens": "completionTokens",
      "endpoint_id": "endpointId",
      "model_permaslug": "modelPermaslug",
      "prompt_tokens": "promptTokens",
      "provider_name": "providerName",
      "reasoning_tokens": "reasoningTokens",
    });
  });

export function activityItemFromJSON(
  jsonString: string,
): SafeParseResult<ActivityItem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ActivityItem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ActivityItem' from JSON`,
  );
}
