/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e8b49d71cdd5
 */

import * as z from "zod/v4";
import { ClosedEnum } from "../types/enums.js";
import {
  AnthropicCacheControlTtl,
  AnthropicCacheControlTtl$outboundSchema,
} from "./anthropiccachecontrolttl.js";

export const AnthropicCacheControlDirectiveType = {
  Ephemeral: "ephemeral",
} as const;
export type AnthropicCacheControlDirectiveType = ClosedEnum<
  typeof AnthropicCacheControlDirectiveType
>;

/**
 * Enable automatic prompt caching. When set, the system automatically applies cache breakpoints to the last cacheable block in the request. Currently supported for Anthropic Claude models.
 */
export type AnthropicCacheControlDirective = {
  ttl?: AnthropicCacheControlTtl | undefined;
  type: AnthropicCacheControlDirectiveType;
};

/** @internal */
export const AnthropicCacheControlDirectiveType$outboundSchema: z.ZodEnum<
  typeof AnthropicCacheControlDirectiveType
> = z.enum(AnthropicCacheControlDirectiveType);

/** @internal */
export type AnthropicCacheControlDirective$Outbound = {
  ttl?: string | undefined;
  type: string;
};

/** @internal */
export const AnthropicCacheControlDirective$outboundSchema: z.ZodType<
  AnthropicCacheControlDirective$Outbound,
  AnthropicCacheControlDirective
> = z.object({
  ttl: AnthropicCacheControlTtl$outboundSchema.optional(),
  type: AnthropicCacheControlDirectiveType$outboundSchema,
});

export function anthropicCacheControlDirectiveToJSON(
  anthropicCacheControlDirective: AnthropicCacheControlDirective,
): string {
  return JSON.stringify(
    AnthropicCacheControlDirective$outboundSchema.parse(
      anthropicCacheControlDirective,
    ),
  );
}
