/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e3853c83720d
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";

export type AutoRouterPlugin = {
  /**
   * List of model patterns to filter which models the auto-router can route between. Supports wildcards (e.g., "anthropic/*" matches all Anthropic models). When not specified, uses the default supported models list.
   */
  allowedModels?: Array<string> | undefined;
  /**
   * Set to false to disable the auto-router plugin for this request. Defaults to true.
   */
  enabled?: boolean | undefined;
  id: "auto-router";
};

/** @internal */
export type AutoRouterPlugin$Outbound = {
  allowed_models?: Array<string> | undefined;
  enabled?: boolean | undefined;
  id: "auto-router";
};

/** @internal */
export const AutoRouterPlugin$outboundSchema: z.ZodType<
  AutoRouterPlugin$Outbound,
  AutoRouterPlugin
> = z.object({
  allowedModels: z.array(z.string()).optional(),
  enabled: z.boolean().optional(),
  id: z.literal("auto-router"),
}).transform((v) => {
  return remap$(v, {
    allowedModels: "allowed_models",
  });
});

export function autoRouterPluginToJSON(
  autoRouterPlugin: AutoRouterPlugin,
): string {
  return JSON.stringify(
    AutoRouterPlugin$outboundSchema.parse(autoRouterPlugin),
  );
}
