/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 7237afe9aafd
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import * as discriminatedUnionTypes from "../types/discriminatedUnion.js";
import { discriminatedUnion } from "../types/discriminatedUnion.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { InputAudio, InputAudio$inboundSchema } from "./inputaudio.js";
import { InputFile, InputFile$inboundSchema } from "./inputfile.js";
import { InputImage, InputImage$inboundSchema } from "./inputimage.js";
import { InputText, InputText$inboundSchema } from "./inputtext.js";
import {
  OpenAIResponseFunctionToolCall,
  OpenAIResponseFunctionToolCall$inboundSchema,
} from "./openairesponsefunctiontoolcall.js";
import {
  OpenAIResponseFunctionToolCallOutput,
  OpenAIResponseFunctionToolCallOutput$inboundSchema,
} from "./openairesponsefunctiontoolcalloutput.js";
import {
  OpenAIResponseInputMessageItem,
  OpenAIResponseInputMessageItem$inboundSchema,
} from "./openairesponseinputmessageitem.js";
import {
  OutputItemImageGenerationCall,
  OutputItemImageGenerationCall$inboundSchema,
} from "./outputitemimagegenerationcall.js";
import { OutputMessage, OutputMessage$inboundSchema } from "./outputmessage.js";

export type BaseInputsContent1 =
  | InputAudio
  | InputFile
  | (InputImage & { type: "input_image" })
  | InputText
  | discriminatedUnionTypes.Unknown<"type">;

export type BaseInputsContent2 =
  | Array<
    | InputAudio
    | InputFile
    | (InputImage & { type: "input_image" })
    | InputText
    | discriminatedUnionTypes.Unknown<"type">
  >
  | string;

export const BaseInputsPhaseFinalAnswer = {
  FinalAnswer: "final_answer",
} as const;
export type BaseInputsPhaseFinalAnswer = ClosedEnum<
  typeof BaseInputsPhaseFinalAnswer
>;

export const BaseInputsPhaseCommentary = {
  Commentary: "commentary",
} as const;
export type BaseInputsPhaseCommentary = ClosedEnum<
  typeof BaseInputsPhaseCommentary
>;

export type BaseInputsPhaseUnion =
  | BaseInputsPhaseCommentary
  | BaseInputsPhaseFinalAnswer
  | any;

export const BaseInputsRoleDeveloper = {
  Developer: "developer",
} as const;
export type BaseInputsRoleDeveloper = ClosedEnum<
  typeof BaseInputsRoleDeveloper
>;

export const BaseInputsRoleAssistant = {
  Assistant: "assistant",
} as const;
export type BaseInputsRoleAssistant = ClosedEnum<
  typeof BaseInputsRoleAssistant
>;

export const BaseInputsRoleSystem = {
  System: "system",
} as const;
export type BaseInputsRoleSystem = ClosedEnum<typeof BaseInputsRoleSystem>;

export const BaseInputsRoleUser = {
  User: "user",
} as const;
export type BaseInputsRoleUser = ClosedEnum<typeof BaseInputsRoleUser>;

export type BaseInputsRoleUnion =
  | BaseInputsRoleUser
  | BaseInputsRoleSystem
  | BaseInputsRoleAssistant
  | BaseInputsRoleDeveloper;

export const BaseInputsType = {
  Message: "message",
} as const;
export type BaseInputsType = ClosedEnum<typeof BaseInputsType>;

export type BaseInputsMessage = {
  content:
    | Array<
      | InputAudio
      | InputFile
      | (InputImage & { type: "input_image" })
      | InputText
      | discriminatedUnionTypes.Unknown<"type">
    >
    | string;
  phase?:
    | BaseInputsPhaseCommentary
    | BaseInputsPhaseFinalAnswer
    | any
    | null
    | undefined;
  role:
    | BaseInputsRoleUser
    | BaseInputsRoleSystem
    | BaseInputsRoleAssistant
    | BaseInputsRoleDeveloper;
  type?: BaseInputsType | undefined;
};

export type BaseInputsUnion1 =
  | OpenAIResponseFunctionToolCall
  | OutputMessage
  | OpenAIResponseInputMessageItem
  | OpenAIResponseFunctionToolCallOutput
  | OutputItemImageGenerationCall
  | BaseInputsMessage;

export type BaseInputsUnion =
  | string
  | Array<
    | OpenAIResponseFunctionToolCall
    | OutputMessage
    | OpenAIResponseInputMessageItem
    | OpenAIResponseFunctionToolCallOutput
    | OutputItemImageGenerationCall
    | BaseInputsMessage
  >
  | any;

/** @internal */
export const BaseInputsContent1$inboundSchema: z.ZodType<
  BaseInputsContent1,
  unknown
> = discriminatedUnion("type", {
  input_audio: InputAudio$inboundSchema,
  input_file: InputFile$inboundSchema,
  input_image: InputImage$inboundSchema.and(
    z.object({ type: z.literal("input_image") }),
  ),
  input_text: InputText$inboundSchema,
});

export function baseInputsContent1FromJSON(
  jsonString: string,
): SafeParseResult<BaseInputsContent1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BaseInputsContent1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BaseInputsContent1' from JSON`,
  );
}

/** @internal */
export const BaseInputsContent2$inboundSchema: z.ZodType<
  BaseInputsContent2,
  unknown
> = z.union([
  z.array(discriminatedUnion("type", {
    input_audio: InputAudio$inboundSchema,
    input_file: InputFile$inboundSchema,
    input_image: InputImage$inboundSchema.and(
      z.object({ type: z.literal("input_image") }),
    ),
    input_text: InputText$inboundSchema,
  })),
  z.string(),
]);

export function baseInputsContent2FromJSON(
  jsonString: string,
): SafeParseResult<BaseInputsContent2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BaseInputsContent2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BaseInputsContent2' from JSON`,
  );
}

/** @internal */
export const BaseInputsPhaseFinalAnswer$inboundSchema: z.ZodEnum<
  typeof BaseInputsPhaseFinalAnswer
> = z.enum(BaseInputsPhaseFinalAnswer);

/** @internal */
export const BaseInputsPhaseCommentary$inboundSchema: z.ZodEnum<
  typeof BaseInputsPhaseCommentary
> = z.enum(BaseInputsPhaseCommentary);

/** @internal */
export const BaseInputsPhaseUnion$inboundSchema: z.ZodType<
  BaseInputsPhaseUnion,
  unknown
> = z.union([
  BaseInputsPhaseCommentary$inboundSchema,
  BaseInputsPhaseFinalAnswer$inboundSchema,
  z.any(),
]);

export function baseInputsPhaseUnionFromJSON(
  jsonString: string,
): SafeParseResult<BaseInputsPhaseUnion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BaseInputsPhaseUnion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BaseInputsPhaseUnion' from JSON`,
  );
}

/** @internal */
export const BaseInputsRoleDeveloper$inboundSchema: z.ZodEnum<
  typeof BaseInputsRoleDeveloper
> = z.enum(BaseInputsRoleDeveloper);

/** @internal */
export const BaseInputsRoleAssistant$inboundSchema: z.ZodEnum<
  typeof BaseInputsRoleAssistant
> = z.enum(BaseInputsRoleAssistant);

/** @internal */
export const BaseInputsRoleSystem$inboundSchema: z.ZodEnum<
  typeof BaseInputsRoleSystem
> = z.enum(BaseInputsRoleSystem);

/** @internal */
export const BaseInputsRoleUser$inboundSchema: z.ZodEnum<
  typeof BaseInputsRoleUser
> = z.enum(BaseInputsRoleUser);

/** @internal */
export const BaseInputsRoleUnion$inboundSchema: z.ZodType<
  BaseInputsRoleUnion,
  unknown
> = z.union([
  BaseInputsRoleUser$inboundSchema,
  BaseInputsRoleSystem$inboundSchema,
  BaseInputsRoleAssistant$inboundSchema,
  BaseInputsRoleDeveloper$inboundSchema,
]);

export function baseInputsRoleUnionFromJSON(
  jsonString: string,
): SafeParseResult<BaseInputsRoleUnion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BaseInputsRoleUnion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BaseInputsRoleUnion' from JSON`,
  );
}

/** @internal */
export const BaseInputsType$inboundSchema: z.ZodEnum<typeof BaseInputsType> = z
  .enum(BaseInputsType);

/** @internal */
export const BaseInputsMessage$inboundSchema: z.ZodType<
  BaseInputsMessage,
  unknown
> = z.object({
  content: z.union([
    z.array(discriminatedUnion("type", {
      input_audio: InputAudio$inboundSchema,
      input_file: InputFile$inboundSchema,
      input_image: InputImage$inboundSchema.and(
        z.object({ type: z.literal("input_image") }),
      ),
      input_text: InputText$inboundSchema,
    })),
    z.string(),
  ]),
  phase: z.nullable(
    z.union([
      BaseInputsPhaseCommentary$inboundSchema,
      BaseInputsPhaseFinalAnswer$inboundSchema,
      z.any(),
    ]),
  ).optional(),
  role: z.union([
    BaseInputsRoleUser$inboundSchema,
    BaseInputsRoleSystem$inboundSchema,
    BaseInputsRoleAssistant$inboundSchema,
    BaseInputsRoleDeveloper$inboundSchema,
  ]),
  type: BaseInputsType$inboundSchema.optional(),
});

export function baseInputsMessageFromJSON(
  jsonString: string,
): SafeParseResult<BaseInputsMessage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BaseInputsMessage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BaseInputsMessage' from JSON`,
  );
}

/** @internal */
export const BaseInputsUnion1$inboundSchema: z.ZodType<
  BaseInputsUnion1,
  unknown
> = z.union([
  OpenAIResponseFunctionToolCall$inboundSchema,
  OutputMessage$inboundSchema,
  OpenAIResponseInputMessageItem$inboundSchema,
  OpenAIResponseFunctionToolCallOutput$inboundSchema,
  OutputItemImageGenerationCall$inboundSchema,
  z.lazy(() => BaseInputsMessage$inboundSchema),
]);

export function baseInputsUnion1FromJSON(
  jsonString: string,
): SafeParseResult<BaseInputsUnion1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BaseInputsUnion1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BaseInputsUnion1' from JSON`,
  );
}

/** @internal */
export const BaseInputsUnion$inboundSchema: z.ZodType<
  BaseInputsUnion,
  unknown
> = z.union([
  z.string(),
  z.array(
    z.union([
      OpenAIResponseFunctionToolCall$inboundSchema,
      OutputMessage$inboundSchema,
      OpenAIResponseInputMessageItem$inboundSchema,
      OpenAIResponseFunctionToolCallOutput$inboundSchema,
      OutputItemImageGenerationCall$inboundSchema,
      z.lazy(() => BaseInputsMessage$inboundSchema),
    ]),
  ),
  z.any(),
]);

export function baseInputsUnionFromJSON(
  jsonString: string,
): SafeParseResult<BaseInputsUnion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BaseInputsUnion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BaseInputsUnion' from JSON`,
  );
}
