/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4d3857aa5f6c
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type BulkUnassignMembersResponse = {
  /**
   * Number of members successfully unassigned
   */
  unassignedCount: number;
};

/** @internal */
export const BulkUnassignMembersResponse$inboundSchema: z.ZodType<
  BulkUnassignMembersResponse,
  unknown
> = z.object({
  unassigned_count: z.int(),
}).transform((v) => {
  return remap$(v, {
    "unassigned_count": "unassignedCount",
  });
});

export function bulkUnassignMembersResponseFromJSON(
  jsonString: string,
): SafeParseResult<BulkUnassignMembersResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BulkUnassignMembersResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BulkUnassignMembersResponse' from JSON`,
  );
}
