/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e773f6f68c24
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";

export type BulkUnassignKeysRequest = {
  /**
   * Array of API key hashes to unassign from the guardrail
   */
  keyHashes: Array<string>;
};

/** @internal */
export type BulkUnassignKeysRequest$Outbound = {
  key_hashes: Array<string>;
};

/** @internal */
export const BulkUnassignKeysRequest$outboundSchema: z.ZodType<
  BulkUnassignKeysRequest$Outbound,
  BulkUnassignKeysRequest
> = z.object({
  keyHashes: z.array(z.string()),
}).transform((v) => {
  return remap$(v, {
    keyHashes: "key_hashes",
  });
});

export function bulkUnassignKeysRequestToJSON(
  bulkUnassignKeysRequest: BulkUnassignKeysRequest,
): string {
  return JSON.stringify(
    BulkUnassignKeysRequest$outboundSchema.parse(bulkUnassignKeysRequest),
  );
}
