/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 5906bcf3a524
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type BulkUnassignKeysResponse = {
  /**
   * Number of keys successfully unassigned
   */
  unassignedCount: number;
};

/** @internal */
export const BulkUnassignKeysResponse$inboundSchema: z.ZodType<
  BulkUnassignKeysResponse,
  unknown
> = z.object({
  unassigned_count: z.int(),
}).transform((v) => {
  return remap$(v, {
    "unassigned_count": "unassignedCount",
  });
});

export function bulkUnassignKeysResponseFromJSON(
  jsonString: string,
): SafeParseResult<BulkUnassignKeysResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BulkUnassignKeysResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BulkUnassignKeysResponse' from JSON`,
  );
}
