/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c8f692e7b579
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type BulkAssignKeysResponse = {
  /**
   * Number of keys successfully assigned
   */
  assignedCount: number;
};

/** @internal */
export const BulkAssignKeysResponse$inboundSchema: z.ZodType<
  BulkAssignKeysResponse,
  unknown
> = z.object({
  assigned_count: z.int(),
}).transform((v) => {
  return remap$(v, {
    "assigned_count": "assignedCount",
  });
});

export function bulkAssignKeysResponseFromJSON(
  jsonString: string,
): SafeParseResult<BulkAssignKeysResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BulkAssignKeysResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BulkAssignKeysResponse' from JSON`,
  );
}
