/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 6a179ea58260
 */

import * as z from "zod/v4";
import {
  ChatContentText,
  ChatContentText$Outbound,
  ChatContentText$outboundSchema,
} from "./chatcontenttext.js";

/**
 * Developer message content
 */
export type ChatDeveloperMessageContent = string | Array<ChatContentText>;

/**
 * Developer message
 */
export type ChatDeveloperMessage = {
  /**
   * Developer message content
   */
  content: string | Array<ChatContentText>;
  /**
   * Optional name for the developer message
   */
  name?: string | undefined;
  role: "developer";
};

/** @internal */
export type ChatDeveloperMessageContent$Outbound =
  | string
  | Array<ChatContentText$Outbound>;

/** @internal */
export const ChatDeveloperMessageContent$outboundSchema: z.ZodType<
  ChatDeveloperMessageContent$Outbound,
  ChatDeveloperMessageContent
> = z.union([z.string(), z.array(ChatContentText$outboundSchema)]);

export function chatDeveloperMessageContentToJSON(
  chatDeveloperMessageContent: ChatDeveloperMessageContent,
): string {
  return JSON.stringify(
    ChatDeveloperMessageContent$outboundSchema.parse(
      chatDeveloperMessageContent,
    ),
  );
}

/** @internal */
export type ChatDeveloperMessage$Outbound = {
  content: string | Array<ChatContentText$Outbound>;
  name?: string | undefined;
  role: "developer";
};

/** @internal */
export const ChatDeveloperMessage$outboundSchema: z.ZodType<
  ChatDeveloperMessage$Outbound,
  ChatDeveloperMessage
> = z.object({
  content: z.union([z.string(), z.array(ChatContentText$outboundSchema)]),
  name: z.string().optional(),
  role: z.literal("developer"),
});

export function chatDeveloperMessageToJSON(
  chatDeveloperMessage: ChatDeveloperMessage,
): string {
  return JSON.stringify(
    ChatDeveloperMessage$outboundSchema.parse(chatDeveloperMessage),
  );
}
