/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 09b5a48d2bab
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  ChatContentCacheControl,
  ChatContentCacheControl$inboundSchema,
  ChatContentCacheControl$Outbound,
  ChatContentCacheControl$outboundSchema,
} from "./chatcontentcachecontrol.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const ChatContentTextType = {
  Text: "text",
} as const;
export type ChatContentTextType = ClosedEnum<typeof ChatContentTextType>;

/**
 * Text content part
 */
export type ChatContentText = {
  /**
   * Cache control for the content part
   */
  cacheControl?: ChatContentCacheControl | undefined;
  text: string;
  type: ChatContentTextType;
};

/** @internal */
export const ChatContentTextType$inboundSchema: z.ZodEnum<
  typeof ChatContentTextType
> = z.enum(ChatContentTextType);
/** @internal */
export const ChatContentTextType$outboundSchema: z.ZodEnum<
  typeof ChatContentTextType
> = ChatContentTextType$inboundSchema;

/** @internal */
export const ChatContentText$inboundSchema: z.ZodType<
  ChatContentText,
  unknown
> = z.object({
  cache_control: ChatContentCacheControl$inboundSchema.optional(),
  text: z.string(),
  type: ChatContentTextType$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "cache_control": "cacheControl",
  });
});
/** @internal */
export type ChatContentText$Outbound = {
  cache_control?: ChatContentCacheControl$Outbound | undefined;
  text: string;
  type: string;
};

/** @internal */
export const ChatContentText$outboundSchema: z.ZodType<
  ChatContentText$Outbound,
  ChatContentText
> = z.object({
  cacheControl: ChatContentCacheControl$outboundSchema.optional(),
  text: z.string(),
  type: ChatContentTextType$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    cacheControl: "cache_control",
  });
});

export function chatContentTextToJSON(
  chatContentText: ChatContentText,
): string {
  return JSON.stringify(ChatContentText$outboundSchema.parse(chatContentText));
}
export function chatContentTextFromJSON(
  jsonString: string,
): SafeParseResult<ChatContentText, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChatContentText$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatContentText' from JSON`,
  );
}
