/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: bc876a8e64eb
 */

import * as z from "zod/v4";
import { ClosedEnum } from "../types/enums.js";

export type ChatNamedToolChoiceFunction = {
  /**
   * Function name to call
   */
  name: string;
};

export const ChatNamedToolChoiceType = {
  Function: "function",
} as const;
export type ChatNamedToolChoiceType = ClosedEnum<
  typeof ChatNamedToolChoiceType
>;

/**
 * Named tool choice for specific function
 */
export type ChatNamedToolChoice = {
  function: ChatNamedToolChoiceFunction;
  type: ChatNamedToolChoiceType;
};

/** @internal */
export type ChatNamedToolChoiceFunction$Outbound = {
  name: string;
};

/** @internal */
export const ChatNamedToolChoiceFunction$outboundSchema: z.ZodType<
  ChatNamedToolChoiceFunction$Outbound,
  ChatNamedToolChoiceFunction
> = z.object({
  name: z.string(),
});

export function chatNamedToolChoiceFunctionToJSON(
  chatNamedToolChoiceFunction: ChatNamedToolChoiceFunction,
): string {
  return JSON.stringify(
    ChatNamedToolChoiceFunction$outboundSchema.parse(
      chatNamedToolChoiceFunction,
    ),
  );
}

/** @internal */
export const ChatNamedToolChoiceType$outboundSchema: z.ZodEnum<
  typeof ChatNamedToolChoiceType
> = z.enum(ChatNamedToolChoiceType);

/** @internal */
export type ChatNamedToolChoice$Outbound = {
  function: ChatNamedToolChoiceFunction$Outbound;
  type: string;
};

/** @internal */
export const ChatNamedToolChoice$outboundSchema: z.ZodType<
  ChatNamedToolChoice$Outbound,
  ChatNamedToolChoice
> = z.object({
  function: z.lazy(() => ChatNamedToolChoiceFunction$outboundSchema),
  type: ChatNamedToolChoiceType$outboundSchema,
});

export function chatNamedToolChoiceToJSON(
  chatNamedToolChoice: ChatNamedToolChoice,
): string {
  return JSON.stringify(
    ChatNamedToolChoice$outboundSchema.parse(chatNamedToolChoice),
  );
}
