/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 0f458a760f42
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ChatContentAudioInputAudio = {
  /**
   * Base64 encoded audio data
   */
  data: string;
  /**
   * Audio format (e.g., wav, mp3, flac, m4a, ogg, aiff, aac, pcm16, pcm24). Supported formats vary by provider.
   */
  format: string;
};

/**
 * Audio input content part. Supported audio formats vary by provider.
 */
export type ChatContentAudio = {
  inputAudio: ChatContentAudioInputAudio;
  type: "input_audio";
};

/** @internal */
export const ChatContentAudioInputAudio$inboundSchema: z.ZodType<
  ChatContentAudioInputAudio,
  unknown
> = z.object({
  data: z.string(),
  format: z.string(),
});
/** @internal */
export type ChatContentAudioInputAudio$Outbound = {
  data: string;
  format: string;
};

/** @internal */
export const ChatContentAudioInputAudio$outboundSchema: z.ZodType<
  ChatContentAudioInputAudio$Outbound,
  ChatContentAudioInputAudio
> = z.object({
  data: z.string(),
  format: z.string(),
});

export function chatContentAudioInputAudioToJSON(
  chatContentAudioInputAudio: ChatContentAudioInputAudio,
): string {
  return JSON.stringify(
    ChatContentAudioInputAudio$outboundSchema.parse(chatContentAudioInputAudio),
  );
}
export function chatContentAudioInputAudioFromJSON(
  jsonString: string,
): SafeParseResult<ChatContentAudioInputAudio, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChatContentAudioInputAudio$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatContentAudioInputAudio' from JSON`,
  );
}

/** @internal */
export const ChatContentAudio$inboundSchema: z.ZodType<
  ChatContentAudio,
  unknown
> = z.object({
  input_audio: z.lazy(() => ChatContentAudioInputAudio$inboundSchema),
  type: z.literal("input_audio"),
}).transform((v) => {
  return remap$(v, {
    "input_audio": "inputAudio",
  });
});
/** @internal */
export type ChatContentAudio$Outbound = {
  input_audio: ChatContentAudioInputAudio$Outbound;
  type: "input_audio";
};

/** @internal */
export const ChatContentAudio$outboundSchema: z.ZodType<
  ChatContentAudio$Outbound,
  ChatContentAudio
> = z.object({
  inputAudio: z.lazy(() => ChatContentAudioInputAudio$outboundSchema),
  type: z.literal("input_audio"),
}).transform((v) => {
  return remap$(v, {
    inputAudio: "input_audio",
  });
});

export function chatContentAudioToJSON(
  chatContentAudio: ChatContentAudio,
): string {
  return JSON.stringify(
    ChatContentAudio$outboundSchema.parse(chatContentAudio),
  );
}
export function chatContentAudioFromJSON(
  jsonString: string,
): SafeParseResult<ChatContentAudio, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChatContentAudio$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatContentAudio' from JSON`,
  );
}
