/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e404d41c140a
 */

import * as z from "zod/v4";
import {
  ChatContentText,
  ChatContentText$Outbound,
  ChatContentText$outboundSchema,
} from "./chatcontenttext.js";

/**
 * System message content
 */
export type ChatSystemMessageContent = string | Array<ChatContentText>;

/**
 * System message for setting behavior
 */
export type ChatSystemMessage = {
  /**
   * System message content
   */
  content: string | Array<ChatContentText>;
  /**
   * Optional name for the system message
   */
  name?: string | undefined;
  role: "system";
};

/** @internal */
export type ChatSystemMessageContent$Outbound =
  | string
  | Array<ChatContentText$Outbound>;

/** @internal */
export const ChatSystemMessageContent$outboundSchema: z.ZodType<
  ChatSystemMessageContent$Outbound,
  ChatSystemMessageContent
> = z.union([z.string(), z.array(ChatContentText$outboundSchema)]);

export function chatSystemMessageContentToJSON(
  chatSystemMessageContent: ChatSystemMessageContent,
): string {
  return JSON.stringify(
    ChatSystemMessageContent$outboundSchema.parse(chatSystemMessageContent),
  );
}

/** @internal */
export type ChatSystemMessage$Outbound = {
  content: string | Array<ChatContentText$Outbound>;
  name?: string | undefined;
  role: "system";
};

/** @internal */
export const ChatSystemMessage$outboundSchema: z.ZodType<
  ChatSystemMessage$Outbound,
  ChatSystemMessage
> = z.object({
  content: z.union([z.string(), z.array(ChatContentText$outboundSchema)]),
  name: z.string().optional(),
  role: z.literal("system"),
});

export function chatSystemMessageToJSON(
  chatSystemMessage: ChatSystemMessage,
): string {
  return JSON.stringify(
    ChatSystemMessage$outboundSchema.parse(chatSystemMessage),
  );
}
