/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 692ef1eded11
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Audio output data or reference
 */
export type ChatAudioOutput = {
  /**
   * Base64 encoded audio data
   */
  data?: string | undefined;
  /**
   * Audio expiration timestamp
   */
  expiresAt?: number | undefined;
  /**
   * Audio output identifier
   */
  id?: string | undefined;
  /**
   * Audio transcript
   */
  transcript?: string | undefined;
};

/** @internal */
export const ChatAudioOutput$inboundSchema: z.ZodType<
  ChatAudioOutput,
  unknown
> = z.object({
  data: z.string().optional(),
  expires_at: z.int().optional(),
  id: z.string().optional(),
  transcript: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "expires_at": "expiresAt",
  });
});
/** @internal */
export type ChatAudioOutput$Outbound = {
  data?: string | undefined;
  expires_at?: number | undefined;
  id?: string | undefined;
  transcript?: string | undefined;
};

/** @internal */
export const ChatAudioOutput$outboundSchema: z.ZodType<
  ChatAudioOutput$Outbound,
  ChatAudioOutput
> = z.object({
  data: z.string().optional(),
  expiresAt: z.int().optional(),
  id: z.string().optional(),
  transcript: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    expiresAt: "expires_at",
  });
});

export function chatAudioOutputToJSON(
  chatAudioOutput: ChatAudioOutput,
): string {
  return JSON.stringify(ChatAudioOutput$outboundSchema.parse(chatAudioOutput));
}
export function chatAudioOutputFromJSON(
  jsonString: string,
): SafeParseResult<ChatAudioOutput, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChatAudioOutput$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatAudioOutput' from JSON`,
  );
}
