/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 7e02597be9a9
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import {
  ChatJsonSchemaConfig,
  ChatJsonSchemaConfig$Outbound,
  ChatJsonSchemaConfig$outboundSchema,
} from "./chatjsonschemaconfig.js";

/**
 * JSON Schema response format for structured outputs
 */
export type ChatFormatJsonSchemaConfig = {
  /**
   * JSON Schema configuration object
   */
  jsonSchema: ChatJsonSchemaConfig;
  type: "json_schema";
};

/** @internal */
export type ChatFormatJsonSchemaConfig$Outbound = {
  json_schema: ChatJsonSchemaConfig$Outbound;
  type: "json_schema";
};

/** @internal */
export const ChatFormatJsonSchemaConfig$outboundSchema: z.ZodType<
  ChatFormatJsonSchemaConfig$Outbound,
  ChatFormatJsonSchemaConfig
> = z.object({
  jsonSchema: ChatJsonSchemaConfig$outboundSchema,
  type: z.literal("json_schema"),
}).transform((v) => {
  return remap$(v, {
    jsonSchema: "json_schema",
  });
});

export function chatFormatJsonSchemaConfigToJSON(
  chatFormatJsonSchemaConfig: ChatFormatJsonSchemaConfig,
): string {
  return JSON.stringify(
    ChatFormatJsonSchemaConfig$outboundSchema.parse(chatFormatJsonSchemaConfig),
  );
}
