/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a67d6bbce478
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import {
  SearchQualityLevel,
  SearchQualityLevel$outboundSchema,
} from "./searchqualitylevel.js";
import {
  WebSearchConfig,
  WebSearchConfig$Outbound,
  WebSearchConfig$outboundSchema,
} from "./websearchconfig.js";
import {
  WebSearchEngineEnum,
  WebSearchEngineEnum$outboundSchema,
} from "./websearchengineenum.js";
import {
  WebSearchUserLocationServerTool,
  WebSearchUserLocationServerTool$Outbound,
  WebSearchUserLocationServerTool$outboundSchema,
} from "./websearchuserlocationservertool.js";

export const ChatWebSearchShorthandType = {
  WebSearch: "web_search",
  WebSearchPreview: "web_search_preview",
  WebSearchPreview20250311: "web_search_preview_2025_03_11",
  WebSearch20250826: "web_search_2025_08_26",
} as const;
export type ChatWebSearchShorthandType = OpenEnum<
  typeof ChatWebSearchShorthandType
>;

/**
 * Web search tool using OpenAI Responses API syntax. Automatically converted to openrouter:web_search.
 */
export type ChatWebSearchShorthand = {
  /**
   * Limit search results to these domains. Supported by Exa, Parallel, and most native providers (Anthropic, OpenAI, xAI). Not supported with Firecrawl or Perplexity.
   */
  allowedDomains?: Array<string> | undefined;
  /**
   * Which search engine to use. "auto" (default) uses native if the provider supports it, otherwise Exa. "native" forces the provider's built-in search. "exa" forces the Exa search API. "firecrawl" uses Firecrawl (requires BYOK). "parallel" uses the Parallel search API.
   */
  engine?: WebSearchEngineEnum | undefined;
  /**
   * Exclude search results from these domains. Supported by Exa, Parallel, Anthropic, and xAI. Not supported with Firecrawl, OpenAI (silently ignored), or Perplexity.
   */
  excludedDomains?: Array<string> | undefined;
  /**
   * Maximum number of search results to return per search call. Defaults to 5. Applies to Exa, Firecrawl, and Parallel engines; ignored with native provider search.
   */
  maxResults?: number | undefined;
  /**
   * Maximum total number of search results across all search calls in a single request. Once this limit is reached, the tool will stop returning new results. Useful for controlling cost and context size in agentic loops.
   */
  maxTotalResults?: number | undefined;
  parameters?: WebSearchConfig | undefined;
  /**
   * How much context to retrieve per result. Defaults to medium (15000 chars). Only applies when using the Exa engine; ignored with native provider search.
   */
  searchContextSize?: SearchQualityLevel | undefined;
  type: ChatWebSearchShorthandType;
  /**
   * Approximate user location for location-biased results.
   */
  userLocation?: WebSearchUserLocationServerTool | undefined;
};

/** @internal */
export const ChatWebSearchShorthandType$outboundSchema: z.ZodType<
  string,
  ChatWebSearchShorthandType
> = openEnums.outboundSchema(ChatWebSearchShorthandType);

/** @internal */
export type ChatWebSearchShorthand$Outbound = {
  allowed_domains?: Array<string> | undefined;
  engine?: string | undefined;
  excluded_domains?: Array<string> | undefined;
  max_results?: number | undefined;
  max_total_results?: number | undefined;
  parameters?: WebSearchConfig$Outbound | undefined;
  search_context_size?: string | undefined;
  type: string;
  user_location?: WebSearchUserLocationServerTool$Outbound | undefined;
};

/** @internal */
export const ChatWebSearchShorthand$outboundSchema: z.ZodType<
  ChatWebSearchShorthand$Outbound,
  ChatWebSearchShorthand
> = z.object({
  allowedDomains: z.array(z.string()).optional(),
  engine: WebSearchEngineEnum$outboundSchema.optional(),
  excludedDomains: z.array(z.string()).optional(),
  maxResults: z.int().optional(),
  maxTotalResults: z.int().optional(),
  parameters: WebSearchConfig$outboundSchema.optional(),
  searchContextSize: SearchQualityLevel$outboundSchema.optional(),
  type: ChatWebSearchShorthandType$outboundSchema,
  userLocation: WebSearchUserLocationServerTool$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    allowedDomains: "allowed_domains",
    excludedDomains: "excluded_domains",
    maxResults: "max_results",
    maxTotalResults: "max_total_results",
    searchContextSize: "search_context_size",
    userLocation: "user_location",
  });
});

export function chatWebSearchShorthandToJSON(
  chatWebSearchShorthand: ChatWebSearchShorthand,
): string {
  return JSON.stringify(
    ChatWebSearchShorthand$outboundSchema.parse(chatWebSearchShorthand),
  );
}
