/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 3747d92a0ba4
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  ChatFinishReasonEnum,
  ChatFinishReasonEnum$inboundSchema,
} from "./chatfinishreasonenum.js";
import {
  ChatStreamDelta,
  ChatStreamDelta$inboundSchema,
} from "./chatstreamdelta.js";
import {
  ChatTokenLogprobs,
  ChatTokenLogprobs$inboundSchema,
} from "./chattokenlogprobs.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Streaming completion choice chunk
 */
export type ChatStreamChoice = {
  /**
   * Delta changes in streaming response
   */
  delta: ChatStreamDelta;
  finishReason: ChatFinishReasonEnum | null;
  /**
   * Choice index
   */
  index: number;
  /**
   * Log probabilities for the completion
   */
  logprobs?: ChatTokenLogprobs | null | undefined;
};

/** @internal */
export const ChatStreamChoice$inboundSchema: z.ZodType<
  ChatStreamChoice,
  unknown
> = z.object({
  delta: ChatStreamDelta$inboundSchema,
  finish_reason: z.nullable(ChatFinishReasonEnum$inboundSchema),
  index: z.int(),
  logprobs: z.nullable(ChatTokenLogprobs$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "finish_reason": "finishReason",
  });
});

export function chatStreamChoiceFromJSON(
  jsonString: string,
): SafeParseResult<ChatStreamChoice, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChatStreamChoice$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatStreamChoice' from JSON`,
  );
}
