/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 2826e2627ca8
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  AnthropicCacheControlTtl,
  AnthropicCacheControlTtl$inboundSchema,
  AnthropicCacheControlTtl$outboundSchema,
} from "./anthropiccachecontrolttl.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const ChatContentCacheControlType = {
  Ephemeral: "ephemeral",
} as const;
export type ChatContentCacheControlType = ClosedEnum<
  typeof ChatContentCacheControlType
>;

/**
 * Cache control for the content part
 */
export type ChatContentCacheControl = {
  ttl?: AnthropicCacheControlTtl | undefined;
  type: ChatContentCacheControlType;
};

/** @internal */
export const ChatContentCacheControlType$inboundSchema: z.ZodEnum<
  typeof ChatContentCacheControlType
> = z.enum(ChatContentCacheControlType);
/** @internal */
export const ChatContentCacheControlType$outboundSchema: z.ZodEnum<
  typeof ChatContentCacheControlType
> = ChatContentCacheControlType$inboundSchema;

/** @internal */
export const ChatContentCacheControl$inboundSchema: z.ZodType<
  ChatContentCacheControl,
  unknown
> = z.object({
  ttl: AnthropicCacheControlTtl$inboundSchema.optional(),
  type: ChatContentCacheControlType$inboundSchema,
});
/** @internal */
export type ChatContentCacheControl$Outbound = {
  ttl?: string | undefined;
  type: string;
};

/** @internal */
export const ChatContentCacheControl$outboundSchema: z.ZodType<
  ChatContentCacheControl$Outbound,
  ChatContentCacheControl
> = z.object({
  ttl: AnthropicCacheControlTtl$outboundSchema.optional(),
  type: ChatContentCacheControlType$outboundSchema,
});

export function chatContentCacheControlToJSON(
  chatContentCacheControl: ChatContentCacheControl,
): string {
  return JSON.stringify(
    ChatContentCacheControl$outboundSchema.parse(chatContentCacheControl),
  );
}
export function chatContentCacheControlFromJSON(
  jsonString: string,
): SafeParseResult<ChatContentCacheControl, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChatContentCacheControl$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatContentCacheControl' from JSON`,
  );
}
