/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f15fee305732
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ChatToolCallFunction = {
  /**
   * Function arguments as JSON string
   */
  arguments: string;
  /**
   * Function name to call
   */
  name: string;
};

export const ChatToolCallType = {
  Function: "function",
} as const;
export type ChatToolCallType = ClosedEnum<typeof ChatToolCallType>;

/**
 * Tool call made by the assistant
 */
export type ChatToolCall = {
  function: ChatToolCallFunction;
  /**
   * Tool call identifier
   */
  id: string;
  type: ChatToolCallType;
};

/** @internal */
export const ChatToolCallFunction$inboundSchema: z.ZodType<
  ChatToolCallFunction,
  unknown
> = z.object({
  arguments: z.string(),
  name: z.string(),
});
/** @internal */
export type ChatToolCallFunction$Outbound = {
  arguments: string;
  name: string;
};

/** @internal */
export const ChatToolCallFunction$outboundSchema: z.ZodType<
  ChatToolCallFunction$Outbound,
  ChatToolCallFunction
> = z.object({
  arguments: z.string(),
  name: z.string(),
});

export function chatToolCallFunctionToJSON(
  chatToolCallFunction: ChatToolCallFunction,
): string {
  return JSON.stringify(
    ChatToolCallFunction$outboundSchema.parse(chatToolCallFunction),
  );
}
export function chatToolCallFunctionFromJSON(
  jsonString: string,
): SafeParseResult<ChatToolCallFunction, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChatToolCallFunction$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatToolCallFunction' from JSON`,
  );
}

/** @internal */
export const ChatToolCallType$inboundSchema: z.ZodEnum<
  typeof ChatToolCallType
> = z.enum(ChatToolCallType);
/** @internal */
export const ChatToolCallType$outboundSchema: z.ZodEnum<
  typeof ChatToolCallType
> = ChatToolCallType$inboundSchema;

/** @internal */
export const ChatToolCall$inboundSchema: z.ZodType<ChatToolCall, unknown> = z
  .object({
    function: z.lazy(() => ChatToolCallFunction$inboundSchema),
    id: z.string(),
    type: ChatToolCallType$inboundSchema,
  });
/** @internal */
export type ChatToolCall$Outbound = {
  function: ChatToolCallFunction$Outbound;
  id: string;
  type: string;
};

/** @internal */
export const ChatToolCall$outboundSchema: z.ZodType<
  ChatToolCall$Outbound,
  ChatToolCall
> = z.object({
  function: z.lazy(() => ChatToolCallFunction$outboundSchema),
  id: z.string(),
  type: ChatToolCallType$outboundSchema,
});

export function chatToolCallToJSON(chatToolCall: ChatToolCall): string {
  return JSON.stringify(ChatToolCall$outboundSchema.parse(chatToolCall));
}
export function chatToolCallFromJSON(
  jsonString: string,
): SafeParseResult<ChatToolCall, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChatToolCall$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatToolCall' from JSON`,
  );
}
