/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d8ae826b4712
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  ChatAssistantImages,
  ChatAssistantImages$inboundSchema,
  ChatAssistantImages$Outbound,
  ChatAssistantImages$outboundSchema,
} from "./chatassistantimages.js";
import {
  ChatAudioOutput,
  ChatAudioOutput$inboundSchema,
  ChatAudioOutput$Outbound,
  ChatAudioOutput$outboundSchema,
} from "./chataudiooutput.js";
import {
  ChatContentItems,
  ChatContentItems$inboundSchema,
  ChatContentItems$Outbound,
  ChatContentItems$outboundSchema,
} from "./chatcontentitems.js";
import {
  ChatToolCall,
  ChatToolCall$inboundSchema,
  ChatToolCall$Outbound,
  ChatToolCall$outboundSchema,
} from "./chattoolcall.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  ReasoningDetailUnion,
  ReasoningDetailUnion$inboundSchema,
  ReasoningDetailUnion$Outbound,
  ReasoningDetailUnion$outboundSchema,
} from "./reasoningdetailunion.js";

/**
 * Assistant message content
 */
export type ChatAssistantMessageContent =
  | string
  | Array<ChatContentItems>
  | any;

export const ChatAssistantMessageRole = {
  Assistant: "assistant",
} as const;
export type ChatAssistantMessageRole = ClosedEnum<
  typeof ChatAssistantMessageRole
>;

/**
 * Assistant message for requests and responses
 */
export type ChatAssistantMessage = {
  /**
   * Audio output data or reference
   */
  audio?: ChatAudioOutput | undefined;
  /**
   * Assistant message content
   */
  content?: string | Array<ChatContentItems> | any | null | undefined;
  /**
   * Generated images from image generation models
   */
  images?: Array<ChatAssistantImages> | undefined;
  /**
   * Optional name for the assistant
   */
  name?: string | undefined;
  /**
   * Reasoning output
   */
  reasoning?: string | null | undefined;
  /**
   * Reasoning details for extended thinking models
   */
  reasoningDetails?: Array<ReasoningDetailUnion> | undefined;
  /**
   * Refusal message if content was refused
   */
  refusal?: string | null | undefined;
  role: ChatAssistantMessageRole;
  /**
   * Tool calls made by the assistant
   */
  toolCalls?: Array<ChatToolCall> | undefined;
};

/** @internal */
export const ChatAssistantMessageContent$inboundSchema: z.ZodType<
  ChatAssistantMessageContent,
  unknown
> = z.union([z.string(), z.array(ChatContentItems$inboundSchema), z.any()]);
/** @internal */
export type ChatAssistantMessageContent$Outbound =
  | string
  | Array<ChatContentItems$Outbound>
  | any;

/** @internal */
export const ChatAssistantMessageContent$outboundSchema: z.ZodType<
  ChatAssistantMessageContent$Outbound,
  ChatAssistantMessageContent
> = z.union([z.string(), z.array(ChatContentItems$outboundSchema), z.any()]);

export function chatAssistantMessageContentToJSON(
  chatAssistantMessageContent: ChatAssistantMessageContent,
): string {
  return JSON.stringify(
    ChatAssistantMessageContent$outboundSchema.parse(
      chatAssistantMessageContent,
    ),
  );
}
export function chatAssistantMessageContentFromJSON(
  jsonString: string,
): SafeParseResult<ChatAssistantMessageContent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChatAssistantMessageContent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatAssistantMessageContent' from JSON`,
  );
}

/** @internal */
export const ChatAssistantMessageRole$inboundSchema: z.ZodEnum<
  typeof ChatAssistantMessageRole
> = z.enum(ChatAssistantMessageRole);
/** @internal */
export const ChatAssistantMessageRole$outboundSchema: z.ZodEnum<
  typeof ChatAssistantMessageRole
> = ChatAssistantMessageRole$inboundSchema;

/** @internal */
export const ChatAssistantMessage$inboundSchema: z.ZodType<
  ChatAssistantMessage,
  unknown
> = z.object({
  audio: ChatAudioOutput$inboundSchema.optional(),
  content: z.nullable(
    z.union([z.string(), z.array(ChatContentItems$inboundSchema), z.any()]),
  ).optional(),
  images: z.array(ChatAssistantImages$inboundSchema).optional(),
  name: z.string().optional(),
  reasoning: z.nullable(z.string()).optional(),
  reasoning_details: z.array(ReasoningDetailUnion$inboundSchema).optional(),
  refusal: z.nullable(z.string()).optional(),
  role: ChatAssistantMessageRole$inboundSchema,
  tool_calls: z.array(ChatToolCall$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "reasoning_details": "reasoningDetails",
    "tool_calls": "toolCalls",
  });
});
/** @internal */
export type ChatAssistantMessage$Outbound = {
  audio?: ChatAudioOutput$Outbound | undefined;
  content?: string | Array<ChatContentItems$Outbound> | any | null | undefined;
  images?: Array<ChatAssistantImages$Outbound> | undefined;
  name?: string | undefined;
  reasoning?: string | null | undefined;
  reasoning_details?: Array<ReasoningDetailUnion$Outbound> | undefined;
  refusal?: string | null | undefined;
  role: string;
  tool_calls?: Array<ChatToolCall$Outbound> | undefined;
};

/** @internal */
export const ChatAssistantMessage$outboundSchema: z.ZodType<
  ChatAssistantMessage$Outbound,
  ChatAssistantMessage
> = z.object({
  audio: ChatAudioOutput$outboundSchema.optional(),
  content: z.nullable(
    z.union([z.string(), z.array(ChatContentItems$outboundSchema), z.any()]),
  ).optional(),
  images: z.array(ChatAssistantImages$outboundSchema).optional(),
  name: z.string().optional(),
  reasoning: z.nullable(z.string()).optional(),
  reasoningDetails: z.array(ReasoningDetailUnion$outboundSchema).optional(),
  refusal: z.nullable(z.string()).optional(),
  role: ChatAssistantMessageRole$outboundSchema,
  toolCalls: z.array(ChatToolCall$outboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    reasoningDetails: "reasoning_details",
    toolCalls: "tool_calls",
  });
});

export function chatAssistantMessageToJSON(
  chatAssistantMessage: ChatAssistantMessage,
): string {
  return JSON.stringify(
    ChatAssistantMessage$outboundSchema.parse(chatAssistantMessage),
  );
}
export function chatAssistantMessageFromJSON(
  jsonString: string,
): SafeParseResult<ChatAssistantMessage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChatAssistantMessage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatAssistantMessage' from JSON`,
  );
}
