/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: afefd8aadd09
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { ChatChoice, ChatChoice$inboundSchema } from "./chatchoice.js";
import { ChatUsage, ChatUsage$inboundSchema } from "./chatusage.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const ChatResultObject = {
  ChatCompletion: "chat.completion",
} as const;
export type ChatResultObject = ClosedEnum<typeof ChatResultObject>;

/**
 * Chat completion response
 */
export type ChatResult = {
  /**
   * List of completion choices
   */
  choices: Array<ChatChoice>;
  /**
   * Unix timestamp of creation
   */
  created: number;
  /**
   * Unique completion identifier
   */
  id: string;
  /**
   * Model used for completion
   */
  model: string;
  object: ChatResultObject;
  /**
   * The service tier used by the upstream provider for this request
   */
  serviceTier?: string | null | undefined;
  /**
   * System fingerprint
   */
  systemFingerprint: string | null;
  /**
   * Token usage statistics
   */
  usage?: ChatUsage | undefined;
};

/** @internal */
export const ChatResultObject$inboundSchema: z.ZodEnum<
  typeof ChatResultObject
> = z.enum(ChatResultObject);

/** @internal */
export const ChatResult$inboundSchema: z.ZodType<ChatResult, unknown> = z
  .object({
    choices: z.array(ChatChoice$inboundSchema),
    created: z.int(),
    id: z.string(),
    model: z.string(),
    object: ChatResultObject$inboundSchema,
    service_tier: z.nullable(z.string()).optional(),
    system_fingerprint: z.nullable(z.string()),
    usage: ChatUsage$inboundSchema.optional(),
  }).transform((v) => {
    return remap$(v, {
      "service_tier": "serviceTier",
      "system_fingerprint": "systemFingerprint",
    });
  });

export function chatResultFromJSON(
  jsonString: string,
): SafeParseResult<ChatResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChatResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatResult' from JSON`,
  );
}
