/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 267d5cc43c1b
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ChatTokenLogprobTopLogprob = {
  bytes: Array<number> | null;
  logprob: number;
  token: string;
};

/**
 * Token log probability information
 */
export type ChatTokenLogprob = {
  /**
   * UTF-8 bytes of the token
   */
  bytes: Array<number> | null;
  /**
   * Log probability of the token
   */
  logprob: number;
  /**
   * The token
   */
  token: string;
  /**
   * Top alternative tokens with probabilities
   */
  topLogprobs: Array<ChatTokenLogprobTopLogprob>;
};

/** @internal */
export const ChatTokenLogprobTopLogprob$inboundSchema: z.ZodType<
  ChatTokenLogprobTopLogprob,
  unknown
> = z.object({
  bytes: z.nullable(z.array(z.int())),
  logprob: z.number(),
  token: z.string(),
});

export function chatTokenLogprobTopLogprobFromJSON(
  jsonString: string,
): SafeParseResult<ChatTokenLogprobTopLogprob, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChatTokenLogprobTopLogprob$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatTokenLogprobTopLogprob' from JSON`,
  );
}

/** @internal */
export const ChatTokenLogprob$inboundSchema: z.ZodType<
  ChatTokenLogprob,
  unknown
> = z.object({
  bytes: z.nullable(z.array(z.int())),
  logprob: z.number(),
  token: z.string(),
  top_logprobs: z.array(z.lazy(() => ChatTokenLogprobTopLogprob$inboundSchema)),
}).transform((v) => {
  return remap$(v, {
    "top_logprobs": "topLogprobs",
  });
});

export function chatTokenLogprobFromJSON(
  jsonString: string,
): SafeParseResult<ChatTokenLogprob, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChatTokenLogprob$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatTokenLogprob' from JSON`,
  );
}
