/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 3d8c886d8084
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import * as discriminatedUnionTypes from "../types/discriminatedUnion.js";
import { discriminatedUnion } from "../types/discriminatedUnion.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  ChatContentAudio,
  ChatContentAudio$inboundSchema,
  ChatContentAudio$Outbound,
  ChatContentAudio$outboundSchema,
} from "./chatcontentaudio.js";
import {
  ChatContentFile,
  ChatContentFile$inboundSchema,
  ChatContentFile$Outbound,
  ChatContentFile$outboundSchema,
} from "./chatcontentfile.js";
import {
  ChatContentImage,
  ChatContentImage$inboundSchema,
  ChatContentImage$Outbound,
  ChatContentImage$outboundSchema,
} from "./chatcontentimage.js";
import {
  ChatContentText,
  ChatContentText$inboundSchema,
  ChatContentText$Outbound,
  ChatContentText$outboundSchema,
} from "./chatcontenttext.js";
import {
  ChatContentVideo,
  ChatContentVideo$inboundSchema,
  ChatContentVideo$Outbound,
  ChatContentVideo$outboundSchema,
} from "./chatcontentvideo.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  LegacyChatContentVideo,
  LegacyChatContentVideo$inboundSchema,
  LegacyChatContentVideo$Outbound,
  LegacyChatContentVideo$outboundSchema,
} from "./legacychatcontentvideo.js";

/**
 * Content part for chat completion messages
 */
export type ChatContentItems =
  | ChatContentFile
  | ChatContentImage
  | ChatContentAudio
  | LegacyChatContentVideo
  | (ChatContentText & { type: "text" })
  | ChatContentVideo
  | discriminatedUnionTypes.Unknown<"type">;

/** @internal */
export const ChatContentItems$inboundSchema: z.ZodType<
  ChatContentItems,
  unknown
> = discriminatedUnion("type", {
  file: ChatContentFile$inboundSchema,
  image_url: ChatContentImage$inboundSchema,
  input_audio: ChatContentAudio$inboundSchema,
  input_video: LegacyChatContentVideo$inboundSchema,
  text: ChatContentText$inboundSchema.and(
    z.object({ type: z.literal("text") }),
  ),
  video_url: ChatContentVideo$inboundSchema,
});
/** @internal */
export type ChatContentItems$Outbound =
  | ChatContentFile$Outbound
  | ChatContentImage$Outbound
  | ChatContentAudio$Outbound
  | LegacyChatContentVideo$Outbound
  | (ChatContentText$Outbound & { type: "text" })
  | ChatContentVideo$Outbound;

/** @internal */
export const ChatContentItems$outboundSchema: z.ZodType<
  ChatContentItems$Outbound,
  ChatContentItems
> = z.union([
  ChatContentFile$outboundSchema,
  ChatContentImage$outboundSchema,
  ChatContentAudio$outboundSchema,
  LegacyChatContentVideo$outboundSchema,
  ChatContentText$outboundSchema.and(z.object({ type: z.literal("text") })),
  ChatContentVideo$outboundSchema,
]);

export function chatContentItemsToJSON(
  chatContentItems: ChatContentItems,
): string {
  return JSON.stringify(
    ChatContentItems$outboundSchema.parse(chatContentItems),
  );
}
export function chatContentItemsFromJSON(
  jsonString: string,
): SafeParseResult<ChatContentItems, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChatContentItems$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatContentItems' from JSON`,
  );
}
