/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: bc892e4ebadf
 */

import * as z from "zod/v4";
import {
  ChatContentItems,
  ChatContentItems$Outbound,
  ChatContentItems$outboundSchema,
} from "./chatcontentitems.js";

/**
 * User message content
 */
export type ChatUserMessageContent = string | Array<ChatContentItems>;

/**
 * User message
 */
export type ChatUserMessage = {
  /**
   * User message content
   */
  content: string | Array<ChatContentItems>;
  /**
   * Optional name for the user
   */
  name?: string | undefined;
  role: "user";
};

/** @internal */
export type ChatUserMessageContent$Outbound =
  | string
  | Array<ChatContentItems$Outbound>;

/** @internal */
export const ChatUserMessageContent$outboundSchema: z.ZodType<
  ChatUserMessageContent$Outbound,
  ChatUserMessageContent
> = z.union([z.string(), z.array(ChatContentItems$outboundSchema)]);

export function chatUserMessageContentToJSON(
  chatUserMessageContent: ChatUserMessageContent,
): string {
  return JSON.stringify(
    ChatUserMessageContent$outboundSchema.parse(chatUserMessageContent),
  );
}

/** @internal */
export type ChatUserMessage$Outbound = {
  content: string | Array<ChatContentItems$Outbound>;
  name?: string | undefined;
  role: "user";
};

/** @internal */
export const ChatUserMessage$outboundSchema: z.ZodType<
  ChatUserMessage$Outbound,
  ChatUserMessage
> = z.object({
  content: z.union([z.string(), z.array(ChatContentItems$outboundSchema)]),
  name: z.string().optional(),
  role: z.literal("user"),
});

export function chatUserMessageToJSON(
  chatUserMessage: ChatUserMessage,
): string {
  return JSON.stringify(ChatUserMessage$outboundSchema.parse(chatUserMessage));
}
