/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: bad96c4eeaf7
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Function call details
 */
export type ChatStreamToolCallFunction = {
  /**
   * Function arguments as JSON string
   */
  arguments?: string | undefined;
  /**
   * Function name
   */
  name?: string | undefined;
};

/**
 * Tool call type
 */
export const ChatStreamToolCallType = {
  Function: "function",
} as const;
/**
 * Tool call type
 */
export type ChatStreamToolCallType = ClosedEnum<typeof ChatStreamToolCallType>;

/**
 * Tool call delta for streaming responses
 */
export type ChatStreamToolCall = {
  /**
   * Function call details
   */
  function?: ChatStreamToolCallFunction | undefined;
  /**
   * Tool call identifier
   */
  id?: string | undefined;
  /**
   * Tool call index in the array
   */
  index: number;
  /**
   * Tool call type
   */
  type?: ChatStreamToolCallType | undefined;
};

/** @internal */
export const ChatStreamToolCallFunction$inboundSchema: z.ZodType<
  ChatStreamToolCallFunction,
  unknown
> = z.object({
  arguments: z.string().optional(),
  name: z.string().optional(),
});

export function chatStreamToolCallFunctionFromJSON(
  jsonString: string,
): SafeParseResult<ChatStreamToolCallFunction, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChatStreamToolCallFunction$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatStreamToolCallFunction' from JSON`,
  );
}

/** @internal */
export const ChatStreamToolCallType$inboundSchema: z.ZodEnum<
  typeof ChatStreamToolCallType
> = z.enum(ChatStreamToolCallType);

/** @internal */
export const ChatStreamToolCall$inboundSchema: z.ZodType<
  ChatStreamToolCall,
  unknown
> = z.object({
  function: z.lazy(() => ChatStreamToolCallFunction$inboundSchema).optional(),
  id: z.string().optional(),
  index: z.int(),
  type: ChatStreamToolCallType$inboundSchema.optional(),
});

export function chatStreamToolCallFromJSON(
  jsonString: string,
): SafeParseResult<ChatStreamToolCall, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChatStreamToolCall$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatStreamToolCall' from JSON`,
  );
}
