/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 361f940e91e4
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  ChatStreamChoice,
  ChatStreamChoice$inboundSchema,
} from "./chatstreamchoice.js";
import { ChatUsage, ChatUsage$inboundSchema } from "./chatusage.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Error information
 */
export type ErrorT = {
  /**
   * Error code
   */
  code: number;
  /**
   * Error message
   */
  message: string;
};

export const ChatStreamChunkObject = {
  ChatCompletionChunk: "chat.completion.chunk",
} as const;
export type ChatStreamChunkObject = ClosedEnum<typeof ChatStreamChunkObject>;

/**
 * Streaming chat completion chunk
 */
export type ChatStreamChunk = {
  /**
   * List of streaming chunk choices
   */
  choices: Array<ChatStreamChoice>;
  /**
   * Unix timestamp of creation
   */
  created: number;
  /**
   * Error information
   */
  error?: ErrorT | undefined;
  /**
   * Unique chunk identifier
   */
  id: string;
  /**
   * Model used for completion
   */
  model: string;
  object: ChatStreamChunkObject;
  /**
   * The service tier used by the upstream provider for this request
   */
  serviceTier?: string | null | undefined;
  /**
   * System fingerprint
   */
  systemFingerprint?: string | undefined;
  /**
   * Token usage statistics
   */
  usage?: ChatUsage | undefined;
};

/** @internal */
export const ErrorT$inboundSchema: z.ZodType<ErrorT, unknown> = z.object({
  code: z.int(),
  message: z.string(),
});

export function errorFromJSON(
  jsonString: string,
): SafeParseResult<ErrorT, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ErrorT$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ErrorT' from JSON`,
  );
}

/** @internal */
export const ChatStreamChunkObject$inboundSchema: z.ZodEnum<
  typeof ChatStreamChunkObject
> = z.enum(ChatStreamChunkObject);

/** @internal */
export const ChatStreamChunk$inboundSchema: z.ZodType<
  ChatStreamChunk,
  unknown
> = z.object({
  choices: z.array(ChatStreamChoice$inboundSchema),
  created: z.int(),
  error: z.lazy(() => ErrorT$inboundSchema).optional(),
  id: z.string(),
  model: z.string(),
  object: ChatStreamChunkObject$inboundSchema,
  service_tier: z.nullable(z.string()).optional(),
  system_fingerprint: z.string().optional(),
  usage: ChatUsage$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "service_tier": "serviceTier",
    "system_fingerprint": "systemFingerprint",
  });
});

export function chatStreamChunkFromJSON(
  jsonString: string,
): SafeParseResult<ChatStreamChunk, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChatStreamChunk$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatStreamChunk' from JSON`,
  );
}
