/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 493e614d6c34
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { ClosedEnum, OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const MemoryLimit = {
  Oneg: "1g",
  Fourg: "4g",
  Sixteeng: "16g",
  SixtyFourg: "64g",
} as const;
export type MemoryLimit = OpenEnum<typeof MemoryLimit>;

export const ContainerType = {
  Auto: "auto",
} as const;
export type ContainerType = ClosedEnum<typeof ContainerType>;

export type ContainerAuto = {
  fileIds?: Array<string> | undefined;
  memoryLimit?: MemoryLimit | null | undefined;
  type: ContainerType;
};

export type Container = ContainerAuto | string;

/**
 * Code interpreter tool configuration
 */
export type CodeInterpreterServerTool = {
  container: ContainerAuto | string;
  type: "code_interpreter";
};

/** @internal */
export const MemoryLimit$inboundSchema: z.ZodType<MemoryLimit, unknown> =
  openEnums.inboundSchema(MemoryLimit);
/** @internal */
export const MemoryLimit$outboundSchema: z.ZodType<string, MemoryLimit> =
  openEnums.outboundSchema(MemoryLimit);

/** @internal */
export const ContainerType$inboundSchema: z.ZodEnum<typeof ContainerType> = z
  .enum(ContainerType);
/** @internal */
export const ContainerType$outboundSchema: z.ZodEnum<typeof ContainerType> =
  ContainerType$inboundSchema;

/** @internal */
export const ContainerAuto$inboundSchema: z.ZodType<ContainerAuto, unknown> = z
  .object({
    file_ids: z.array(z.string()).optional(),
    memory_limit: z.nullable(MemoryLimit$inboundSchema).optional(),
    type: ContainerType$inboundSchema,
  }).transform((v) => {
    return remap$(v, {
      "file_ids": "fileIds",
      "memory_limit": "memoryLimit",
    });
  });
/** @internal */
export type ContainerAuto$Outbound = {
  file_ids?: Array<string> | undefined;
  memory_limit?: string | null | undefined;
  type: string;
};

/** @internal */
export const ContainerAuto$outboundSchema: z.ZodType<
  ContainerAuto$Outbound,
  ContainerAuto
> = z.object({
  fileIds: z.array(z.string()).optional(),
  memoryLimit: z.nullable(MemoryLimit$outboundSchema).optional(),
  type: ContainerType$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    fileIds: "file_ids",
    memoryLimit: "memory_limit",
  });
});

export function containerAutoToJSON(containerAuto: ContainerAuto): string {
  return JSON.stringify(ContainerAuto$outboundSchema.parse(containerAuto));
}
export function containerAutoFromJSON(
  jsonString: string,
): SafeParseResult<ContainerAuto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ContainerAuto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ContainerAuto' from JSON`,
  );
}

/** @internal */
export const Container$inboundSchema: z.ZodType<Container, unknown> = z.union([
  z.lazy(() => ContainerAuto$inboundSchema),
  z.string(),
]);
/** @internal */
export type Container$Outbound = ContainerAuto$Outbound | string;

/** @internal */
export const Container$outboundSchema: z.ZodType<
  Container$Outbound,
  Container
> = z.union([z.lazy(() => ContainerAuto$outboundSchema), z.string()]);

export function containerToJSON(container: Container): string {
  return JSON.stringify(Container$outboundSchema.parse(container));
}
export function containerFromJSON(
  jsonString: string,
): SafeParseResult<Container, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Container$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Container' from JSON`,
  );
}

/** @internal */
export const CodeInterpreterServerTool$inboundSchema: z.ZodType<
  CodeInterpreterServerTool,
  unknown
> = z.object({
  container: z.union([z.lazy(() => ContainerAuto$inboundSchema), z.string()]),
  type: z.literal("code_interpreter"),
});
/** @internal */
export type CodeInterpreterServerTool$Outbound = {
  container: ContainerAuto$Outbound | string;
  type: "code_interpreter";
};

/** @internal */
export const CodeInterpreterServerTool$outboundSchema: z.ZodType<
  CodeInterpreterServerTool$Outbound,
  CodeInterpreterServerTool
> = z.object({
  container: z.union([z.lazy(() => ContainerAuto$outboundSchema), z.string()]),
  type: z.literal("code_interpreter"),
});

export function codeInterpreterServerToolToJSON(
  codeInterpreterServerTool: CodeInterpreterServerTool,
): string {
  return JSON.stringify(
    CodeInterpreterServerTool$outboundSchema.parse(codeInterpreterServerTool),
  );
}
export function codeInterpreterServerToolFromJSON(
  jsonString: string,
): SafeParseResult<CodeInterpreterServerTool, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CodeInterpreterServerTool$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CodeInterpreterServerTool' from JSON`,
  );
}
