/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: beca2c6f6a75
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const CompoundFilterType = {
  And: "and",
  Or: "or",
} as const;
export type CompoundFilterType = OpenEnum<typeof CompoundFilterType>;

/**
 * A compound filter that combines multiple comparison or compound filters
 */
export type CompoundFilter = {
  filters: Array<{ [k: string]: any | null }>;
  type: CompoundFilterType;
};

/** @internal */
export const CompoundFilterType$inboundSchema: z.ZodType<
  CompoundFilterType,
  unknown
> = openEnums.inboundSchema(CompoundFilterType);
/** @internal */
export const CompoundFilterType$outboundSchema: z.ZodType<
  string,
  CompoundFilterType
> = openEnums.outboundSchema(CompoundFilterType);

/** @internal */
export const CompoundFilter$inboundSchema: z.ZodType<CompoundFilter, unknown> =
  z.object({
    filters: z.array(z.record(z.string(), z.nullable(z.any()))),
    type: CompoundFilterType$inboundSchema,
  });
/** @internal */
export type CompoundFilter$Outbound = {
  filters: Array<{ [k: string]: any | null }>;
  type: string;
};

/** @internal */
export const CompoundFilter$outboundSchema: z.ZodType<
  CompoundFilter$Outbound,
  CompoundFilter
> = z.object({
  filters: z.array(z.record(z.string(), z.nullable(z.any()))),
  type: CompoundFilterType$outboundSchema,
});

export function compoundFilterToJSON(compoundFilter: CompoundFilter): string {
  return JSON.stringify(CompoundFilter$outboundSchema.parse(compoundFilter));
}
export function compoundFilterFromJSON(
  jsonString: string,
): SafeParseResult<CompoundFilter, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CompoundFilter$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CompoundFilter' from JSON`,
  );
}
