/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 6b4d72ed5ae8
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";

export type ContentPartImageImageUrl = {
  url: string;
};

export const ContentPartImageType = {
  ImageUrl: "image_url",
} as const;
export type ContentPartImageType = ClosedEnum<typeof ContentPartImageType>;

export type ContentPartImage = {
  imageUrl: ContentPartImageImageUrl;
  type: ContentPartImageType;
};

/** @internal */
export type ContentPartImageImageUrl$Outbound = {
  url: string;
};

/** @internal */
export const ContentPartImageImageUrl$outboundSchema: z.ZodType<
  ContentPartImageImageUrl$Outbound,
  ContentPartImageImageUrl
> = z.object({
  url: z.string(),
});

export function contentPartImageImageUrlToJSON(
  contentPartImageImageUrl: ContentPartImageImageUrl,
): string {
  return JSON.stringify(
    ContentPartImageImageUrl$outboundSchema.parse(contentPartImageImageUrl),
  );
}

/** @internal */
export const ContentPartImageType$outboundSchema: z.ZodEnum<
  typeof ContentPartImageType
> = z.enum(ContentPartImageType);

/** @internal */
export type ContentPartImage$Outbound = {
  image_url: ContentPartImageImageUrl$Outbound;
  type: string;
};

/** @internal */
export const ContentPartImage$outboundSchema: z.ZodType<
  ContentPartImage$Outbound,
  ContentPartImage
> = z.object({
  imageUrl: z.lazy(() => ContentPartImageImageUrl$outboundSchema),
  type: ContentPartImageType$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    imageUrl: "image_url",
  });
});

export function contentPartImageToJSON(
  contentPartImage: ContentPartImage,
): string {
  return JSON.stringify(
    ContentPartImage$outboundSchema.parse(contentPartImage),
  );
}
