/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e3e073b472a1
 */

import * as z from "zod/v4";
import {
  ContextCompressionEngine,
  ContextCompressionEngine$outboundSchema,
} from "./contextcompressionengine.js";

export type ContextCompressionPlugin = {
  /**
   * Set to false to disable the context-compression plugin for this request. Defaults to true.
   */
  enabled?: boolean | undefined;
  /**
   * The compression engine to use. Defaults to "middle-out".
   */
  engine?: ContextCompressionEngine | undefined;
  id: "context-compression";
};

/** @internal */
export type ContextCompressionPlugin$Outbound = {
  enabled?: boolean | undefined;
  engine?: string | undefined;
  id: "context-compression";
};

/** @internal */
export const ContextCompressionPlugin$outboundSchema: z.ZodType<
  ContextCompressionPlugin$Outbound,
  ContextCompressionPlugin
> = z.object({
  enabled: z.boolean().optional(),
  engine: ContextCompressionEngine$outboundSchema.optional(),
  id: z.literal("context-compression"),
});

export function contextCompressionPluginToJSON(
  contextCompressionPlugin: ContextCompressionPlugin,
): string {
  return JSON.stringify(
    ContextCompressionPlugin$outboundSchema.parse(contextCompressionPlugin),
  );
}
