/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 943cfab7678a
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as discriminatedUnionTypes from "../types/discriminatedUnion.js";
import { discriminatedUnion } from "../types/discriminatedUnion.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  OpenAIResponsesRefusalContent,
  OpenAIResponsesRefusalContent$inboundSchema,
} from "./openairesponsesrefusalcontent.js";
import {
  ReasoningTextContent,
  ReasoningTextContent$inboundSchema,
} from "./reasoningtextcontent.js";
import {
  ResponseOutputText,
  ResponseOutputText$inboundSchema,
} from "./responseoutputtext.js";

export type ContentPartDoneEventPart =
  | ResponseOutputText
  | (ReasoningTextContent & { type: "reasoning_text" })
  | OpenAIResponsesRefusalContent
  | discriminatedUnionTypes.Unknown<"type">;

/**
 * Event emitted when a content part is complete
 */
export type ContentPartDoneEvent = {
  contentIndex: number;
  itemId: string;
  outputIndex: number;
  part:
    | ResponseOutputText
    | (ReasoningTextContent & { type: "reasoning_text" })
    | OpenAIResponsesRefusalContent
    | discriminatedUnionTypes.Unknown<"type">;
  sequenceNumber: number;
  type: "response.content_part.done";
};

/** @internal */
export const ContentPartDoneEventPart$inboundSchema: z.ZodType<
  ContentPartDoneEventPart,
  unknown
> = discriminatedUnion("type", {
  output_text: ResponseOutputText$inboundSchema,
  reasoning_text: ReasoningTextContent$inboundSchema.and(
    z.object({ type: z.literal("reasoning_text") }),
  ),
  refusal: OpenAIResponsesRefusalContent$inboundSchema,
});

export function contentPartDoneEventPartFromJSON(
  jsonString: string,
): SafeParseResult<ContentPartDoneEventPart, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ContentPartDoneEventPart$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ContentPartDoneEventPart' from JSON`,
  );
}

/** @internal */
export const ContentPartDoneEvent$inboundSchema: z.ZodType<
  ContentPartDoneEvent,
  unknown
> = z.object({
  content_index: z.int(),
  item_id: z.string(),
  output_index: z.int(),
  part: discriminatedUnion("type", {
    output_text: ResponseOutputText$inboundSchema,
    reasoning_text: ReasoningTextContent$inboundSchema.and(
      z.object({ type: z.literal("reasoning_text") }),
    ),
    refusal: OpenAIResponsesRefusalContent$inboundSchema,
  }),
  sequence_number: z.int(),
  type: z.literal("response.content_part.done"),
}).transform((v) => {
  return remap$(v, {
    "content_index": "contentIndex",
    "item_id": "itemId",
    "output_index": "outputIndex",
    "sequence_number": "sequenceNumber",
  });
});

export function contentPartDoneEventFromJSON(
  jsonString: string,
): SafeParseResult<ContentPartDoneEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ContentPartDoneEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ContentPartDoneEvent' from JSON`,
  );
}
