/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: fbf07f1435fd
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import {
  GuardrailInterval,
  GuardrailInterval$outboundSchema,
} from "./guardrailinterval.js";

export type CreateGuardrailRequest = {
  /**
   * Array of model identifiers (slug or canonical_slug accepted)
   */
  allowedModels?: Array<string> | null | undefined;
  /**
   * List of allowed provider IDs
   */
  allowedProviders?: Array<string> | null | undefined;
  /**
   * Description of the guardrail
   */
  description?: string | null | undefined;
  /**
   * Whether to enforce zero data retention
   */
  enforceZdr?: boolean | null | undefined;
  /**
   * List of provider IDs to exclude from routing
   */
  ignoredProviders?: Array<string> | null | undefined;
  /**
   * Spending limit in USD
   */
  limitUsd?: number | undefined;
  /**
   * Name for the new guardrail
   */
  name: string;
  /**
   * Interval at which the limit resets (daily, weekly, monthly)
   */
  resetInterval?: GuardrailInterval | null | undefined;
};

/** @internal */
export type CreateGuardrailRequest$Outbound = {
  allowed_models?: Array<string> | null | undefined;
  allowed_providers?: Array<string> | null | undefined;
  description?: string | null | undefined;
  enforce_zdr?: boolean | null | undefined;
  ignored_providers?: Array<string> | null | undefined;
  limit_usd?: number | undefined;
  name: string;
  reset_interval?: string | null | undefined;
};

/** @internal */
export const CreateGuardrailRequest$outboundSchema: z.ZodType<
  CreateGuardrailRequest$Outbound,
  CreateGuardrailRequest
> = z.object({
  allowedModels: z.nullable(z.array(z.string())).optional(),
  allowedProviders: z.nullable(z.array(z.string())).optional(),
  description: z.nullable(z.string()).optional(),
  enforceZdr: z.nullable(z.boolean()).optional(),
  ignoredProviders: z.nullable(z.array(z.string())).optional(),
  limitUsd: z.number().optional(),
  name: z.string(),
  resetInterval: z.nullable(GuardrailInterval$outboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    allowedModels: "allowed_models",
    allowedProviders: "allowed_providers",
    enforceZdr: "enforce_zdr",
    ignoredProviders: "ignored_providers",
    limitUsd: "limit_usd",
    resetInterval: "reset_interval",
  });
});

export function createGuardrailRequestToJSON(
  createGuardrailRequest: CreateGuardrailRequest,
): string {
  return JSON.stringify(
    CreateGuardrailRequest$outboundSchema.parse(createGuardrailRequest),
  );
}
