/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: b293ddf87321
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import * as discriminatedUnionTypes from "../types/discriminatedUnion.js";
import { discriminatedUnion } from "../types/discriminatedUnion.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const Syntax = {
  Lark: "lark",
  Regex: "regex",
} as const;
export type Syntax = OpenEnum<typeof Syntax>;

export type FormatGrammar = {
  definition: string;
  syntax: Syntax;
  type: "grammar";
};

export type FormatText = {
  type: "text";
};

export type Format =
  | FormatText
  | FormatGrammar
  | discriminatedUnionTypes.Unknown<"type">;

/**
 * Custom tool configuration
 */
export type CustomTool = {
  description?: string | undefined;
  format?:
    | FormatText
    | FormatGrammar
    | discriminatedUnionTypes.Unknown<"type">
    | undefined;
  name: string;
  type: "custom";
};

/** @internal */
export const Syntax$inboundSchema: z.ZodType<Syntax, unknown> = openEnums
  .inboundSchema(Syntax);
/** @internal */
export const Syntax$outboundSchema: z.ZodType<string, Syntax> = openEnums
  .outboundSchema(Syntax);

/** @internal */
export const FormatGrammar$inboundSchema: z.ZodType<FormatGrammar, unknown> = z
  .object({
    definition: z.string(),
    syntax: Syntax$inboundSchema,
    type: z.literal("grammar"),
  });
/** @internal */
export type FormatGrammar$Outbound = {
  definition: string;
  syntax: string;
  type: "grammar";
};

/** @internal */
export const FormatGrammar$outboundSchema: z.ZodType<
  FormatGrammar$Outbound,
  FormatGrammar
> = z.object({
  definition: z.string(),
  syntax: Syntax$outboundSchema,
  type: z.literal("grammar"),
});

export function formatGrammarToJSON(formatGrammar: FormatGrammar): string {
  return JSON.stringify(FormatGrammar$outboundSchema.parse(formatGrammar));
}
export function formatGrammarFromJSON(
  jsonString: string,
): SafeParseResult<FormatGrammar, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FormatGrammar$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FormatGrammar' from JSON`,
  );
}

/** @internal */
export const FormatText$inboundSchema: z.ZodType<FormatText, unknown> = z
  .object({
    type: z.literal("text"),
  });
/** @internal */
export type FormatText$Outbound = {
  type: "text";
};

/** @internal */
export const FormatText$outboundSchema: z.ZodType<
  FormatText$Outbound,
  FormatText
> = z.object({
  type: z.literal("text"),
});

export function formatTextToJSON(formatText: FormatText): string {
  return JSON.stringify(FormatText$outboundSchema.parse(formatText));
}
export function formatTextFromJSON(
  jsonString: string,
): SafeParseResult<FormatText, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FormatText$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FormatText' from JSON`,
  );
}

/** @internal */
export const Format$inboundSchema: z.ZodType<Format, unknown> =
  discriminatedUnion("type", {
    text: z.lazy(() => FormatText$inboundSchema),
    grammar: z.lazy(() => FormatGrammar$inboundSchema),
  });
/** @internal */
export type Format$Outbound = FormatText$Outbound | FormatGrammar$Outbound;

/** @internal */
export const Format$outboundSchema: z.ZodType<Format$Outbound, Format> = z
  .union([
    z.lazy(() => FormatText$outboundSchema),
    z.lazy(() => FormatGrammar$outboundSchema),
  ]);

export function formatToJSON(format: Format): string {
  return JSON.stringify(Format$outboundSchema.parse(format));
}
export function formatFromJSON(
  jsonString: string,
): SafeParseResult<Format, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Format$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Format' from JSON`,
  );
}

/** @internal */
export const CustomTool$inboundSchema: z.ZodType<CustomTool, unknown> = z
  .object({
    description: z.string().optional(),
    format: discriminatedUnion("type", {
      text: z.lazy(() => FormatText$inboundSchema),
      grammar: z.lazy(() => FormatGrammar$inboundSchema),
    }).optional(),
    name: z.string(),
    type: z.literal("custom"),
  });
/** @internal */
export type CustomTool$Outbound = {
  description?: string | undefined;
  format?: FormatText$Outbound | FormatGrammar$Outbound | undefined;
  name: string;
  type: "custom";
};

/** @internal */
export const CustomTool$outboundSchema: z.ZodType<
  CustomTool$Outbound,
  CustomTool
> = z.object({
  description: z.string().optional(),
  format: z.union([
    z.lazy(() => FormatText$outboundSchema),
    z.lazy(() => FormatGrammar$outboundSchema),
  ]).optional(),
  name: z.string(),
  type: z.literal("custom"),
});

export function customToolToJSON(customTool: CustomTool): string {
  return JSON.stringify(CustomTool$outboundSchema.parse(customTool));
}
export function customToolFromJSON(
  jsonString: string,
): SafeParseResult<CustomTool, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CustomTool$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CustomTool' from JSON`,
  );
}
