/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e4d8b08fcbb5
 */

import * as z from "zod/v4";
import { ClosedEnum } from "../types/enums.js";

export type DatetimeServerToolParameters = {
  /**
   * IANA timezone name (e.g. "America/New_York"). Defaults to UTC.
   */
  timezone?: string | undefined;
};

export const DatetimeServerToolType = {
  OpenrouterDatetime: "openrouter:datetime",
} as const;
export type DatetimeServerToolType = ClosedEnum<typeof DatetimeServerToolType>;

/**
 * OpenRouter built-in server tool: returns the current date and time
 */
export type DatetimeServerTool = {
  parameters?: DatetimeServerToolParameters | undefined;
  type: DatetimeServerToolType;
};

/** @internal */
export type DatetimeServerToolParameters$Outbound = {
  timezone?: string | undefined;
};

/** @internal */
export const DatetimeServerToolParameters$outboundSchema: z.ZodType<
  DatetimeServerToolParameters$Outbound,
  DatetimeServerToolParameters
> = z.object({
  timezone: z.string().optional(),
});

export function datetimeServerToolParametersToJSON(
  datetimeServerToolParameters: DatetimeServerToolParameters,
): string {
  return JSON.stringify(
    DatetimeServerToolParameters$outboundSchema.parse(
      datetimeServerToolParameters,
    ),
  );
}

/** @internal */
export const DatetimeServerToolType$outboundSchema: z.ZodEnum<
  typeof DatetimeServerToolType
> = z.enum(DatetimeServerToolType);

/** @internal */
export type DatetimeServerTool$Outbound = {
  parameters?: DatetimeServerToolParameters$Outbound | undefined;
  type: string;
};

/** @internal */
export const DatetimeServerTool$outboundSchema: z.ZodType<
  DatetimeServerTool$Outbound,
  DatetimeServerTool
> = z.object({
  parameters: z.lazy(() => DatetimeServerToolParameters$outboundSchema)
    .optional(),
  type: DatetimeServerToolType$outboundSchema,
});

export function datetimeServerToolToJSON(
  datetimeServerTool: DatetimeServerTool,
): string {
  return JSON.stringify(
    DatetimeServerTool$outboundSchema.parse(datetimeServerTool),
  );
}
