/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 0e3bca037a2a
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import * as openEnums from "../types/enums.js";
import { ClosedEnum, OpenEnum } from "../types/enums.js";
import {
  InputAudio,
  InputAudio$Outbound,
  InputAudio$outboundSchema,
} from "./inputaudio.js";
import {
  InputFile,
  InputFile$Outbound,
  InputFile$outboundSchema,
} from "./inputfile.js";
import {
  InputText,
  InputText$Outbound,
  InputText$outboundSchema,
} from "./inputtext.js";
import {
  InputVideo,
  InputVideo$Outbound,
  InputVideo$outboundSchema,
} from "./inputvideo.js";

export const EasyInputMessageDetail = {
  Auto: "auto",
  High: "high",
  Low: "low",
} as const;
export type EasyInputMessageDetail = OpenEnum<typeof EasyInputMessageDetail>;

/**
 * Image input content item
 */
export type EasyInputMessageContentInputImage = {
  detail: EasyInputMessageDetail;
  imageUrl?: string | null | undefined;
  type: "input_image";
};

export type EasyInputMessageContentUnion1 =
  | InputText
  | EasyInputMessageContentInputImage
  | InputFile
  | InputAudio
  | InputVideo;

export type EasyInputMessageContentUnion2 =
  | Array<
    | InputText
    | EasyInputMessageContentInputImage
    | InputFile
    | InputAudio
    | InputVideo
  >
  | string
  | any;

export const EasyInputMessagePhaseFinalAnswer = {
  FinalAnswer: "final_answer",
} as const;
export type EasyInputMessagePhaseFinalAnswer = ClosedEnum<
  typeof EasyInputMessagePhaseFinalAnswer
>;

export const EasyInputMessagePhaseCommentary = {
  Commentary: "commentary",
} as const;
export type EasyInputMessagePhaseCommentary = ClosedEnum<
  typeof EasyInputMessagePhaseCommentary
>;

/**
 * The phase of an assistant message. Use `commentary` for an intermediate assistant message and `final_answer` for the final assistant message. For follow-up requests with models like `gpt-5.3-codex` and later, preserve and resend phase on all assistant messages. Omitting it can degrade performance. Not used for user messages.
 */
export type EasyInputMessagePhaseUnion =
  | EasyInputMessagePhaseCommentary
  | EasyInputMessagePhaseFinalAnswer
  | any;

export const EasyInputMessageRoleDeveloper = {
  Developer: "developer",
} as const;
export type EasyInputMessageRoleDeveloper = ClosedEnum<
  typeof EasyInputMessageRoleDeveloper
>;

export const EasyInputMessageRoleAssistant = {
  Assistant: "assistant",
} as const;
export type EasyInputMessageRoleAssistant = ClosedEnum<
  typeof EasyInputMessageRoleAssistant
>;

export const EasyInputMessageRoleSystem = {
  System: "system",
} as const;
export type EasyInputMessageRoleSystem = ClosedEnum<
  typeof EasyInputMessageRoleSystem
>;

export const EasyInputMessageRoleUser = {
  User: "user",
} as const;
export type EasyInputMessageRoleUser = ClosedEnum<
  typeof EasyInputMessageRoleUser
>;

export type EasyInputMessageRoleUnion =
  | EasyInputMessageRoleUser
  | EasyInputMessageRoleSystem
  | EasyInputMessageRoleAssistant
  | EasyInputMessageRoleDeveloper;

export const EasyInputMessageTypeMessage = {
  Message: "message",
} as const;
export type EasyInputMessageTypeMessage = ClosedEnum<
  typeof EasyInputMessageTypeMessage
>;

export type EasyInputMessage = {
  content?:
    | Array<
      | InputText
      | EasyInputMessageContentInputImage
      | InputFile
      | InputAudio
      | InputVideo
    >
    | string
    | any
    | null
    | undefined;
  /**
   * The phase of an assistant message. Use `commentary` for an intermediate assistant message and `final_answer` for the final assistant message. For follow-up requests with models like `gpt-5.3-codex` and later, preserve and resend phase on all assistant messages. Omitting it can degrade performance. Not used for user messages.
   */
  phase?:
    | EasyInputMessagePhaseCommentary
    | EasyInputMessagePhaseFinalAnswer
    | any
    | null
    | undefined;
  role:
    | EasyInputMessageRoleUser
    | EasyInputMessageRoleSystem
    | EasyInputMessageRoleAssistant
    | EasyInputMessageRoleDeveloper;
  type?: EasyInputMessageTypeMessage | undefined;
};

/** @internal */
export const EasyInputMessageDetail$outboundSchema: z.ZodType<
  string,
  EasyInputMessageDetail
> = openEnums.outboundSchema(EasyInputMessageDetail);

/** @internal */
export type EasyInputMessageContentInputImage$Outbound = {
  detail: string;
  image_url?: string | null | undefined;
  type: "input_image";
};

/** @internal */
export const EasyInputMessageContentInputImage$outboundSchema: z.ZodType<
  EasyInputMessageContentInputImage$Outbound,
  EasyInputMessageContentInputImage
> = z.object({
  detail: EasyInputMessageDetail$outboundSchema,
  imageUrl: z.nullable(z.string()).optional(),
  type: z.literal("input_image"),
}).transform((v) => {
  return remap$(v, {
    imageUrl: "image_url",
  });
});

export function easyInputMessageContentInputImageToJSON(
  easyInputMessageContentInputImage: EasyInputMessageContentInputImage,
): string {
  return JSON.stringify(
    EasyInputMessageContentInputImage$outboundSchema.parse(
      easyInputMessageContentInputImage,
    ),
  );
}

/** @internal */
export type EasyInputMessageContentUnion1$Outbound =
  | InputText$Outbound
  | EasyInputMessageContentInputImage$Outbound
  | InputFile$Outbound
  | InputAudio$Outbound
  | InputVideo$Outbound;

/** @internal */
export const EasyInputMessageContentUnion1$outboundSchema: z.ZodType<
  EasyInputMessageContentUnion1$Outbound,
  EasyInputMessageContentUnion1
> = z.union([
  InputText$outboundSchema,
  z.lazy(() => EasyInputMessageContentInputImage$outboundSchema),
  InputFile$outboundSchema,
  InputAudio$outboundSchema,
  InputVideo$outboundSchema,
]);

export function easyInputMessageContentUnion1ToJSON(
  easyInputMessageContentUnion1: EasyInputMessageContentUnion1,
): string {
  return JSON.stringify(
    EasyInputMessageContentUnion1$outboundSchema.parse(
      easyInputMessageContentUnion1,
    ),
  );
}

/** @internal */
export type EasyInputMessageContentUnion2$Outbound =
  | Array<
    | InputText$Outbound
    | EasyInputMessageContentInputImage$Outbound
    | InputFile$Outbound
    | InputAudio$Outbound
    | InputVideo$Outbound
  >
  | string
  | any;

/** @internal */
export const EasyInputMessageContentUnion2$outboundSchema: z.ZodType<
  EasyInputMessageContentUnion2$Outbound,
  EasyInputMessageContentUnion2
> = z.union([
  z.array(z.union([
    InputText$outboundSchema,
    z.lazy(() => EasyInputMessageContentInputImage$outboundSchema),
    InputFile$outboundSchema,
    InputAudio$outboundSchema,
    InputVideo$outboundSchema,
  ])),
  z.string(),
  z.any(),
]);

export function easyInputMessageContentUnion2ToJSON(
  easyInputMessageContentUnion2: EasyInputMessageContentUnion2,
): string {
  return JSON.stringify(
    EasyInputMessageContentUnion2$outboundSchema.parse(
      easyInputMessageContentUnion2,
    ),
  );
}

/** @internal */
export const EasyInputMessagePhaseFinalAnswer$outboundSchema: z.ZodEnum<
  typeof EasyInputMessagePhaseFinalAnswer
> = z.enum(EasyInputMessagePhaseFinalAnswer);

/** @internal */
export const EasyInputMessagePhaseCommentary$outboundSchema: z.ZodEnum<
  typeof EasyInputMessagePhaseCommentary
> = z.enum(EasyInputMessagePhaseCommentary);

/** @internal */
export type EasyInputMessagePhaseUnion$Outbound = string | string | any;

/** @internal */
export const EasyInputMessagePhaseUnion$outboundSchema: z.ZodType<
  EasyInputMessagePhaseUnion$Outbound,
  EasyInputMessagePhaseUnion
> = z.union([
  EasyInputMessagePhaseCommentary$outboundSchema,
  EasyInputMessagePhaseFinalAnswer$outboundSchema,
  z.any(),
]);

export function easyInputMessagePhaseUnionToJSON(
  easyInputMessagePhaseUnion: EasyInputMessagePhaseUnion,
): string {
  return JSON.stringify(
    EasyInputMessagePhaseUnion$outboundSchema.parse(easyInputMessagePhaseUnion),
  );
}

/** @internal */
export const EasyInputMessageRoleDeveloper$outboundSchema: z.ZodEnum<
  typeof EasyInputMessageRoleDeveloper
> = z.enum(EasyInputMessageRoleDeveloper);

/** @internal */
export const EasyInputMessageRoleAssistant$outboundSchema: z.ZodEnum<
  typeof EasyInputMessageRoleAssistant
> = z.enum(EasyInputMessageRoleAssistant);

/** @internal */
export const EasyInputMessageRoleSystem$outboundSchema: z.ZodEnum<
  typeof EasyInputMessageRoleSystem
> = z.enum(EasyInputMessageRoleSystem);

/** @internal */
export const EasyInputMessageRoleUser$outboundSchema: z.ZodEnum<
  typeof EasyInputMessageRoleUser
> = z.enum(EasyInputMessageRoleUser);

/** @internal */
export type EasyInputMessageRoleUnion$Outbound =
  | string
  | string
  | string
  | string;

/** @internal */
export const EasyInputMessageRoleUnion$outboundSchema: z.ZodType<
  EasyInputMessageRoleUnion$Outbound,
  EasyInputMessageRoleUnion
> = z.union([
  EasyInputMessageRoleUser$outboundSchema,
  EasyInputMessageRoleSystem$outboundSchema,
  EasyInputMessageRoleAssistant$outboundSchema,
  EasyInputMessageRoleDeveloper$outboundSchema,
]);

export function easyInputMessageRoleUnionToJSON(
  easyInputMessageRoleUnion: EasyInputMessageRoleUnion,
): string {
  return JSON.stringify(
    EasyInputMessageRoleUnion$outboundSchema.parse(easyInputMessageRoleUnion),
  );
}

/** @internal */
export const EasyInputMessageTypeMessage$outboundSchema: z.ZodEnum<
  typeof EasyInputMessageTypeMessage
> = z.enum(EasyInputMessageTypeMessage);

/** @internal */
export type EasyInputMessage$Outbound = {
  content?:
    | Array<
      | InputText$Outbound
      | EasyInputMessageContentInputImage$Outbound
      | InputFile$Outbound
      | InputAudio$Outbound
      | InputVideo$Outbound
    >
    | string
    | any
    | null
    | undefined;
  phase?: string | string | any | null | undefined;
  role: string | string | string | string;
  type?: string | undefined;
};

/** @internal */
export const EasyInputMessage$outboundSchema: z.ZodType<
  EasyInputMessage$Outbound,
  EasyInputMessage
> = z.object({
  content: z.nullable(
    z.union([
      z.array(z.union([
        InputText$outboundSchema,
        z.lazy(() => EasyInputMessageContentInputImage$outboundSchema),
        InputFile$outboundSchema,
        InputAudio$outboundSchema,
        InputVideo$outboundSchema,
      ])),
      z.string(),
      z.any(),
    ]),
  ).optional(),
  phase: z.nullable(
    z.union([
      EasyInputMessagePhaseCommentary$outboundSchema,
      EasyInputMessagePhaseFinalAnswer$outboundSchema,
      z.any(),
    ]),
  ).optional(),
  role: z.union([
    EasyInputMessageRoleUser$outboundSchema,
    EasyInputMessageRoleSystem$outboundSchema,
    EasyInputMessageRoleAssistant$outboundSchema,
    EasyInputMessageRoleDeveloper$outboundSchema,
  ]),
  type: EasyInputMessageTypeMessage$outboundSchema.optional(),
});

export function easyInputMessageToJSON(
  easyInputMessage: EasyInputMessage,
): string {
  return JSON.stringify(
    EasyInputMessage$outboundSchema.parse(easyInputMessage),
  );
}
