/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a4e22766585b
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Event emitted when an error occurs during streaming
 */
export type ErrorEvent = {
  code: string | null;
  message: string;
  param: string | null;
  sequenceNumber: number;
  type: "error";
};

/** @internal */
export const ErrorEvent$inboundSchema: z.ZodType<ErrorEvent, unknown> = z
  .object({
    code: z.nullable(z.string()),
    message: z.string(),
    param: z.nullable(z.string()),
    sequence_number: z.int(),
    type: z.literal("error"),
  }).transform((v) => {
    return remap$(v, {
      "sequence_number": "sequenceNumber",
    });
  });

export function errorEventFromJSON(
  jsonString: string,
): SafeParseResult<ErrorEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ErrorEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ErrorEvent' from JSON`,
  );
}
