/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 04e61b333ea7
 */

import * as z from "zod/v4";
import {
  PDFParserOptions,
  PDFParserOptions$Outbound,
  PDFParserOptions$outboundSchema,
} from "./pdfparseroptions.js";

export type FileParserPlugin = {
  /**
   * Set to false to disable the file-parser plugin for this request. Defaults to true.
   */
  enabled?: boolean | undefined;
  id: "file-parser";
  /**
   * Options for PDF parsing.
   */
  pdf?: PDFParserOptions | undefined;
};

/** @internal */
export type FileParserPlugin$Outbound = {
  enabled?: boolean | undefined;
  id: "file-parser";
  pdf?: PDFParserOptions$Outbound | undefined;
};

/** @internal */
export const FileParserPlugin$outboundSchema: z.ZodType<
  FileParserPlugin$Outbound,
  FileParserPlugin
> = z.object({
  enabled: z.boolean().optional(),
  id: z.literal("file-parser"),
  pdf: PDFParserOptions$outboundSchema.optional(),
});

export function fileParserPluginToJSON(
  fileParserPlugin: FileParserPlugin,
): string {
  return JSON.stringify(
    FileParserPlugin$outboundSchema.parse(fileParserPlugin),
  );
}
