/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 6e4608e1920c
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import * as discriminatedUnionTypes from "../types/discriminatedUnion.js";
import { discriminatedUnion } from "../types/discriminatedUnion.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  FormatJsonObjectConfig,
  FormatJsonObjectConfig$inboundSchema,
  FormatJsonObjectConfig$Outbound,
  FormatJsonObjectConfig$outboundSchema,
} from "./formatjsonobjectconfig.js";
import {
  FormatJsonSchemaConfig,
  FormatJsonSchemaConfig$inboundSchema,
  FormatJsonSchemaConfig$Outbound,
  FormatJsonSchemaConfig$outboundSchema,
} from "./formatjsonschemaconfig.js";
import {
  FormatTextConfig,
  FormatTextConfig$inboundSchema,
  FormatTextConfig$Outbound,
  FormatTextConfig$outboundSchema,
} from "./formattextconfig.js";

/**
 * Text response format configuration
 */
export type Formats =
  | FormatTextConfig
  | FormatJsonObjectConfig
  | FormatJsonSchemaConfig
  | discriminatedUnionTypes.Unknown<"type">;

/** @internal */
export const Formats$inboundSchema: z.ZodType<Formats, unknown> =
  discriminatedUnion("type", {
    text: FormatTextConfig$inboundSchema,
    json_object: FormatJsonObjectConfig$inboundSchema,
    json_schema: FormatJsonSchemaConfig$inboundSchema,
  });
/** @internal */
export type Formats$Outbound =
  | FormatTextConfig$Outbound
  | FormatJsonObjectConfig$Outbound
  | FormatJsonSchemaConfig$Outbound;

/** @internal */
export const Formats$outboundSchema: z.ZodType<Formats$Outbound, Formats> = z
  .union([
    FormatTextConfig$outboundSchema,
    FormatJsonObjectConfig$outboundSchema,
    FormatJsonSchemaConfig$outboundSchema,
  ]);

export function formatsToJSON(formats: Formats): string {
  return JSON.stringify(Formats$outboundSchema.parse(formats));
}
export function formatsFromJSON(
  jsonString: string,
): SafeParseResult<Formats, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Formats$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Formats' from JSON`,
  );
}
