/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: dbec4c78c132
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * JSON schema constrained response format
 */
export type FormatJsonSchemaConfig = {
  description?: string | undefined;
  name: string;
  schema: { [k: string]: any | null };
  strict?: boolean | null | undefined;
  type: "json_schema";
};

/** @internal */
export const FormatJsonSchemaConfig$inboundSchema: z.ZodType<
  FormatJsonSchemaConfig,
  unknown
> = z.object({
  description: z.string().optional(),
  name: z.string(),
  schema: z.record(z.string(), z.nullable(z.any())),
  strict: z.nullable(z.boolean()).optional(),
  type: z.literal("json_schema"),
});
/** @internal */
export type FormatJsonSchemaConfig$Outbound = {
  description?: string | undefined;
  name: string;
  schema: { [k: string]: any | null };
  strict?: boolean | null | undefined;
  type: "json_schema";
};

/** @internal */
export const FormatJsonSchemaConfig$outboundSchema: z.ZodType<
  FormatJsonSchemaConfig$Outbound,
  FormatJsonSchemaConfig
> = z.object({
  description: z.string().optional(),
  name: z.string(),
  schema: z.record(z.string(), z.nullable(z.any())),
  strict: z.nullable(z.boolean()).optional(),
  type: z.literal("json_schema"),
});

export function formatJsonSchemaConfigToJSON(
  formatJsonSchemaConfig: FormatJsonSchemaConfig,
): string {
  return JSON.stringify(
    FormatJsonSchemaConfig$outboundSchema.parse(formatJsonSchemaConfig),
  );
}
export function formatJsonSchemaConfigFromJSON(
  jsonString: string,
): SafeParseResult<FormatJsonSchemaConfig, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FormatJsonSchemaConfig$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FormatJsonSchemaConfig' from JSON`,
  );
}
