/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: b2142af551f4
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Event emitted when function call arguments streaming is complete
 */
export type FunctionCallArgsDoneEvent = {
  arguments: string;
  itemId: string;
  name: string;
  outputIndex: number;
  sequenceNumber: number;
  type: "response.function_call_arguments.done";
};

/** @internal */
export const FunctionCallArgsDoneEvent$inboundSchema: z.ZodType<
  FunctionCallArgsDoneEvent,
  unknown
> = z.object({
  arguments: z.string(),
  item_id: z.string(),
  name: z.string(),
  output_index: z.int(),
  sequence_number: z.int(),
  type: z.literal("response.function_call_arguments.done"),
}).transform((v) => {
  return remap$(v, {
    "item_id": "itemId",
    "output_index": "outputIndex",
    "sequence_number": "sequenceNumber",
  });
});

export function functionCallArgsDoneEventFromJSON(
  jsonString: string,
): SafeParseResult<FunctionCallArgsDoneEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FunctionCallArgsDoneEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FunctionCallArgsDoneEvent' from JSON`,
  );
}
