/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 3103b978871a
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { Guardrail, Guardrail$inboundSchema } from "./guardrail.js";

export type GetGuardrailResponse = {
  data: Guardrail;
};

/** @internal */
export const GetGuardrailResponse$inboundSchema: z.ZodType<
  GetGuardrailResponse,
  unknown
> = z.object({
  data: Guardrail$inboundSchema,
});

export function getGuardrailResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetGuardrailResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetGuardrailResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetGuardrailResponse' from JSON`,
  );
}
