/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a8a819c013c0
 */

import * as z from "zod/v4";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

/**
 * Interval at which the limit resets (daily, weekly, monthly)
 */
export const GuardrailInterval = {
  Daily: "daily",
  Weekly: "weekly",
  Monthly: "monthly",
} as const;
/**
 * Interval at which the limit resets (daily, weekly, monthly)
 */
export type GuardrailInterval = OpenEnum<typeof GuardrailInterval>;

/** @internal */
export const GuardrailInterval$inboundSchema: z.ZodType<
  GuardrailInterval,
  unknown
> = openEnums.inboundSchema(GuardrailInterval);
/** @internal */
export const GuardrailInterval$outboundSchema: z.ZodType<
  string,
  GuardrailInterval
> = openEnums.outboundSchema(GuardrailInterval);
