/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: db1f02788378
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Image generation call with partial image
 */
export type ImageGenCallPartialImageEvent = {
  itemId: string;
  outputIndex: number;
  partialImageB64: string;
  partialImageIndex: number;
  sequenceNumber: number;
  type: "response.image_generation_call.partial_image";
};

/** @internal */
export const ImageGenCallPartialImageEvent$inboundSchema: z.ZodType<
  ImageGenCallPartialImageEvent,
  unknown
> = z.object({
  item_id: z.string(),
  output_index: z.int(),
  partial_image_b64: z.string(),
  partial_image_index: z.int(),
  sequence_number: z.int(),
  type: z.literal("response.image_generation_call.partial_image"),
}).transform((v) => {
  return remap$(v, {
    "item_id": "itemId",
    "output_index": "outputIndex",
    "partial_image_b64": "partialImageB64",
    "partial_image_index": "partialImageIndex",
    "sequence_number": "sequenceNumber",
  });
});

export function imageGenCallPartialImageEventFromJSON(
  jsonString: string,
): SafeParseResult<ImageGenCallPartialImageEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ImageGenCallPartialImageEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ImageGenCallPartialImageEvent' from JSON`,
  );
}
