/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f9385ea6a417
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Image generation call in progress
 */
export type ImageGenCallInProgressEvent = {
  itemId: string;
  outputIndex: number;
  sequenceNumber: number;
  type: "response.image_generation_call.in_progress";
};

/** @internal */
export const ImageGenCallInProgressEvent$inboundSchema: z.ZodType<
  ImageGenCallInProgressEvent,
  unknown
> = z.object({
  item_id: z.string(),
  output_index: z.int(),
  sequence_number: z.int(),
  type: z.literal("response.image_generation_call.in_progress"),
}).transform((v) => {
  return remap$(v, {
    "item_id": "itemId",
    "output_index": "outputIndex",
    "sequence_number": "sequenceNumber",
  });
});

export function imageGenCallInProgressEventFromJSON(
  jsonString: string,
): SafeParseResult<ImageGenCallInProgressEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ImageGenCallInProgressEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ImageGenCallInProgressEvent' from JSON`,
  );
}
