/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 78f212025019
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import * as openEnums from "../types/enums.js";
import { ClosedEnum, OpenEnum } from "../types/enums.js";
import {
  InputAudio,
  InputAudio$Outbound,
  InputAudio$outboundSchema,
} from "./inputaudio.js";
import {
  InputFile,
  InputFile$Outbound,
  InputFile$outboundSchema,
} from "./inputfile.js";
import {
  InputText,
  InputText$Outbound,
  InputText$outboundSchema,
} from "./inputtext.js";
import {
  InputVideo,
  InputVideo$Outbound,
  InputVideo$outboundSchema,
} from "./inputvideo.js";

export const InputMessageItemDetail = {
  Auto: "auto",
  High: "high",
  Low: "low",
} as const;
export type InputMessageItemDetail = OpenEnum<typeof InputMessageItemDetail>;

/**
 * Image input content item
 */
export type InputMessageItemContentInputImage = {
  detail: InputMessageItemDetail;
  imageUrl?: string | null | undefined;
  type: "input_image";
};

export type InputMessageItemContentUnion =
  | InputText
  | InputMessageItemContentInputImage
  | InputFile
  | InputAudio
  | InputVideo;

export const InputMessageItemRoleDeveloper = {
  Developer: "developer",
} as const;
export type InputMessageItemRoleDeveloper = ClosedEnum<
  typeof InputMessageItemRoleDeveloper
>;

export const InputMessageItemRoleSystem = {
  System: "system",
} as const;
export type InputMessageItemRoleSystem = ClosedEnum<
  typeof InputMessageItemRoleSystem
>;

export const InputMessageItemRoleUser = {
  User: "user",
} as const;
export type InputMessageItemRoleUser = ClosedEnum<
  typeof InputMessageItemRoleUser
>;

export type InputMessageItemRoleUnion =
  | InputMessageItemRoleUser
  | InputMessageItemRoleSystem
  | InputMessageItemRoleDeveloper;

export const InputMessageItemTypeMessage = {
  Message: "message",
} as const;
export type InputMessageItemTypeMessage = ClosedEnum<
  typeof InputMessageItemTypeMessage
>;

export type InputMessageItem = {
  content?:
    | Array<
      | InputText
      | InputMessageItemContentInputImage
      | InputFile
      | InputAudio
      | InputVideo
    >
    | null
    | undefined;
  id?: string | undefined;
  role:
    | InputMessageItemRoleUser
    | InputMessageItemRoleSystem
    | InputMessageItemRoleDeveloper;
  type?: InputMessageItemTypeMessage | undefined;
};

/** @internal */
export const InputMessageItemDetail$outboundSchema: z.ZodType<
  string,
  InputMessageItemDetail
> = openEnums.outboundSchema(InputMessageItemDetail);

/** @internal */
export type InputMessageItemContentInputImage$Outbound = {
  detail: string;
  image_url?: string | null | undefined;
  type: "input_image";
};

/** @internal */
export const InputMessageItemContentInputImage$outboundSchema: z.ZodType<
  InputMessageItemContentInputImage$Outbound,
  InputMessageItemContentInputImage
> = z.object({
  detail: InputMessageItemDetail$outboundSchema,
  imageUrl: z.nullable(z.string()).optional(),
  type: z.literal("input_image"),
}).transform((v) => {
  return remap$(v, {
    imageUrl: "image_url",
  });
});

export function inputMessageItemContentInputImageToJSON(
  inputMessageItemContentInputImage: InputMessageItemContentInputImage,
): string {
  return JSON.stringify(
    InputMessageItemContentInputImage$outboundSchema.parse(
      inputMessageItemContentInputImage,
    ),
  );
}

/** @internal */
export type InputMessageItemContentUnion$Outbound =
  | InputText$Outbound
  | InputMessageItemContentInputImage$Outbound
  | InputFile$Outbound
  | InputAudio$Outbound
  | InputVideo$Outbound;

/** @internal */
export const InputMessageItemContentUnion$outboundSchema: z.ZodType<
  InputMessageItemContentUnion$Outbound,
  InputMessageItemContentUnion
> = z.union([
  InputText$outboundSchema,
  z.lazy(() => InputMessageItemContentInputImage$outboundSchema),
  InputFile$outboundSchema,
  InputAudio$outboundSchema,
  InputVideo$outboundSchema,
]);

export function inputMessageItemContentUnionToJSON(
  inputMessageItemContentUnion: InputMessageItemContentUnion,
): string {
  return JSON.stringify(
    InputMessageItemContentUnion$outboundSchema.parse(
      inputMessageItemContentUnion,
    ),
  );
}

/** @internal */
export const InputMessageItemRoleDeveloper$outboundSchema: z.ZodEnum<
  typeof InputMessageItemRoleDeveloper
> = z.enum(InputMessageItemRoleDeveloper);

/** @internal */
export const InputMessageItemRoleSystem$outboundSchema: z.ZodEnum<
  typeof InputMessageItemRoleSystem
> = z.enum(InputMessageItemRoleSystem);

/** @internal */
export const InputMessageItemRoleUser$outboundSchema: z.ZodEnum<
  typeof InputMessageItemRoleUser
> = z.enum(InputMessageItemRoleUser);

/** @internal */
export type InputMessageItemRoleUnion$Outbound = string | string | string;

/** @internal */
export const InputMessageItemRoleUnion$outboundSchema: z.ZodType<
  InputMessageItemRoleUnion$Outbound,
  InputMessageItemRoleUnion
> = z.union([
  InputMessageItemRoleUser$outboundSchema,
  InputMessageItemRoleSystem$outboundSchema,
  InputMessageItemRoleDeveloper$outboundSchema,
]);

export function inputMessageItemRoleUnionToJSON(
  inputMessageItemRoleUnion: InputMessageItemRoleUnion,
): string {
  return JSON.stringify(
    InputMessageItemRoleUnion$outboundSchema.parse(inputMessageItemRoleUnion),
  );
}

/** @internal */
export const InputMessageItemTypeMessage$outboundSchema: z.ZodEnum<
  typeof InputMessageItemTypeMessage
> = z.enum(InputMessageItemTypeMessage);

/** @internal */
export type InputMessageItem$Outbound = {
  content?:
    | Array<
      | InputText$Outbound
      | InputMessageItemContentInputImage$Outbound
      | InputFile$Outbound
      | InputAudio$Outbound
      | InputVideo$Outbound
    >
    | null
    | undefined;
  id?: string | undefined;
  role: string | string | string;
  type?: string | undefined;
};

/** @internal */
export const InputMessageItem$outboundSchema: z.ZodType<
  InputMessageItem$Outbound,
  InputMessageItem
> = z.object({
  content: z.nullable(
    z.array(z.union([
      InputText$outboundSchema,
      z.lazy(() => InputMessageItemContentInputImage$outboundSchema),
      InputFile$outboundSchema,
      InputAudio$outboundSchema,
      InputVideo$outboundSchema,
    ])),
  ).optional(),
  id: z.string().optional(),
  role: z.union([
    InputMessageItemRoleUser$outboundSchema,
    InputMessageItemRoleSystem$outboundSchema,
    InputMessageItemRoleDeveloper$outboundSchema,
  ]),
  type: InputMessageItemTypeMessage$outboundSchema.optional(),
});

export function inputMessageItemToJSON(
  inputMessageItem: InputMessageItem,
): string {
  return JSON.stringify(
    InputMessageItem$outboundSchema.parse(inputMessageItem),
  );
}
