/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 7a718177a217
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { ClosedEnum, OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const InputImageDetail = {
  Auto: "auto",
  High: "high",
  Low: "low",
} as const;
export type InputImageDetail = OpenEnum<typeof InputImageDetail>;

export const InputImageTypeEnum = {
  InputImage: "input_image",
} as const;
export type InputImageTypeEnum = ClosedEnum<typeof InputImageTypeEnum>;

/**
 * Image input content item
 */
export type InputImage = {
  detail: InputImageDetail;
  imageUrl?: string | null | undefined;
  type: InputImageTypeEnum;
};

/** @internal */
export const InputImageDetail$inboundSchema: z.ZodType<
  InputImageDetail,
  unknown
> = openEnums.inboundSchema(InputImageDetail);
/** @internal */
export const InputImageDetail$outboundSchema: z.ZodType<
  string,
  InputImageDetail
> = openEnums.outboundSchema(InputImageDetail);

/** @internal */
export const InputImageTypeEnum$inboundSchema: z.ZodEnum<
  typeof InputImageTypeEnum
> = z.enum(InputImageTypeEnum);
/** @internal */
export const InputImageTypeEnum$outboundSchema: z.ZodEnum<
  typeof InputImageTypeEnum
> = InputImageTypeEnum$inboundSchema;

/** @internal */
export const InputImage$inboundSchema: z.ZodType<InputImage, unknown> = z
  .object({
    detail: InputImageDetail$inboundSchema,
    image_url: z.nullable(z.string()).optional(),
    type: InputImageTypeEnum$inboundSchema,
  }).transform((v) => {
    return remap$(v, {
      "image_url": "imageUrl",
    });
  });
/** @internal */
export type InputImage$Outbound = {
  detail: string;
  image_url?: string | null | undefined;
  type: string;
};

/** @internal */
export const InputImage$outboundSchema: z.ZodType<
  InputImage$Outbound,
  InputImage
> = z.object({
  detail: InputImageDetail$outboundSchema,
  imageUrl: z.nullable(z.string()).optional(),
  type: InputImageTypeEnum$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    imageUrl: "image_url",
  });
});

export function inputImageToJSON(inputImage: InputImage): string {
  return JSON.stringify(InputImage$outboundSchema.parse(inputImage));
}
export function inputImageFromJSON(
  jsonString: string,
): SafeParseResult<InputImage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InputImage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InputImage' from JSON`,
  );
}
