/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 3aff2165a17d
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";
import {
  EasyInputMessage,
  EasyInputMessage$Outbound,
  EasyInputMessage$outboundSchema,
} from "./easyinputmessage.js";
import {
  FunctionCallItem,
  FunctionCallItem$Outbound,
  FunctionCallItem$outboundSchema,
} from "./functioncallitem.js";
import {
  FunctionCallOutputItem,
  FunctionCallOutputItem$Outbound,
  FunctionCallOutputItem$outboundSchema,
} from "./functioncalloutputitem.js";
import {
  InputMessageItem,
  InputMessageItem$Outbound,
  InputMessageItem$outboundSchema,
} from "./inputmessageitem.js";
import {
  OpenAIResponsesRefusalContent,
  OpenAIResponsesRefusalContent$Outbound,
  OpenAIResponsesRefusalContent$outboundSchema,
} from "./openairesponsesrefusalcontent.js";
import {
  OutputDatetimeItem,
  OutputDatetimeItem$Outbound,
  OutputDatetimeItem$outboundSchema,
} from "./outputdatetimeitem.js";
import {
  OutputFileSearchCallItem,
  OutputFileSearchCallItem$Outbound,
  OutputFileSearchCallItem$outboundSchema,
} from "./outputfilesearchcallitem.js";
import {
  OutputFunctionCallItem,
  OutputFunctionCallItem$Outbound,
  OutputFunctionCallItem$outboundSchema,
} from "./outputfunctioncallitem.js";
import {
  OutputImageGenerationCallItem,
  OutputImageGenerationCallItem$Outbound,
  OutputImageGenerationCallItem$outboundSchema,
} from "./outputimagegenerationcallitem.js";
import {
  OutputWebSearchCallItem,
  OutputWebSearchCallItem$Outbound,
  OutputWebSearchCallItem$outboundSchema,
} from "./outputwebsearchcallitem.js";
import {
  OutputWebSearchServerToolItem,
  OutputWebSearchServerToolItem$Outbound,
  OutputWebSearchServerToolItem$outboundSchema,
} from "./outputwebsearchservertoolitem.js";
import {
  ReasoningFormat,
  ReasoningFormat$outboundSchema,
} from "./reasoningformat.js";
import {
  ReasoningItem,
  ReasoningItem$Outbound,
  ReasoningItem$outboundSchema,
} from "./reasoningitem.js";
import {
  ReasoningSummaryText,
  ReasoningSummaryText$Outbound,
  ReasoningSummaryText$outboundSchema,
} from "./reasoningsummarytext.js";
import {
  ReasoningTextContent,
  ReasoningTextContent$Outbound,
  ReasoningTextContent$outboundSchema,
} from "./reasoningtextcontent.js";
import {
  ResponseOutputText,
  ResponseOutputText$Outbound,
  ResponseOutputText$outboundSchema,
} from "./responseoutputtext.js";

export const InputsStatusInProgress2 = {
  InProgress: "in_progress",
} as const;
export type InputsStatusInProgress2 = ClosedEnum<
  typeof InputsStatusInProgress2
>;

export const InputsStatusIncomplete2 = {
  Incomplete: "incomplete",
} as const;
export type InputsStatusIncomplete2 = ClosedEnum<
  typeof InputsStatusIncomplete2
>;

export const InputsStatusCompleted2 = {
  Completed: "completed",
} as const;
export type InputsStatusCompleted2 = ClosedEnum<typeof InputsStatusCompleted2>;

export type InputsStatusUnion2 =
  | InputsStatusCompleted2
  | InputsStatusIncomplete2
  | InputsStatusInProgress2;

export const InputsTypeReasoning = {
  Reasoning: "reasoning",
} as const;
export type InputsTypeReasoning = ClosedEnum<typeof InputsTypeReasoning>;

/**
 * An output item containing reasoning
 */
export type InputsReasoning = {
  content?: Array<ReasoningTextContent> | null | undefined;
  encryptedContent?: string | null | undefined;
  id: string;
  status?:
    | InputsStatusCompleted2
    | InputsStatusIncomplete2
    | InputsStatusInProgress2
    | undefined;
  summary: Array<ReasoningSummaryText> | null;
  type: InputsTypeReasoning;
  format?: ReasoningFormat | null | undefined;
  /**
   * A signature for the reasoning content, used for verification
   */
  signature?: string | null | undefined;
};

export type InputsContent1 = ResponseOutputText | OpenAIResponsesRefusalContent;

export type InputsContent2 =
  | Array<ResponseOutputText | OpenAIResponsesRefusalContent>
  | string
  | any;

export const InputsPhaseFinalAnswer = {
  FinalAnswer: "final_answer",
} as const;
export type InputsPhaseFinalAnswer = ClosedEnum<typeof InputsPhaseFinalAnswer>;

export const InputsPhaseCommentary = {
  Commentary: "commentary",
} as const;
export type InputsPhaseCommentary = ClosedEnum<typeof InputsPhaseCommentary>;

/**
 * The phase of an assistant message. Use `commentary` for an intermediate assistant message and `final_answer` for the final assistant message. For follow-up requests with models like `gpt-5.3-codex` and later, preserve and resend phase on all assistant messages. Omitting it can degrade performance. Not used for user messages.
 */
export type InputsPhaseUnion =
  | InputsPhaseCommentary
  | InputsPhaseFinalAnswer
  | any;

export const InputsRole = {
  Assistant: "assistant",
} as const;
export type InputsRole = ClosedEnum<typeof InputsRole>;

export const InputsStatusInProgress1 = {
  InProgress: "in_progress",
} as const;
export type InputsStatusInProgress1 = ClosedEnum<
  typeof InputsStatusInProgress1
>;

export const InputsStatusIncomplete1 = {
  Incomplete: "incomplete",
} as const;
export type InputsStatusIncomplete1 = ClosedEnum<
  typeof InputsStatusIncomplete1
>;

export const InputsStatusCompleted1 = {
  Completed: "completed",
} as const;
export type InputsStatusCompleted1 = ClosedEnum<typeof InputsStatusCompleted1>;

export type InputsStatusUnion1 =
  | InputsStatusCompleted1
  | InputsStatusIncomplete1
  | InputsStatusInProgress1;

export const InputsTypeMessage = {
  Message: "message",
} as const;
export type InputsTypeMessage = ClosedEnum<typeof InputsTypeMessage>;

/**
 * An output message item
 */
export type InputsMessage = {
  content:
    | Array<ResponseOutputText | OpenAIResponsesRefusalContent>
    | string
    | any
    | null;
  id: string;
  /**
   * The phase of an assistant message. Use `commentary` for an intermediate assistant message and `final_answer` for the final assistant message. For follow-up requests with models like `gpt-5.3-codex` and later, preserve and resend phase on all assistant messages. Omitting it can degrade performance. Not used for user messages.
   */
  phase?:
    | InputsPhaseCommentary
    | InputsPhaseFinalAnswer
    | any
    | null
    | undefined;
  role: InputsRole;
  status?:
    | InputsStatusCompleted1
    | InputsStatusIncomplete1
    | InputsStatusInProgress1
    | undefined;
  type: InputsTypeMessage;
};

export type InputsUnion1 =
  | FunctionCallItem
  | InputsMessage
  | OutputFunctionCallItem
  | OutputWebSearchCallItem
  | OutputFileSearchCallItem
  | OutputDatetimeItem
  | ReasoningItem
  | FunctionCallOutputItem
  | InputsReasoning
  | OutputImageGenerationCallItem
  | OutputWebSearchServerToolItem
  | EasyInputMessage
  | InputMessageItem;

/**
 * Input for a response request - can be a string or array of items
 */
export type InputsUnion =
  | string
  | Array<
    | FunctionCallItem
    | InputsMessage
    | OutputFunctionCallItem
    | OutputWebSearchCallItem
    | OutputFileSearchCallItem
    | OutputDatetimeItem
    | ReasoningItem
    | FunctionCallOutputItem
    | InputsReasoning
    | OutputImageGenerationCallItem
    | OutputWebSearchServerToolItem
    | EasyInputMessage
    | InputMessageItem
  >;

/** @internal */
export const InputsStatusInProgress2$outboundSchema: z.ZodEnum<
  typeof InputsStatusInProgress2
> = z.enum(InputsStatusInProgress2);

/** @internal */
export const InputsStatusIncomplete2$outboundSchema: z.ZodEnum<
  typeof InputsStatusIncomplete2
> = z.enum(InputsStatusIncomplete2);

/** @internal */
export const InputsStatusCompleted2$outboundSchema: z.ZodEnum<
  typeof InputsStatusCompleted2
> = z.enum(InputsStatusCompleted2);

/** @internal */
export type InputsStatusUnion2$Outbound = string | string | string;

/** @internal */
export const InputsStatusUnion2$outboundSchema: z.ZodType<
  InputsStatusUnion2$Outbound,
  InputsStatusUnion2
> = z.union([
  InputsStatusCompleted2$outboundSchema,
  InputsStatusIncomplete2$outboundSchema,
  InputsStatusInProgress2$outboundSchema,
]);

export function inputsStatusUnion2ToJSON(
  inputsStatusUnion2: InputsStatusUnion2,
): string {
  return JSON.stringify(
    InputsStatusUnion2$outboundSchema.parse(inputsStatusUnion2),
  );
}

/** @internal */
export const InputsTypeReasoning$outboundSchema: z.ZodEnum<
  typeof InputsTypeReasoning
> = z.enum(InputsTypeReasoning);

/** @internal */
export type InputsReasoning$Outbound = {
  content?: Array<ReasoningTextContent$Outbound> | null | undefined;
  encrypted_content?: string | null | undefined;
  id: string;
  status?: string | string | string | undefined;
  summary: Array<ReasoningSummaryText$Outbound> | null;
  type: string;
  format?: string | null | undefined;
  signature?: string | null | undefined;
};

/** @internal */
export const InputsReasoning$outboundSchema: z.ZodType<
  InputsReasoning$Outbound,
  InputsReasoning
> = z.object({
  content: z.nullable(z.array(ReasoningTextContent$outboundSchema)).optional(),
  encryptedContent: z.nullable(z.string()).optional(),
  id: z.string(),
  status: z.union([
    InputsStatusCompleted2$outboundSchema,
    InputsStatusIncomplete2$outboundSchema,
    InputsStatusInProgress2$outboundSchema,
  ]).optional(),
  summary: z.nullable(z.array(ReasoningSummaryText$outboundSchema)),
  type: InputsTypeReasoning$outboundSchema,
  format: z.nullable(ReasoningFormat$outboundSchema).optional(),
  signature: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    encryptedContent: "encrypted_content",
  });
});

export function inputsReasoningToJSON(
  inputsReasoning: InputsReasoning,
): string {
  return JSON.stringify(InputsReasoning$outboundSchema.parse(inputsReasoning));
}

/** @internal */
export type InputsContent1$Outbound =
  | ResponseOutputText$Outbound
  | OpenAIResponsesRefusalContent$Outbound;

/** @internal */
export const InputsContent1$outboundSchema: z.ZodType<
  InputsContent1$Outbound,
  InputsContent1
> = z.union([
  ResponseOutputText$outboundSchema,
  OpenAIResponsesRefusalContent$outboundSchema,
]);

export function inputsContent1ToJSON(inputsContent1: InputsContent1): string {
  return JSON.stringify(InputsContent1$outboundSchema.parse(inputsContent1));
}

/** @internal */
export type InputsContent2$Outbound =
  | Array<ResponseOutputText$Outbound | OpenAIResponsesRefusalContent$Outbound>
  | string
  | any;

/** @internal */
export const InputsContent2$outboundSchema: z.ZodType<
  InputsContent2$Outbound,
  InputsContent2
> = z.union([
  z.array(
    z.union([
      ResponseOutputText$outboundSchema,
      OpenAIResponsesRefusalContent$outboundSchema,
    ]),
  ),
  z.string(),
  z.any(),
]);

export function inputsContent2ToJSON(inputsContent2: InputsContent2): string {
  return JSON.stringify(InputsContent2$outboundSchema.parse(inputsContent2));
}

/** @internal */
export const InputsPhaseFinalAnswer$outboundSchema: z.ZodEnum<
  typeof InputsPhaseFinalAnswer
> = z.enum(InputsPhaseFinalAnswer);

/** @internal */
export const InputsPhaseCommentary$outboundSchema: z.ZodEnum<
  typeof InputsPhaseCommentary
> = z.enum(InputsPhaseCommentary);

/** @internal */
export type InputsPhaseUnion$Outbound = string | string | any;

/** @internal */
export const InputsPhaseUnion$outboundSchema: z.ZodType<
  InputsPhaseUnion$Outbound,
  InputsPhaseUnion
> = z.union([
  InputsPhaseCommentary$outboundSchema,
  InputsPhaseFinalAnswer$outboundSchema,
  z.any(),
]);

export function inputsPhaseUnionToJSON(
  inputsPhaseUnion: InputsPhaseUnion,
): string {
  return JSON.stringify(
    InputsPhaseUnion$outboundSchema.parse(inputsPhaseUnion),
  );
}

/** @internal */
export const InputsRole$outboundSchema: z.ZodEnum<typeof InputsRole> = z.enum(
  InputsRole,
);

/** @internal */
export const InputsStatusInProgress1$outboundSchema: z.ZodEnum<
  typeof InputsStatusInProgress1
> = z.enum(InputsStatusInProgress1);

/** @internal */
export const InputsStatusIncomplete1$outboundSchema: z.ZodEnum<
  typeof InputsStatusIncomplete1
> = z.enum(InputsStatusIncomplete1);

/** @internal */
export const InputsStatusCompleted1$outboundSchema: z.ZodEnum<
  typeof InputsStatusCompleted1
> = z.enum(InputsStatusCompleted1);

/** @internal */
export type InputsStatusUnion1$Outbound = string | string | string;

/** @internal */
export const InputsStatusUnion1$outboundSchema: z.ZodType<
  InputsStatusUnion1$Outbound,
  InputsStatusUnion1
> = z.union([
  InputsStatusCompleted1$outboundSchema,
  InputsStatusIncomplete1$outboundSchema,
  InputsStatusInProgress1$outboundSchema,
]);

export function inputsStatusUnion1ToJSON(
  inputsStatusUnion1: InputsStatusUnion1,
): string {
  return JSON.stringify(
    InputsStatusUnion1$outboundSchema.parse(inputsStatusUnion1),
  );
}

/** @internal */
export const InputsTypeMessage$outboundSchema: z.ZodEnum<
  typeof InputsTypeMessage
> = z.enum(InputsTypeMessage);

/** @internal */
export type InputsMessage$Outbound = {
  content:
    | Array<
      ResponseOutputText$Outbound | OpenAIResponsesRefusalContent$Outbound
    >
    | string
    | any
    | null;
  id: string;
  phase?: string | string | any | null | undefined;
  role: string;
  status?: string | string | string | undefined;
  type: string;
};

/** @internal */
export const InputsMessage$outboundSchema: z.ZodType<
  InputsMessage$Outbound,
  InputsMessage
> = z.object({
  content: z.nullable(
    z.union([
      z.array(
        z.union([
          ResponseOutputText$outboundSchema,
          OpenAIResponsesRefusalContent$outboundSchema,
        ]),
      ),
      z.string(),
      z.any(),
    ]),
  ),
  id: z.string(),
  phase: z.nullable(
    z.union([
      InputsPhaseCommentary$outboundSchema,
      InputsPhaseFinalAnswer$outboundSchema,
      z.any(),
    ]),
  ).optional(),
  role: InputsRole$outboundSchema,
  status: z.union([
    InputsStatusCompleted1$outboundSchema,
    InputsStatusIncomplete1$outboundSchema,
    InputsStatusInProgress1$outboundSchema,
  ]).optional(),
  type: InputsTypeMessage$outboundSchema,
});

export function inputsMessageToJSON(inputsMessage: InputsMessage): string {
  return JSON.stringify(InputsMessage$outboundSchema.parse(inputsMessage));
}

/** @internal */
export type InputsUnion1$Outbound =
  | FunctionCallItem$Outbound
  | InputsMessage$Outbound
  | OutputFunctionCallItem$Outbound
  | OutputWebSearchCallItem$Outbound
  | OutputFileSearchCallItem$Outbound
  | OutputDatetimeItem$Outbound
  | ReasoningItem$Outbound
  | FunctionCallOutputItem$Outbound
  | InputsReasoning$Outbound
  | OutputImageGenerationCallItem$Outbound
  | OutputWebSearchServerToolItem$Outbound
  | EasyInputMessage$Outbound
  | InputMessageItem$Outbound;

/** @internal */
export const InputsUnion1$outboundSchema: z.ZodType<
  InputsUnion1$Outbound,
  InputsUnion1
> = z.union([
  FunctionCallItem$outboundSchema,
  z.lazy(() => InputsMessage$outboundSchema),
  OutputFunctionCallItem$outboundSchema,
  OutputWebSearchCallItem$outboundSchema,
  OutputFileSearchCallItem$outboundSchema,
  OutputDatetimeItem$outboundSchema,
  ReasoningItem$outboundSchema,
  FunctionCallOutputItem$outboundSchema,
  z.lazy(() => InputsReasoning$outboundSchema),
  OutputImageGenerationCallItem$outboundSchema,
  OutputWebSearchServerToolItem$outboundSchema,
  EasyInputMessage$outboundSchema,
  InputMessageItem$outboundSchema,
]);

export function inputsUnion1ToJSON(inputsUnion1: InputsUnion1): string {
  return JSON.stringify(InputsUnion1$outboundSchema.parse(inputsUnion1));
}

/** @internal */
export type InputsUnion$Outbound =
  | string
  | Array<
    | FunctionCallItem$Outbound
    | InputsMessage$Outbound
    | OutputFunctionCallItem$Outbound
    | OutputWebSearchCallItem$Outbound
    | OutputFileSearchCallItem$Outbound
    | OutputDatetimeItem$Outbound
    | ReasoningItem$Outbound
    | FunctionCallOutputItem$Outbound
    | InputsReasoning$Outbound
    | OutputImageGenerationCallItem$Outbound
    | OutputWebSearchServerToolItem$Outbound
    | EasyInputMessage$Outbound
    | InputMessageItem$Outbound
  >;

/** @internal */
export const InputsUnion$outboundSchema: z.ZodType<
  InputsUnion$Outbound,
  InputsUnion
> = z.union([
  z.string(),
  z.array(z.union([
    FunctionCallItem$outboundSchema,
    z.lazy(() => InputsMessage$outboundSchema),
    OutputFunctionCallItem$outboundSchema,
    OutputWebSearchCallItem$outboundSchema,
    OutputFileSearchCallItem$outboundSchema,
    OutputDatetimeItem$outboundSchema,
    ReasoningItem$outboundSchema,
    FunctionCallOutputItem$outboundSchema,
    z.lazy(() => InputsReasoning$outboundSchema),
    OutputImageGenerationCallItem$outboundSchema,
    OutputWebSearchServerToolItem$outboundSchema,
    EasyInputMessage$outboundSchema,
    InputMessageItem$outboundSchema,
  ])),
]);

export function inputsUnionToJSON(inputsUnion: InputsUnion): string {
  return JSON.stringify(InputsUnion$outboundSchema.parse(inputsUnion));
}
