/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 9bdc14c7565f
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const FormatEnum = {
  Mp3: "mp3",
  Wav: "wav",
} as const;
export type FormatEnum = OpenEnum<typeof FormatEnum>;

export type InputAudioInputAudio = {
  data: string;
  format: FormatEnum;
};

/**
 * Audio input content item
 */
export type InputAudio = {
  inputAudio: InputAudioInputAudio;
  type: "input_audio";
};

/** @internal */
export const FormatEnum$inboundSchema: z.ZodType<FormatEnum, unknown> =
  openEnums.inboundSchema(FormatEnum);
/** @internal */
export const FormatEnum$outboundSchema: z.ZodType<string, FormatEnum> =
  openEnums.outboundSchema(FormatEnum);

/** @internal */
export const InputAudioInputAudio$inboundSchema: z.ZodType<
  InputAudioInputAudio,
  unknown
> = z.object({
  data: z.string(),
  format: FormatEnum$inboundSchema,
});
/** @internal */
export type InputAudioInputAudio$Outbound = {
  data: string;
  format: string;
};

/** @internal */
export const InputAudioInputAudio$outboundSchema: z.ZodType<
  InputAudioInputAudio$Outbound,
  InputAudioInputAudio
> = z.object({
  data: z.string(),
  format: FormatEnum$outboundSchema,
});

export function inputAudioInputAudioToJSON(
  inputAudioInputAudio: InputAudioInputAudio,
): string {
  return JSON.stringify(
    InputAudioInputAudio$outboundSchema.parse(inputAudioInputAudio),
  );
}
export function inputAudioInputAudioFromJSON(
  jsonString: string,
): SafeParseResult<InputAudioInputAudio, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InputAudioInputAudio$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InputAudioInputAudio' from JSON`,
  );
}

/** @internal */
export const InputAudio$inboundSchema: z.ZodType<InputAudio, unknown> = z
  .object({
    input_audio: z.lazy(() => InputAudioInputAudio$inboundSchema),
    type: z.literal("input_audio"),
  }).transform((v) => {
    return remap$(v, {
      "input_audio": "inputAudio",
    });
  });
/** @internal */
export type InputAudio$Outbound = {
  input_audio: InputAudioInputAudio$Outbound;
  type: "input_audio";
};

/** @internal */
export const InputAudio$outboundSchema: z.ZodType<
  InputAudio$Outbound,
  InputAudio
> = z.object({
  inputAudio: z.lazy(() => InputAudioInputAudio$outboundSchema),
  type: z.literal("input_audio"),
}).transform((v) => {
  return remap$(v, {
    inputAudio: "input_audio",
  });
});

export function inputAudioToJSON(inputAudio: InputAudio): string {
  return JSON.stringify(InputAudio$outboundSchema.parse(inputAudio));
}
export function inputAudioFromJSON(
  jsonString: string,
): SafeParseResult<InputAudio, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InputAudio$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InputAudio' from JSON`,
  );
}
