/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 21319fb604ac
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * File input content item
 */
export type InputFile = {
  fileData?: string | undefined;
  fileId?: string | null | undefined;
  fileUrl?: string | undefined;
  filename?: string | undefined;
  type: "input_file";
};

/** @internal */
export const InputFile$inboundSchema: z.ZodType<InputFile, unknown> = z.object({
  file_data: z.string().optional(),
  file_id: z.nullable(z.string()).optional(),
  file_url: z.string().optional(),
  filename: z.string().optional(),
  type: z.literal("input_file"),
}).transform((v) => {
  return remap$(v, {
    "file_data": "fileData",
    "file_id": "fileId",
    "file_url": "fileUrl",
  });
});
/** @internal */
export type InputFile$Outbound = {
  file_data?: string | undefined;
  file_id?: string | null | undefined;
  file_url?: string | undefined;
  filename?: string | undefined;
  type: "input_file";
};

/** @internal */
export const InputFile$outboundSchema: z.ZodType<
  InputFile$Outbound,
  InputFile
> = z.object({
  fileData: z.string().optional(),
  fileId: z.nullable(z.string()).optional(),
  fileUrl: z.string().optional(),
  filename: z.string().optional(),
  type: z.literal("input_file"),
}).transform((v) => {
  return remap$(v, {
    fileData: "file_data",
    fileId: "file_id",
    fileUrl: "file_url",
  });
});

export function inputFileToJSON(inputFile: InputFile): string {
  return JSON.stringify(InputFile$outboundSchema.parse(inputFile));
}
export function inputFileFromJSON(
  jsonString: string,
): SafeParseResult<InputFile, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InputFile$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InputFile' from JSON`,
  );
}
