/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: bbd89d5e9f3f
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  MemberAssignment,
  MemberAssignment$inboundSchema,
} from "./memberassignment.js";

export type ListMemberAssignmentsResponse = {
  /**
   * List of member assignments
   */
  data: Array<MemberAssignment>;
  /**
   * Total number of member assignments
   */
  totalCount: number;
};

/** @internal */
export const ListMemberAssignmentsResponse$inboundSchema: z.ZodType<
  ListMemberAssignmentsResponse,
  unknown
> = z.object({
  data: z.array(MemberAssignment$inboundSchema),
  total_count: z.int(),
}).transform((v) => {
  return remap$(v, {
    "total_count": "totalCount",
  });
});

export function listMemberAssignmentsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListMemberAssignmentsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListMemberAssignmentsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListMemberAssignmentsResponse' from JSON`,
  );
}
