/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 281c3f73d27b
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { Guardrail, Guardrail$inboundSchema } from "./guardrail.js";

export type ListGuardrailsResponse = {
  /**
   * List of guardrails
   */
  data: Array<Guardrail>;
  /**
   * Total number of guardrails
   */
  totalCount: number;
};

/** @internal */
export const ListGuardrailsResponse$inboundSchema: z.ZodType<
  ListGuardrailsResponse,
  unknown
> = z.object({
  data: z.array(Guardrail$inboundSchema),
  total_count: z.int(),
}).transform((v) => {
  return remap$(v, {
    "total_count": "totalCount",
  });
});

export function listGuardrailsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListGuardrailsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListGuardrailsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListGuardrailsResponse' from JSON`,
  );
}
