/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 6c14372c6290
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { KeyAssignment, KeyAssignment$inboundSchema } from "./keyassignment.js";

export type ListKeyAssignmentsResponse = {
  /**
   * List of key assignments
   */
  data: Array<KeyAssignment>;
  /**
   * Total number of key assignments for this guardrail
   */
  totalCount: number;
};

/** @internal */
export const ListKeyAssignmentsResponse$inboundSchema: z.ZodType<
  ListKeyAssignmentsResponse,
  unknown
> = z.object({
  data: z.array(KeyAssignment$inboundSchema),
  total_count: z.int(),
}).transform((v) => {
  return remap$(v, {
    "total_count": "totalCount",
  });
});

export function listKeyAssignmentsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListKeyAssignmentsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListKeyAssignmentsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListKeyAssignmentsResponse' from JSON`,
  );
}
