/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 5178e92a44ba
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { InputModality, InputModality$inboundSchema } from "./inputmodality.js";
import { InstructType, InstructType$inboundSchema } from "./instructtype.js";
import {
  OutputModality,
  OutputModality$inboundSchema,
} from "./outputmodality.js";
import {
  PublicEndpoint,
  PublicEndpoint$inboundSchema,
} from "./publicendpoint.js";

/**
 * Tokenizer type used by the model
 */
export const Tokenizer = {
  Router: "Router",
  Media: "Media",
  Other: "Other",
  Gpt: "GPT",
  Claude: "Claude",
  Gemini: "Gemini",
  Gemma: "Gemma",
  Grok: "Grok",
  Cohere: "Cohere",
  Nova: "Nova",
  Qwen: "Qwen",
  Yi: "Yi",
  DeepSeek: "DeepSeek",
  Mistral: "Mistral",
  Llama2: "Llama2",
  Llama3: "Llama3",
  Llama4: "Llama4",
  PaLM: "PaLM",
  Rwkv: "RWKV",
  Qwen3: "Qwen3",
} as const;
/**
 * Tokenizer type used by the model
 */
export type Tokenizer = OpenEnum<typeof Tokenizer>;

/**
 * Model architecture information
 */
export type Architecture = {
  /**
   * Supported input modalities
   */
  inputModalities: Array<InputModality>;
  /**
   * Instruction format type
   */
  instructType: InstructType | null;
  /**
   * Primary modality of the model
   */
  modality: string | null;
  /**
   * Supported output modalities
   */
  outputModalities: Array<OutputModality>;
  tokenizer: Tokenizer | null;
};

/**
 * List of available endpoints for a model
 */
export type ListEndpointsResponse = {
  architecture: Architecture;
  /**
   * Unix timestamp of when the model was created
   */
  created: number;
  /**
   * Description of the model
   */
  description: string;
  /**
   * List of available endpoints for this model
   */
  endpoints: Array<PublicEndpoint>;
  /**
   * Unique identifier for the model
   */
  id: string;
  /**
   * Display name of the model
   */
  name: string;
};

/** @internal */
export const Tokenizer$inboundSchema: z.ZodType<Tokenizer, unknown> = openEnums
  .inboundSchema(Tokenizer);

/** @internal */
export const Architecture$inboundSchema: z.ZodType<Architecture, unknown> = z
  .object({
    input_modalities: z.array(InputModality$inboundSchema),
    instruct_type: z.nullable(InstructType$inboundSchema),
    modality: z.nullable(z.string()),
    output_modalities: z.array(OutputModality$inboundSchema),
    tokenizer: z.nullable(Tokenizer$inboundSchema),
  }).transform((v) => {
    return remap$(v, {
      "input_modalities": "inputModalities",
      "instruct_type": "instructType",
      "output_modalities": "outputModalities",
    });
  });

export function architectureFromJSON(
  jsonString: string,
): SafeParseResult<Architecture, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Architecture$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Architecture' from JSON`,
  );
}

/** @internal */
export const ListEndpointsResponse$inboundSchema: z.ZodType<
  ListEndpointsResponse,
  unknown
> = z.object({
  architecture: z.lazy(() => Architecture$inboundSchema),
  created: z.int(),
  description: z.string(),
  endpoints: z.array(PublicEndpoint$inboundSchema),
  id: z.string(),
  name: z.string(),
});

export function listEndpointsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListEndpointsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListEndpointsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListEndpointsResponse' from JSON`,
  );
}
