/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 5e5a26b93ed7
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { ClosedEnum, OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type AllowedTools = {
  readOnly?: boolean | undefined;
  toolNames?: Array<string> | undefined;
};

export type AllowedToolsUnion = Array<string> | AllowedTools | any;

export const ConnectorId = {
  ConnectorDropbox: "connector_dropbox",
  ConnectorGmail: "connector_gmail",
  ConnectorGooglecalendar: "connector_googlecalendar",
  ConnectorGoogledrive: "connector_googledrive",
  ConnectorMicrosoftteams: "connector_microsoftteams",
  ConnectorOutlookcalendar: "connector_outlookcalendar",
  ConnectorOutlookemail: "connector_outlookemail",
  ConnectorSharepoint: "connector_sharepoint",
} as const;
export type ConnectorId = OpenEnum<typeof ConnectorId>;

export const RequireApprovalNever = {
  Never: "never",
} as const;
export type RequireApprovalNever = ClosedEnum<typeof RequireApprovalNever>;

export const RequireApprovalAlways = {
  Always: "always",
} as const;
export type RequireApprovalAlways = ClosedEnum<typeof RequireApprovalAlways>;

export type Always = {
  toolNames?: Array<string> | undefined;
};

export type Never = {
  toolNames?: Array<string> | undefined;
};

export type RequireApproval = {
  always?: Always | undefined;
  never?: Never | undefined;
};

export type RequireApprovalUnion =
  | RequireApproval
  | RequireApprovalAlways
  | RequireApprovalNever
  | any;

/**
 * MCP (Model Context Protocol) tool configuration
 */
export type McpServerTool = {
  allowedTools?: Array<string> | AllowedTools | any | null | undefined;
  authorization?: string | undefined;
  connectorId?: ConnectorId | undefined;
  headers?: { [k: string]: string } | null | undefined;
  requireApproval?:
    | RequireApproval
    | RequireApprovalAlways
    | RequireApprovalNever
    | any
    | null
    | undefined;
  serverDescription?: string | undefined;
  serverLabel: string;
  serverUrl?: string | undefined;
  type: "mcp";
};

/** @internal */
export const AllowedTools$inboundSchema: z.ZodType<AllowedTools, unknown> = z
  .object({
    read_only: z.boolean().optional(),
    tool_names: z.array(z.string()).optional(),
  }).transform((v) => {
    return remap$(v, {
      "read_only": "readOnly",
      "tool_names": "toolNames",
    });
  });
/** @internal */
export type AllowedTools$Outbound = {
  read_only?: boolean | undefined;
  tool_names?: Array<string> | undefined;
};

/** @internal */
export const AllowedTools$outboundSchema: z.ZodType<
  AllowedTools$Outbound,
  AllowedTools
> = z.object({
  readOnly: z.boolean().optional(),
  toolNames: z.array(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    readOnly: "read_only",
    toolNames: "tool_names",
  });
});

export function allowedToolsToJSON(allowedTools: AllowedTools): string {
  return JSON.stringify(AllowedTools$outboundSchema.parse(allowedTools));
}
export function allowedToolsFromJSON(
  jsonString: string,
): SafeParseResult<AllowedTools, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AllowedTools$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AllowedTools' from JSON`,
  );
}

/** @internal */
export const AllowedToolsUnion$inboundSchema: z.ZodType<
  AllowedToolsUnion,
  unknown
> = z.union([
  z.array(z.string()),
  z.lazy(() => AllowedTools$inboundSchema),
  z.any(),
]);
/** @internal */
export type AllowedToolsUnion$Outbound =
  | Array<string>
  | AllowedTools$Outbound
  | any;

/** @internal */
export const AllowedToolsUnion$outboundSchema: z.ZodType<
  AllowedToolsUnion$Outbound,
  AllowedToolsUnion
> = z.union([
  z.array(z.string()),
  z.lazy(() => AllowedTools$outboundSchema),
  z.any(),
]);

export function allowedToolsUnionToJSON(
  allowedToolsUnion: AllowedToolsUnion,
): string {
  return JSON.stringify(
    AllowedToolsUnion$outboundSchema.parse(allowedToolsUnion),
  );
}
export function allowedToolsUnionFromJSON(
  jsonString: string,
): SafeParseResult<AllowedToolsUnion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AllowedToolsUnion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AllowedToolsUnion' from JSON`,
  );
}

/** @internal */
export const ConnectorId$inboundSchema: z.ZodType<ConnectorId, unknown> =
  openEnums.inboundSchema(ConnectorId);
/** @internal */
export const ConnectorId$outboundSchema: z.ZodType<string, ConnectorId> =
  openEnums.outboundSchema(ConnectorId);

/** @internal */
export const RequireApprovalNever$inboundSchema: z.ZodEnum<
  typeof RequireApprovalNever
> = z.enum(RequireApprovalNever);
/** @internal */
export const RequireApprovalNever$outboundSchema: z.ZodEnum<
  typeof RequireApprovalNever
> = RequireApprovalNever$inboundSchema;

/** @internal */
export const RequireApprovalAlways$inboundSchema: z.ZodEnum<
  typeof RequireApprovalAlways
> = z.enum(RequireApprovalAlways);
/** @internal */
export const RequireApprovalAlways$outboundSchema: z.ZodEnum<
  typeof RequireApprovalAlways
> = RequireApprovalAlways$inboundSchema;

/** @internal */
export const Always$inboundSchema: z.ZodType<Always, unknown> = z.object({
  tool_names: z.array(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "tool_names": "toolNames",
  });
});
/** @internal */
export type Always$Outbound = {
  tool_names?: Array<string> | undefined;
};

/** @internal */
export const Always$outboundSchema: z.ZodType<Always$Outbound, Always> = z
  .object({
    toolNames: z.array(z.string()).optional(),
  }).transform((v) => {
    return remap$(v, {
      toolNames: "tool_names",
    });
  });

export function alwaysToJSON(always: Always): string {
  return JSON.stringify(Always$outboundSchema.parse(always));
}
export function alwaysFromJSON(
  jsonString: string,
): SafeParseResult<Always, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Always$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Always' from JSON`,
  );
}

/** @internal */
export const Never$inboundSchema: z.ZodType<Never, unknown> = z.object({
  tool_names: z.array(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "tool_names": "toolNames",
  });
});
/** @internal */
export type Never$Outbound = {
  tool_names?: Array<string> | undefined;
};

/** @internal */
export const Never$outboundSchema: z.ZodType<Never$Outbound, Never> = z.object({
  toolNames: z.array(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    toolNames: "tool_names",
  });
});

export function neverToJSON(never: Never): string {
  return JSON.stringify(Never$outboundSchema.parse(never));
}
export function neverFromJSON(
  jsonString: string,
): SafeParseResult<Never, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Never$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Never' from JSON`,
  );
}

/** @internal */
export const RequireApproval$inboundSchema: z.ZodType<
  RequireApproval,
  unknown
> = z.object({
  always: z.lazy(() => Always$inboundSchema).optional(),
  never: z.lazy(() => Never$inboundSchema).optional(),
});
/** @internal */
export type RequireApproval$Outbound = {
  always?: Always$Outbound | undefined;
  never?: Never$Outbound | undefined;
};

/** @internal */
export const RequireApproval$outboundSchema: z.ZodType<
  RequireApproval$Outbound,
  RequireApproval
> = z.object({
  always: z.lazy(() => Always$outboundSchema).optional(),
  never: z.lazy(() => Never$outboundSchema).optional(),
});

export function requireApprovalToJSON(
  requireApproval: RequireApproval,
): string {
  return JSON.stringify(RequireApproval$outboundSchema.parse(requireApproval));
}
export function requireApprovalFromJSON(
  jsonString: string,
): SafeParseResult<RequireApproval, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RequireApproval$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RequireApproval' from JSON`,
  );
}

/** @internal */
export const RequireApprovalUnion$inboundSchema: z.ZodType<
  RequireApprovalUnion,
  unknown
> = z.union([
  z.lazy(() => RequireApproval$inboundSchema),
  RequireApprovalAlways$inboundSchema,
  RequireApprovalNever$inboundSchema,
  z.any(),
]);
/** @internal */
export type RequireApprovalUnion$Outbound =
  | RequireApproval$Outbound
  | string
  | string
  | any;

/** @internal */
export const RequireApprovalUnion$outboundSchema: z.ZodType<
  RequireApprovalUnion$Outbound,
  RequireApprovalUnion
> = z.union([
  z.lazy(() => RequireApproval$outboundSchema),
  RequireApprovalAlways$outboundSchema,
  RequireApprovalNever$outboundSchema,
  z.any(),
]);

export function requireApprovalUnionToJSON(
  requireApprovalUnion: RequireApprovalUnion,
): string {
  return JSON.stringify(
    RequireApprovalUnion$outboundSchema.parse(requireApprovalUnion),
  );
}
export function requireApprovalUnionFromJSON(
  jsonString: string,
): SafeParseResult<RequireApprovalUnion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RequireApprovalUnion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RequireApprovalUnion' from JSON`,
  );
}

/** @internal */
export const McpServerTool$inboundSchema: z.ZodType<McpServerTool, unknown> = z
  .object({
    allowed_tools: z.nullable(
      z.union([
        z.array(z.string()),
        z.lazy(() => AllowedTools$inboundSchema),
        z.any(),
      ]),
    ).optional(),
    authorization: z.string().optional(),
    connector_id: ConnectorId$inboundSchema.optional(),
    headers: z.nullable(z.record(z.string(), z.string())).optional(),
    require_approval: z.nullable(
      z.union([
        z.lazy(() => RequireApproval$inboundSchema),
        RequireApprovalAlways$inboundSchema,
        RequireApprovalNever$inboundSchema,
        z.any(),
      ]),
    ).optional(),
    server_description: z.string().optional(),
    server_label: z.string(),
    server_url: z.string().optional(),
    type: z.literal("mcp"),
  }).transform((v) => {
    return remap$(v, {
      "allowed_tools": "allowedTools",
      "connector_id": "connectorId",
      "require_approval": "requireApproval",
      "server_description": "serverDescription",
      "server_label": "serverLabel",
      "server_url": "serverUrl",
    });
  });
/** @internal */
export type McpServerTool$Outbound = {
  allowed_tools?:
    | Array<string>
    | AllowedTools$Outbound
    | any
    | null
    | undefined;
  authorization?: string | undefined;
  connector_id?: string | undefined;
  headers?: { [k: string]: string } | null | undefined;
  require_approval?:
    | RequireApproval$Outbound
    | string
    | string
    | any
    | null
    | undefined;
  server_description?: string | undefined;
  server_label: string;
  server_url?: string | undefined;
  type: "mcp";
};

/** @internal */
export const McpServerTool$outboundSchema: z.ZodType<
  McpServerTool$Outbound,
  McpServerTool
> = z.object({
  allowedTools: z.nullable(
    z.union([
      z.array(z.string()),
      z.lazy(() => AllowedTools$outboundSchema),
      z.any(),
    ]),
  ).optional(),
  authorization: z.string().optional(),
  connectorId: ConnectorId$outboundSchema.optional(),
  headers: z.nullable(z.record(z.string(), z.string())).optional(),
  requireApproval: z.nullable(
    z.union([
      z.lazy(() => RequireApproval$outboundSchema),
      RequireApprovalAlways$outboundSchema,
      RequireApprovalNever$outboundSchema,
      z.any(),
    ]),
  ).optional(),
  serverDescription: z.string().optional(),
  serverLabel: z.string(),
  serverUrl: z.string().optional(),
  type: z.literal("mcp"),
}).transform((v) => {
  return remap$(v, {
    allowedTools: "allowed_tools",
    connectorId: "connector_id",
    requireApproval: "require_approval",
    serverDescription: "server_description",
    serverLabel: "server_label",
    serverUrl: "server_url",
  });
});

export function mcpServerToolToJSON(mcpServerTool: McpServerTool): string {
  return JSON.stringify(McpServerTool$outboundSchema.parse(mcpServerTool));
}
export function mcpServerToolFromJSON(
  jsonString: string,
): SafeParseResult<McpServerTool, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => McpServerTool$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'McpServerTool' from JSON`,
  );
}
