/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 5e100b48823e
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type MemberAssignment = {
  /**
   * User ID of who made the assignment
   */
  assignedBy: string | null;
  /**
   * ISO 8601 timestamp of when the assignment was created
   */
  createdAt: string;
  /**
   * ID of the guardrail
   */
  guardrailId: string;
  /**
   * Unique identifier for the assignment
   */
  id: string;
  /**
   * Organization ID
   */
  organizationId: string;
  /**
   * Clerk user ID of the assigned member
   */
  userId: string;
};

/** @internal */
export const MemberAssignment$inboundSchema: z.ZodType<
  MemberAssignment,
  unknown
> = z.object({
  assigned_by: z.nullable(z.string()),
  created_at: z.string(),
  guardrail_id: z.string(),
  id: z.string(),
  organization_id: z.string(),
  user_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "assigned_by": "assignedBy",
    "created_at": "createdAt",
    "guardrail_id": "guardrailId",
    "organization_id": "organizationId",
    "user_id": "userId",
  });
});

export function memberAssignmentFromJSON(
  jsonString: string,
): SafeParseResult<MemberAssignment, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MemberAssignment$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MemberAssignment' from JSON`,
  );
}
