/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 965b10bc40c4
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Related API endpoints and resources for this model.
 */
export type ModelLinks = {
  /**
   * URL for the model details/endpoints API
   */
  details: string;
};

/** @internal */
export const ModelLinks$inboundSchema: z.ZodType<ModelLinks, unknown> = z
  .object({
    details: z.string(),
  });

export function modelLinksFromJSON(
  jsonString: string,
): SafeParseResult<ModelLinks, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ModelLinks$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ModelLinks' from JSON`,
  );
}
