/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 5445ae4a5385
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type OpenAIResponsesRefusalContent = {
  refusal: string;
  type: "refusal";
};

/** @internal */
export const OpenAIResponsesRefusalContent$inboundSchema: z.ZodType<
  OpenAIResponsesRefusalContent,
  unknown
> = z.object({
  refusal: z.string(),
  type: z.literal("refusal"),
});
/** @internal */
export type OpenAIResponsesRefusalContent$Outbound = {
  refusal: string;
  type: "refusal";
};

/** @internal */
export const OpenAIResponsesRefusalContent$outboundSchema: z.ZodType<
  OpenAIResponsesRefusalContent$Outbound,
  OpenAIResponsesRefusalContent
> = z.object({
  refusal: z.string(),
  type: z.literal("refusal"),
});

export function openAIResponsesRefusalContentToJSON(
  openAIResponsesRefusalContent: OpenAIResponsesRefusalContent,
): string {
  return JSON.stringify(
    OpenAIResponsesRefusalContent$outboundSchema.parse(
      openAIResponsesRefusalContent,
    ),
  );
}
export function openAIResponsesRefusalContentFromJSON(
  jsonString: string,
): SafeParseResult<OpenAIResponsesRefusalContent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OpenAIResponsesRefusalContent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OpenAIResponsesRefusalContent' from JSON`,
  );
}
