/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4d50f36832ad
 */

import * as z from "zod/v4";
import { ClosedEnum } from "../types/enums.js";
import {
  WebSearchConfig,
  WebSearchConfig$Outbound,
  WebSearchConfig$outboundSchema,
} from "./websearchconfig.js";

export const OpenRouterWebSearchServerToolType = {
  OpenrouterWebSearch: "openrouter:web_search",
} as const;
export type OpenRouterWebSearchServerToolType = ClosedEnum<
  typeof OpenRouterWebSearchServerToolType
>;

/**
 * OpenRouter built-in server tool: searches the web for current information
 */
export type OpenRouterWebSearchServerTool = {
  parameters?: WebSearchConfig | undefined;
  type: OpenRouterWebSearchServerToolType;
};

/** @internal */
export const OpenRouterWebSearchServerToolType$outboundSchema: z.ZodEnum<
  typeof OpenRouterWebSearchServerToolType
> = z.enum(OpenRouterWebSearchServerToolType);

/** @internal */
export type OpenRouterWebSearchServerTool$Outbound = {
  parameters?: WebSearchConfig$Outbound | undefined;
  type: string;
};

/** @internal */
export const OpenRouterWebSearchServerTool$outboundSchema: z.ZodType<
  OpenRouterWebSearchServerTool$Outbound,
  OpenRouterWebSearchServerTool
> = z.object({
  parameters: WebSearchConfig$outboundSchema.optional(),
  type: OpenRouterWebSearchServerToolType$outboundSchema,
});

export function openRouterWebSearchServerToolToJSON(
  openRouterWebSearchServerTool: OpenRouterWebSearchServerTool,
): string {
  return JSON.stringify(
    OpenRouterWebSearchServerTool$outboundSchema.parse(
      openRouterWebSearchServerTool,
    ),
  );
}
