/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d27a63e0fb93
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  ToolCallStatus,
  ToolCallStatus$inboundSchema,
} from "./toolcallstatus.js";

export const OpenAIResponseFunctionToolCallType = {
  FunctionCall: "function_call",
} as const;
export type OpenAIResponseFunctionToolCallType = ClosedEnum<
  typeof OpenAIResponseFunctionToolCallType
>;

export type OpenAIResponseFunctionToolCall = {
  arguments: string;
  callId: string;
  id?: string | undefined;
  name: string;
  status?: ToolCallStatus | undefined;
  type: OpenAIResponseFunctionToolCallType;
};

/** @internal */
export const OpenAIResponseFunctionToolCallType$inboundSchema: z.ZodEnum<
  typeof OpenAIResponseFunctionToolCallType
> = z.enum(OpenAIResponseFunctionToolCallType);

/** @internal */
export const OpenAIResponseFunctionToolCall$inboundSchema: z.ZodType<
  OpenAIResponseFunctionToolCall,
  unknown
> = z.object({
  arguments: z.string(),
  call_id: z.string(),
  id: z.string().optional(),
  name: z.string(),
  status: ToolCallStatus$inboundSchema.optional(),
  type: OpenAIResponseFunctionToolCallType$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "call_id": "callId",
  });
});

export function openAIResponseFunctionToolCallFromJSON(
  jsonString: string,
): SafeParseResult<OpenAIResponseFunctionToolCall, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OpenAIResponseFunctionToolCall$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OpenAIResponseFunctionToolCall' from JSON`,
  );
}
