/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 44b1a23df5d5
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  OpenResponsesResult,
  OpenResponsesResult$inboundSchema,
} from "./openresponsesresult.js";

/**
 * Event emitted when a response is in progress
 */
export type OpenResponsesInProgressEvent = {
  /**
   * Complete non-streaming response from the Responses API
   */
  response: OpenResponsesResult;
  sequenceNumber: number;
  type: "response.in_progress";
};

/** @internal */
export const OpenResponsesInProgressEvent$inboundSchema: z.ZodType<
  OpenResponsesInProgressEvent,
  unknown
> = z.object({
  response: OpenResponsesResult$inboundSchema,
  sequence_number: z.int(),
  type: z.literal("response.in_progress"),
}).transform((v) => {
  return remap$(v, {
    "sequence_number": "sequenceNumber",
  });
});

export function openResponsesInProgressEventFromJSON(
  jsonString: string,
): SafeParseResult<OpenResponsesInProgressEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OpenResponsesInProgressEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OpenResponsesInProgressEvent' from JSON`,
  );
}
