/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 73d80db9cd46
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  ToolChoiceAllowed,
  ToolChoiceAllowed$inboundSchema,
  ToolChoiceAllowed$Outbound,
  ToolChoiceAllowed$outboundSchema,
} from "./toolchoiceallowed.js";

export const OpenAIResponsesToolChoiceTypeWebSearchPreview = {
  WebSearchPreview: "web_search_preview",
} as const;
export type OpenAIResponsesToolChoiceTypeWebSearchPreview = ClosedEnum<
  typeof OpenAIResponsesToolChoiceTypeWebSearchPreview
>;

export const OpenAIResponsesToolChoiceTypeWebSearchPreview20250311 = {
  WebSearchPreview20250311: "web_search_preview_2025_03_11",
} as const;
export type OpenAIResponsesToolChoiceTypeWebSearchPreview20250311 = ClosedEnum<
  typeof OpenAIResponsesToolChoiceTypeWebSearchPreview20250311
>;

export type Type =
  | OpenAIResponsesToolChoiceTypeWebSearchPreview20250311
  | OpenAIResponsesToolChoiceTypeWebSearchPreview;

export type OpenAIResponsesToolChoice = {
  type:
    | OpenAIResponsesToolChoiceTypeWebSearchPreview20250311
    | OpenAIResponsesToolChoiceTypeWebSearchPreview;
};

export const OpenAIResponsesToolChoiceTypeFunction = {
  Function: "function",
} as const;
export type OpenAIResponsesToolChoiceTypeFunction = ClosedEnum<
  typeof OpenAIResponsesToolChoiceTypeFunction
>;

export type OpenAIResponsesToolChoiceFunction = {
  name: string;
  type: OpenAIResponsesToolChoiceTypeFunction;
};

export const OpenAIResponsesToolChoiceRequired = {
  Required: "required",
} as const;
export type OpenAIResponsesToolChoiceRequired = ClosedEnum<
  typeof OpenAIResponsesToolChoiceRequired
>;

export const OpenAIResponsesToolChoiceNone = {
  None: "none",
} as const;
export type OpenAIResponsesToolChoiceNone = ClosedEnum<
  typeof OpenAIResponsesToolChoiceNone
>;

export const OpenAIResponsesToolChoiceAuto = {
  Auto: "auto",
} as const;
export type OpenAIResponsesToolChoiceAuto = ClosedEnum<
  typeof OpenAIResponsesToolChoiceAuto
>;

export type OpenAIResponsesToolChoiceUnion =
  | ToolChoiceAllowed
  | OpenAIResponsesToolChoiceFunction
  | OpenAIResponsesToolChoice
  | OpenAIResponsesToolChoiceAuto
  | OpenAIResponsesToolChoiceNone
  | OpenAIResponsesToolChoiceRequired;

/** @internal */
export const OpenAIResponsesToolChoiceTypeWebSearchPreview$inboundSchema:
  z.ZodEnum<typeof OpenAIResponsesToolChoiceTypeWebSearchPreview> = z.enum(
    OpenAIResponsesToolChoiceTypeWebSearchPreview,
  );
/** @internal */
export const OpenAIResponsesToolChoiceTypeWebSearchPreview$outboundSchema:
  z.ZodEnum<typeof OpenAIResponsesToolChoiceTypeWebSearchPreview> =
    OpenAIResponsesToolChoiceTypeWebSearchPreview$inboundSchema;

/** @internal */
export const OpenAIResponsesToolChoiceTypeWebSearchPreview20250311$inboundSchema:
  z.ZodEnum<typeof OpenAIResponsesToolChoiceTypeWebSearchPreview20250311> = z
    .enum(OpenAIResponsesToolChoiceTypeWebSearchPreview20250311);
/** @internal */
export const OpenAIResponsesToolChoiceTypeWebSearchPreview20250311$outboundSchema:
  z.ZodEnum<typeof OpenAIResponsesToolChoiceTypeWebSearchPreview20250311> =
    OpenAIResponsesToolChoiceTypeWebSearchPreview20250311$inboundSchema;

/** @internal */
export const Type$inboundSchema: z.ZodType<Type, unknown> = z.union([
  OpenAIResponsesToolChoiceTypeWebSearchPreview20250311$inboundSchema,
  OpenAIResponsesToolChoiceTypeWebSearchPreview$inboundSchema,
]);
/** @internal */
export type Type$Outbound = string | string;

/** @internal */
export const Type$outboundSchema: z.ZodType<Type$Outbound, Type> = z.union([
  OpenAIResponsesToolChoiceTypeWebSearchPreview20250311$outboundSchema,
  OpenAIResponsesToolChoiceTypeWebSearchPreview$outboundSchema,
]);

export function typeToJSON(type: Type): string {
  return JSON.stringify(Type$outboundSchema.parse(type));
}
export function typeFromJSON(
  jsonString: string,
): SafeParseResult<Type, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Type$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Type' from JSON`,
  );
}

/** @internal */
export const OpenAIResponsesToolChoice$inboundSchema: z.ZodType<
  OpenAIResponsesToolChoice,
  unknown
> = z.object({
  type: z.union([
    OpenAIResponsesToolChoiceTypeWebSearchPreview20250311$inboundSchema,
    OpenAIResponsesToolChoiceTypeWebSearchPreview$inboundSchema,
  ]),
});
/** @internal */
export type OpenAIResponsesToolChoice$Outbound = {
  type: string | string;
};

/** @internal */
export const OpenAIResponsesToolChoice$outboundSchema: z.ZodType<
  OpenAIResponsesToolChoice$Outbound,
  OpenAIResponsesToolChoice
> = z.object({
  type: z.union([
    OpenAIResponsesToolChoiceTypeWebSearchPreview20250311$outboundSchema,
    OpenAIResponsesToolChoiceTypeWebSearchPreview$outboundSchema,
  ]),
});

export function openAIResponsesToolChoiceToJSON(
  openAIResponsesToolChoice: OpenAIResponsesToolChoice,
): string {
  return JSON.stringify(
    OpenAIResponsesToolChoice$outboundSchema.parse(openAIResponsesToolChoice),
  );
}
export function openAIResponsesToolChoiceFromJSON(
  jsonString: string,
): SafeParseResult<OpenAIResponsesToolChoice, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OpenAIResponsesToolChoice$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OpenAIResponsesToolChoice' from JSON`,
  );
}

/** @internal */
export const OpenAIResponsesToolChoiceTypeFunction$inboundSchema: z.ZodEnum<
  typeof OpenAIResponsesToolChoiceTypeFunction
> = z.enum(OpenAIResponsesToolChoiceTypeFunction);
/** @internal */
export const OpenAIResponsesToolChoiceTypeFunction$outboundSchema: z.ZodEnum<
  typeof OpenAIResponsesToolChoiceTypeFunction
> = OpenAIResponsesToolChoiceTypeFunction$inboundSchema;

/** @internal */
export const OpenAIResponsesToolChoiceFunction$inboundSchema: z.ZodType<
  OpenAIResponsesToolChoiceFunction,
  unknown
> = z.object({
  name: z.string(),
  type: OpenAIResponsesToolChoiceTypeFunction$inboundSchema,
});
/** @internal */
export type OpenAIResponsesToolChoiceFunction$Outbound = {
  name: string;
  type: string;
};

/** @internal */
export const OpenAIResponsesToolChoiceFunction$outboundSchema: z.ZodType<
  OpenAIResponsesToolChoiceFunction$Outbound,
  OpenAIResponsesToolChoiceFunction
> = z.object({
  name: z.string(),
  type: OpenAIResponsesToolChoiceTypeFunction$outboundSchema,
});

export function openAIResponsesToolChoiceFunctionToJSON(
  openAIResponsesToolChoiceFunction: OpenAIResponsesToolChoiceFunction,
): string {
  return JSON.stringify(
    OpenAIResponsesToolChoiceFunction$outboundSchema.parse(
      openAIResponsesToolChoiceFunction,
    ),
  );
}
export function openAIResponsesToolChoiceFunctionFromJSON(
  jsonString: string,
): SafeParseResult<OpenAIResponsesToolChoiceFunction, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OpenAIResponsesToolChoiceFunction$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OpenAIResponsesToolChoiceFunction' from JSON`,
  );
}

/** @internal */
export const OpenAIResponsesToolChoiceRequired$inboundSchema: z.ZodEnum<
  typeof OpenAIResponsesToolChoiceRequired
> = z.enum(OpenAIResponsesToolChoiceRequired);
/** @internal */
export const OpenAIResponsesToolChoiceRequired$outboundSchema: z.ZodEnum<
  typeof OpenAIResponsesToolChoiceRequired
> = OpenAIResponsesToolChoiceRequired$inboundSchema;

/** @internal */
export const OpenAIResponsesToolChoiceNone$inboundSchema: z.ZodEnum<
  typeof OpenAIResponsesToolChoiceNone
> = z.enum(OpenAIResponsesToolChoiceNone);
/** @internal */
export const OpenAIResponsesToolChoiceNone$outboundSchema: z.ZodEnum<
  typeof OpenAIResponsesToolChoiceNone
> = OpenAIResponsesToolChoiceNone$inboundSchema;

/** @internal */
export const OpenAIResponsesToolChoiceAuto$inboundSchema: z.ZodEnum<
  typeof OpenAIResponsesToolChoiceAuto
> = z.enum(OpenAIResponsesToolChoiceAuto);
/** @internal */
export const OpenAIResponsesToolChoiceAuto$outboundSchema: z.ZodEnum<
  typeof OpenAIResponsesToolChoiceAuto
> = OpenAIResponsesToolChoiceAuto$inboundSchema;

/** @internal */
export const OpenAIResponsesToolChoiceUnion$inboundSchema: z.ZodType<
  OpenAIResponsesToolChoiceUnion,
  unknown
> = z.union([
  ToolChoiceAllowed$inboundSchema,
  z.lazy(() => OpenAIResponsesToolChoiceFunction$inboundSchema),
  z.lazy(() => OpenAIResponsesToolChoice$inboundSchema),
  OpenAIResponsesToolChoiceAuto$inboundSchema,
  OpenAIResponsesToolChoiceNone$inboundSchema,
  OpenAIResponsesToolChoiceRequired$inboundSchema,
]);
/** @internal */
export type OpenAIResponsesToolChoiceUnion$Outbound =
  | ToolChoiceAllowed$Outbound
  | OpenAIResponsesToolChoiceFunction$Outbound
  | OpenAIResponsesToolChoice$Outbound
  | string
  | string
  | string;

/** @internal */
export const OpenAIResponsesToolChoiceUnion$outboundSchema: z.ZodType<
  OpenAIResponsesToolChoiceUnion$Outbound,
  OpenAIResponsesToolChoiceUnion
> = z.union([
  ToolChoiceAllowed$outboundSchema,
  z.lazy(() => OpenAIResponsesToolChoiceFunction$outboundSchema),
  z.lazy(() => OpenAIResponsesToolChoice$outboundSchema),
  OpenAIResponsesToolChoiceAuto$outboundSchema,
  OpenAIResponsesToolChoiceNone$outboundSchema,
  OpenAIResponsesToolChoiceRequired$outboundSchema,
]);

export function openAIResponsesToolChoiceUnionToJSON(
  openAIResponsesToolChoiceUnion: OpenAIResponsesToolChoiceUnion,
): string {
  return JSON.stringify(
    OpenAIResponsesToolChoiceUnion$outboundSchema.parse(
      openAIResponsesToolChoiceUnion,
    ),
  );
}
export function openAIResponsesToolChoiceUnionFromJSON(
  jsonString: string,
): SafeParseResult<OpenAIResponsesToolChoiceUnion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OpenAIResponsesToolChoiceUnion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OpenAIResponsesToolChoiceUnion' from JSON`,
  );
}
