/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 78c25d89c63e
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as discriminatedUnionTypes from "../types/discriminatedUnion.js";
import { discriminatedUnion } from "../types/discriminatedUnion.js";
import * as openEnums from "../types/enums.js";
import { ClosedEnum, OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { InputFile, InputFile$inboundSchema } from "./inputfile.js";
import { InputImage, InputImage$inboundSchema } from "./inputimage.js";
import { InputText, InputText$inboundSchema } from "./inputtext.js";

export type OpenAIResponseFunctionToolCallOutputOutput1 =
  | InputFile
  | (InputImage & { type: "input_image" })
  | InputText
  | discriminatedUnionTypes.Unknown<"type">;

export type OpenAIResponseFunctionToolCallOutputOutput2 =
  | string
  | Array<
    | InputFile
    | (InputImage & { type: "input_image" })
    | InputText
    | discriminatedUnionTypes.Unknown<"type">
  >;

export const OpenAIResponseFunctionToolCallOutputStatus = {
  InProgress: "in_progress",
  Completed: "completed",
  Incomplete: "incomplete",
} as const;
export type OpenAIResponseFunctionToolCallOutputStatus = OpenEnum<
  typeof OpenAIResponseFunctionToolCallOutputStatus
>;

export const OpenAIResponseFunctionToolCallOutputType = {
  FunctionCallOutput: "function_call_output",
} as const;
export type OpenAIResponseFunctionToolCallOutputType = ClosedEnum<
  typeof OpenAIResponseFunctionToolCallOutputType
>;

export type OpenAIResponseFunctionToolCallOutput = {
  callId: string;
  id?: string | null | undefined;
  output:
    | string
    | Array<
      | InputFile
      | (InputImage & { type: "input_image" })
      | InputText
      | discriminatedUnionTypes.Unknown<"type">
    >;
  status?: OpenAIResponseFunctionToolCallOutputStatus | null | undefined;
  type: OpenAIResponseFunctionToolCallOutputType;
};

/** @internal */
export const OpenAIResponseFunctionToolCallOutputOutput1$inboundSchema:
  z.ZodType<OpenAIResponseFunctionToolCallOutputOutput1, unknown> =
    discriminatedUnion("type", {
      input_file: InputFile$inboundSchema,
      input_image: InputImage$inboundSchema.and(
        z.object({ type: z.literal("input_image") }),
      ),
      input_text: InputText$inboundSchema,
    });

export function openAIResponseFunctionToolCallOutputOutput1FromJSON(
  jsonString: string,
): SafeParseResult<
  OpenAIResponseFunctionToolCallOutputOutput1,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      OpenAIResponseFunctionToolCallOutputOutput1$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'OpenAIResponseFunctionToolCallOutputOutput1' from JSON`,
  );
}

/** @internal */
export const OpenAIResponseFunctionToolCallOutputOutput2$inboundSchema:
  z.ZodType<OpenAIResponseFunctionToolCallOutputOutput2, unknown> = z.union([
    z.string(),
    z.array(
      discriminatedUnion("type", {
        input_file: InputFile$inboundSchema,
        input_image: InputImage$inboundSchema.and(
          z.object({ type: z.literal("input_image") }),
        ),
        input_text: InputText$inboundSchema,
      }),
    ),
  ]);

export function openAIResponseFunctionToolCallOutputOutput2FromJSON(
  jsonString: string,
): SafeParseResult<
  OpenAIResponseFunctionToolCallOutputOutput2,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      OpenAIResponseFunctionToolCallOutputOutput2$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'OpenAIResponseFunctionToolCallOutputOutput2' from JSON`,
  );
}

/** @internal */
export const OpenAIResponseFunctionToolCallOutputStatus$inboundSchema:
  z.ZodType<OpenAIResponseFunctionToolCallOutputStatus, unknown> = openEnums
    .inboundSchema(OpenAIResponseFunctionToolCallOutputStatus);

/** @internal */
export const OpenAIResponseFunctionToolCallOutputType$inboundSchema: z.ZodEnum<
  typeof OpenAIResponseFunctionToolCallOutputType
> = z.enum(OpenAIResponseFunctionToolCallOutputType);

/** @internal */
export const OpenAIResponseFunctionToolCallOutput$inboundSchema: z.ZodType<
  OpenAIResponseFunctionToolCallOutput,
  unknown
> = z.object({
  call_id: z.string(),
  id: z.nullable(z.string()).optional(),
  output: z.union([
    z.string(),
    z.array(
      discriminatedUnion("type", {
        input_file: InputFile$inboundSchema,
        input_image: InputImage$inboundSchema.and(
          z.object({ type: z.literal("input_image") }),
        ),
        input_text: InputText$inboundSchema,
      }),
    ),
  ]),
  status: z.nullable(OpenAIResponseFunctionToolCallOutputStatus$inboundSchema)
    .optional(),
  type: OpenAIResponseFunctionToolCallOutputType$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "call_id": "callId",
  });
});

export function openAIResponseFunctionToolCallOutputFromJSON(
  jsonString: string,
): SafeParseResult<OpenAIResponseFunctionToolCallOutput, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      OpenAIResponseFunctionToolCallOutput$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OpenAIResponseFunctionToolCallOutput' from JSON`,
  );
}
