/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 67004da2ad5c
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import * as discriminatedUnionTypes from "../types/discriminatedUnion.js";
import { discriminatedUnion } from "../types/discriminatedUnion.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { InputAudio, InputAudio$inboundSchema } from "./inputaudio.js";
import { InputFile, InputFile$inboundSchema } from "./inputfile.js";
import { InputImage, InputImage$inboundSchema } from "./inputimage.js";
import { InputText, InputText$inboundSchema } from "./inputtext.js";

export type OpenAIResponseInputMessageItemContent =
  | InputAudio
  | InputFile
  | (InputImage & { type: "input_image" })
  | InputText
  | discriminatedUnionTypes.Unknown<"type">;

export const OpenAIResponseInputMessageItemRoleDeveloper = {
  Developer: "developer",
} as const;
export type OpenAIResponseInputMessageItemRoleDeveloper = ClosedEnum<
  typeof OpenAIResponseInputMessageItemRoleDeveloper
>;

export const OpenAIResponseInputMessageItemRoleSystem = {
  System: "system",
} as const;
export type OpenAIResponseInputMessageItemRoleSystem = ClosedEnum<
  typeof OpenAIResponseInputMessageItemRoleSystem
>;

export const OpenAIResponseInputMessageItemRoleUser = {
  User: "user",
} as const;
export type OpenAIResponseInputMessageItemRoleUser = ClosedEnum<
  typeof OpenAIResponseInputMessageItemRoleUser
>;

export type OpenAIResponseInputMessageItemRoleUnion =
  | OpenAIResponseInputMessageItemRoleUser
  | OpenAIResponseInputMessageItemRoleSystem
  | OpenAIResponseInputMessageItemRoleDeveloper;

export const OpenAIResponseInputMessageItemType = {
  Message: "message",
} as const;
export type OpenAIResponseInputMessageItemType = ClosedEnum<
  typeof OpenAIResponseInputMessageItemType
>;

export type OpenAIResponseInputMessageItem = {
  content: Array<
    | InputAudio
    | InputFile
    | (InputImage & { type: "input_image" })
    | InputText
    | discriminatedUnionTypes.Unknown<"type">
  >;
  id: string;
  role:
    | OpenAIResponseInputMessageItemRoleUser
    | OpenAIResponseInputMessageItemRoleSystem
    | OpenAIResponseInputMessageItemRoleDeveloper;
  type?: OpenAIResponseInputMessageItemType | undefined;
};

/** @internal */
export const OpenAIResponseInputMessageItemContent$inboundSchema: z.ZodType<
  OpenAIResponseInputMessageItemContent,
  unknown
> = discriminatedUnion("type", {
  input_audio: InputAudio$inboundSchema,
  input_file: InputFile$inboundSchema,
  input_image: InputImage$inboundSchema.and(
    z.object({ type: z.literal("input_image") }),
  ),
  input_text: InputText$inboundSchema,
});

export function openAIResponseInputMessageItemContentFromJSON(
  jsonString: string,
): SafeParseResult<OpenAIResponseInputMessageItemContent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      OpenAIResponseInputMessageItemContent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OpenAIResponseInputMessageItemContent' from JSON`,
  );
}

/** @internal */
export const OpenAIResponseInputMessageItemRoleDeveloper$inboundSchema:
  z.ZodEnum<typeof OpenAIResponseInputMessageItemRoleDeveloper> = z.enum(
    OpenAIResponseInputMessageItemRoleDeveloper,
  );

/** @internal */
export const OpenAIResponseInputMessageItemRoleSystem$inboundSchema: z.ZodEnum<
  typeof OpenAIResponseInputMessageItemRoleSystem
> = z.enum(OpenAIResponseInputMessageItemRoleSystem);

/** @internal */
export const OpenAIResponseInputMessageItemRoleUser$inboundSchema: z.ZodEnum<
  typeof OpenAIResponseInputMessageItemRoleUser
> = z.enum(OpenAIResponseInputMessageItemRoleUser);

/** @internal */
export const OpenAIResponseInputMessageItemRoleUnion$inboundSchema: z.ZodType<
  OpenAIResponseInputMessageItemRoleUnion,
  unknown
> = z.union([
  OpenAIResponseInputMessageItemRoleUser$inboundSchema,
  OpenAIResponseInputMessageItemRoleSystem$inboundSchema,
  OpenAIResponseInputMessageItemRoleDeveloper$inboundSchema,
]);

export function openAIResponseInputMessageItemRoleUnionFromJSON(
  jsonString: string,
): SafeParseResult<
  OpenAIResponseInputMessageItemRoleUnion,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      OpenAIResponseInputMessageItemRoleUnion$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'OpenAIResponseInputMessageItemRoleUnion' from JSON`,
  );
}

/** @internal */
export const OpenAIResponseInputMessageItemType$inboundSchema: z.ZodEnum<
  typeof OpenAIResponseInputMessageItemType
> = z.enum(OpenAIResponseInputMessageItemType);

/** @internal */
export const OpenAIResponseInputMessageItem$inboundSchema: z.ZodType<
  OpenAIResponseInputMessageItem,
  unknown
> = z.object({
  content: z.array(discriminatedUnion("type", {
    input_audio: InputAudio$inboundSchema,
    input_file: InputFile$inboundSchema,
    input_image: InputImage$inboundSchema.and(
      z.object({ type: z.literal("input_image") }),
    ),
    input_text: InputText$inboundSchema,
  })),
  id: z.string(),
  role: z.union([
    OpenAIResponseInputMessageItemRoleUser$inboundSchema,
    OpenAIResponseInputMessageItemRoleSystem$inboundSchema,
    OpenAIResponseInputMessageItemRoleDeveloper$inboundSchema,
  ]),
  type: OpenAIResponseInputMessageItemType$inboundSchema.optional(),
});

export function openAIResponseInputMessageItemFromJSON(
  jsonString: string,
): SafeParseResult<OpenAIResponseInputMessageItem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OpenAIResponseInputMessageItem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OpenAIResponseInputMessageItem' from JSON`,
  );
}
