/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 0d7161b3403e
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import * as discriminatedUnionTypes from "../types/discriminatedUnion.js";
import { discriminatedUnion } from "../types/discriminatedUnion.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  OutputDatetimeItem,
  OutputDatetimeItem$inboundSchema,
} from "./outputdatetimeitem.js";
import {
  OutputFileSearchCallItem,
  OutputFileSearchCallItem$inboundSchema,
} from "./outputfilesearchcallitem.js";
import {
  OutputFunctionCallItem,
  OutputFunctionCallItem$inboundSchema,
} from "./outputfunctioncallitem.js";
import {
  OutputImageGenerationCallItem,
  OutputImageGenerationCallItem$inboundSchema,
} from "./outputimagegenerationcallitem.js";
import {
  OutputMessageItem,
  OutputMessageItem$inboundSchema,
} from "./outputmessageitem.js";
import {
  OutputReasoningItem,
  OutputReasoningItem$inboundSchema,
} from "./outputreasoningitem.js";
import {
  OutputWebSearchCallItem,
  OutputWebSearchCallItem$inboundSchema,
} from "./outputwebsearchcallitem.js";
import {
  OutputWebSearchServerToolItem,
  OutputWebSearchServerToolItem$inboundSchema,
} from "./outputwebsearchservertoolitem.js";

/**
 * An output item from the response
 */
export type OutputItems =
  | (OutputFileSearchCallItem & { type: "file_search_call" })
  | (OutputFunctionCallItem & { type: "function_call" })
  | (OutputImageGenerationCallItem & { type: "image_generation_call" })
  | OutputMessageItem
  | (OutputDatetimeItem & { type: "openrouter:datetime" })
  | (OutputWebSearchServerToolItem & { type: "openrouter:web_search" })
  | OutputReasoningItem
  | (OutputWebSearchCallItem & { type: "web_search_call" })
  | discriminatedUnionTypes.Unknown<"type">;

/** @internal */
export const OutputItems$inboundSchema: z.ZodType<OutputItems, unknown> =
  discriminatedUnion("type", {
    file_search_call: OutputFileSearchCallItem$inboundSchema.and(
      z.object({ type: z.literal("file_search_call") }),
    ),
    function_call: OutputFunctionCallItem$inboundSchema.and(
      z.object({ type: z.literal("function_call") }),
    ),
    image_generation_call: OutputImageGenerationCallItem$inboundSchema.and(
      z.object({ type: z.literal("image_generation_call") }),
    ),
    message: OutputMessageItem$inboundSchema,
    ["openrouter:datetime"]: OutputDatetimeItem$inboundSchema.and(
      z.object({ type: z.literal("openrouter:datetime") }),
    ),
    ["openrouter:web_search"]: OutputWebSearchServerToolItem$inboundSchema.and(
      z.object({ type: z.literal("openrouter:web_search") }),
    ),
    reasoning: OutputReasoningItem$inboundSchema,
    web_search_call: OutputWebSearchCallItem$inboundSchema.and(
      z.object({ type: z.literal("web_search_call") }),
    ),
  });

export function outputItemsFromJSON(
  jsonString: string,
): SafeParseResult<OutputItems, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OutputItems$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OutputItems' from JSON`,
  );
}
