/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 618bac10713d
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  ImageGenerationStatus,
  ImageGenerationStatus$inboundSchema,
  ImageGenerationStatus$outboundSchema,
} from "./imagegenerationstatus.js";

export const OutputImageGenerationCallItemType = {
  ImageGenerationCall: "image_generation_call",
} as const;
export type OutputImageGenerationCallItemType = ClosedEnum<
  typeof OutputImageGenerationCallItemType
>;

export type OutputImageGenerationCallItem = {
  id: string;
  result?: string | null | undefined;
  status: ImageGenerationStatus;
  type: OutputImageGenerationCallItemType;
};

/** @internal */
export const OutputImageGenerationCallItemType$inboundSchema: z.ZodEnum<
  typeof OutputImageGenerationCallItemType
> = z.enum(OutputImageGenerationCallItemType);
/** @internal */
export const OutputImageGenerationCallItemType$outboundSchema: z.ZodEnum<
  typeof OutputImageGenerationCallItemType
> = OutputImageGenerationCallItemType$inboundSchema;

/** @internal */
export const OutputImageGenerationCallItem$inboundSchema: z.ZodType<
  OutputImageGenerationCallItem,
  unknown
> = z.object({
  id: z.string(),
  result: z.nullable(z.string()).default(null),
  status: ImageGenerationStatus$inboundSchema,
  type: OutputImageGenerationCallItemType$inboundSchema,
});
/** @internal */
export type OutputImageGenerationCallItem$Outbound = {
  id: string;
  result: string | null;
  status: string;
  type: string;
};

/** @internal */
export const OutputImageGenerationCallItem$outboundSchema: z.ZodType<
  OutputImageGenerationCallItem$Outbound,
  OutputImageGenerationCallItem
> = z.object({
  id: z.string(),
  result: z.nullable(z.string()).default(null),
  status: ImageGenerationStatus$outboundSchema,
  type: OutputImageGenerationCallItemType$outboundSchema,
});

export function outputImageGenerationCallItemToJSON(
  outputImageGenerationCallItem: OutputImageGenerationCallItem,
): string {
  return JSON.stringify(
    OutputImageGenerationCallItem$outboundSchema.parse(
      outputImageGenerationCallItem,
    ),
  );
}
export function outputImageGenerationCallItemFromJSON(
  jsonString: string,
): SafeParseResult<OutputImageGenerationCallItem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OutputImageGenerationCallItem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OutputImageGenerationCallItem' from JSON`,
  );
}
