/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: eafceec94b81
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  WebSearchStatus,
  WebSearchStatus$inboundSchema,
  WebSearchStatus$outboundSchema,
} from "./websearchstatus.js";

export const OutputFileSearchCallItemType = {
  FileSearchCall: "file_search_call",
} as const;
export type OutputFileSearchCallItemType = ClosedEnum<
  typeof OutputFileSearchCallItemType
>;

export type OutputFileSearchCallItem = {
  id: string;
  queries: Array<string>;
  status: WebSearchStatus;
  type: OutputFileSearchCallItemType;
};

/** @internal */
export const OutputFileSearchCallItemType$inboundSchema: z.ZodEnum<
  typeof OutputFileSearchCallItemType
> = z.enum(OutputFileSearchCallItemType);
/** @internal */
export const OutputFileSearchCallItemType$outboundSchema: z.ZodEnum<
  typeof OutputFileSearchCallItemType
> = OutputFileSearchCallItemType$inboundSchema;

/** @internal */
export const OutputFileSearchCallItem$inboundSchema: z.ZodType<
  OutputFileSearchCallItem,
  unknown
> = z.object({
  id: z.string(),
  queries: z.array(z.string()),
  status: WebSearchStatus$inboundSchema,
  type: OutputFileSearchCallItemType$inboundSchema,
});
/** @internal */
export type OutputFileSearchCallItem$Outbound = {
  id: string;
  queries: Array<string>;
  status: string;
  type: string;
};

/** @internal */
export const OutputFileSearchCallItem$outboundSchema: z.ZodType<
  OutputFileSearchCallItem$Outbound,
  OutputFileSearchCallItem
> = z.object({
  id: z.string(),
  queries: z.array(z.string()),
  status: WebSearchStatus$outboundSchema,
  type: OutputFileSearchCallItemType$outboundSchema,
});

export function outputFileSearchCallItemToJSON(
  outputFileSearchCallItem: OutputFileSearchCallItem,
): string {
  return JSON.stringify(
    OutputFileSearchCallItem$outboundSchema.parse(outputFileSearchCallItem),
  );
}
export function outputFileSearchCallItemFromJSON(
  jsonString: string,
): SafeParseResult<OutputFileSearchCallItem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OutputFileSearchCallItem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OutputFileSearchCallItem' from JSON`,
  );
}
