/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 9c3ac6a7a9ad
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  ImageGenerationStatus,
  ImageGenerationStatus$inboundSchema,
} from "./imagegenerationstatus.js";

export const OutputItemImageGenerationCallType = {
  ImageGenerationCall: "image_generation_call",
} as const;
export type OutputItemImageGenerationCallType = ClosedEnum<
  typeof OutputItemImageGenerationCallType
>;

export type OutputItemImageGenerationCall = {
  id: string;
  result: string | null;
  status: ImageGenerationStatus;
  type: OutputItemImageGenerationCallType;
};

/** @internal */
export const OutputItemImageGenerationCallType$inboundSchema: z.ZodEnum<
  typeof OutputItemImageGenerationCallType
> = z.enum(OutputItemImageGenerationCallType);

/** @internal */
export const OutputItemImageGenerationCall$inboundSchema: z.ZodType<
  OutputItemImageGenerationCall,
  unknown
> = z.object({
  id: z.string(),
  result: z.nullable(z.string()).default(null),
  status: ImageGenerationStatus$inboundSchema,
  type: OutputItemImageGenerationCallType$inboundSchema,
});

export function outputItemImageGenerationCallFromJSON(
  jsonString: string,
): SafeParseResult<OutputItemImageGenerationCall, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OutputItemImageGenerationCall$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OutputItemImageGenerationCall' from JSON`,
  );
}
