/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 0c1828e72f98
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  ToolCallStatus,
  ToolCallStatus$inboundSchema,
  ToolCallStatus$outboundSchema,
} from "./toolcallstatus.js";

export const OutputDatetimeItemType = {
  OpenrouterDatetime: "openrouter:datetime",
} as const;
export type OutputDatetimeItemType = ClosedEnum<typeof OutputDatetimeItemType>;

/**
 * An openrouter:datetime server tool output item
 */
export type OutputDatetimeItem = {
  /**
   * ISO 8601 datetime string
   */
  datetime: string;
  id?: string | undefined;
  status: ToolCallStatus;
  /**
   * IANA timezone name
   */
  timezone: string;
  type: OutputDatetimeItemType;
};

/** @internal */
export const OutputDatetimeItemType$inboundSchema: z.ZodEnum<
  typeof OutputDatetimeItemType
> = z.enum(OutputDatetimeItemType);
/** @internal */
export const OutputDatetimeItemType$outboundSchema: z.ZodEnum<
  typeof OutputDatetimeItemType
> = OutputDatetimeItemType$inboundSchema;

/** @internal */
export const OutputDatetimeItem$inboundSchema: z.ZodType<
  OutputDatetimeItem,
  unknown
> = z.object({
  datetime: z.string(),
  id: z.string().optional(),
  status: ToolCallStatus$inboundSchema,
  timezone: z.string(),
  type: OutputDatetimeItemType$inboundSchema,
});
/** @internal */
export type OutputDatetimeItem$Outbound = {
  datetime: string;
  id?: string | undefined;
  status: string;
  timezone: string;
  type: string;
};

/** @internal */
export const OutputDatetimeItem$outboundSchema: z.ZodType<
  OutputDatetimeItem$Outbound,
  OutputDatetimeItem
> = z.object({
  datetime: z.string(),
  id: z.string().optional(),
  status: ToolCallStatus$outboundSchema,
  timezone: z.string(),
  type: OutputDatetimeItemType$outboundSchema,
});

export function outputDatetimeItemToJSON(
  outputDatetimeItem: OutputDatetimeItem,
): string {
  return JSON.stringify(
    OutputDatetimeItem$outboundSchema.parse(outputDatetimeItem),
  );
}
export function outputDatetimeItemFromJSON(
  jsonString: string,
): SafeParseResult<OutputDatetimeItem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OutputDatetimeItem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OutputDatetimeItem' from JSON`,
  );
}
