/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 6b2d2af692c7
 */

import * as z from "zod/v4";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const OutputModality = {
  Text: "text",
  Image: "image",
  Embeddings: "embeddings",
  Audio: "audio",
  Video: "video",
  Rerank: "rerank",
} as const;
export type OutputModality = OpenEnum<typeof OutputModality>;

/** @internal */
export const OutputModality$inboundSchema: z.ZodType<OutputModality, unknown> =
  openEnums.inboundSchema(OutputModality);
