/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4ea30f8ad34c
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  ReasoningFormat,
  ReasoningFormat$inboundSchema,
} from "./reasoningformat.js";
import {
  ReasoningSummaryText,
  ReasoningSummaryText$inboundSchema,
} from "./reasoningsummarytext.js";
import {
  ReasoningTextContent,
  ReasoningTextContent$inboundSchema,
} from "./reasoningtextcontent.js";

export const OutputReasoningItemStatusInProgress = {
  InProgress: "in_progress",
} as const;
export type OutputReasoningItemStatusInProgress = ClosedEnum<
  typeof OutputReasoningItemStatusInProgress
>;

export const OutputReasoningItemStatusIncomplete = {
  Incomplete: "incomplete",
} as const;
export type OutputReasoningItemStatusIncomplete = ClosedEnum<
  typeof OutputReasoningItemStatusIncomplete
>;

export const OutputReasoningItemStatusCompleted = {
  Completed: "completed",
} as const;
export type OutputReasoningItemStatusCompleted = ClosedEnum<
  typeof OutputReasoningItemStatusCompleted
>;

export type OutputReasoningItemStatusUnion =
  | OutputReasoningItemStatusCompleted
  | OutputReasoningItemStatusIncomplete
  | OutputReasoningItemStatusInProgress;

/**
 * An output item containing reasoning
 */
export type OutputReasoningItem = {
  content?: Array<ReasoningTextContent> | null | undefined;
  encryptedContent?: string | null | undefined;
  id: string;
  status?:
    | OutputReasoningItemStatusCompleted
    | OutputReasoningItemStatusIncomplete
    | OutputReasoningItemStatusInProgress
    | undefined;
  summary: Array<ReasoningSummaryText>;
  type: "reasoning";
  format?: ReasoningFormat | null | undefined;
  /**
   * A signature for the reasoning content, used for verification
   */
  signature?: string | null | undefined;
};

/** @internal */
export const OutputReasoningItemStatusInProgress$inboundSchema: z.ZodEnum<
  typeof OutputReasoningItemStatusInProgress
> = z.enum(OutputReasoningItemStatusInProgress);

/** @internal */
export const OutputReasoningItemStatusIncomplete$inboundSchema: z.ZodEnum<
  typeof OutputReasoningItemStatusIncomplete
> = z.enum(OutputReasoningItemStatusIncomplete);

/** @internal */
export const OutputReasoningItemStatusCompleted$inboundSchema: z.ZodEnum<
  typeof OutputReasoningItemStatusCompleted
> = z.enum(OutputReasoningItemStatusCompleted);

/** @internal */
export const OutputReasoningItemStatusUnion$inboundSchema: z.ZodType<
  OutputReasoningItemStatusUnion,
  unknown
> = z.union([
  OutputReasoningItemStatusCompleted$inboundSchema,
  OutputReasoningItemStatusIncomplete$inboundSchema,
  OutputReasoningItemStatusInProgress$inboundSchema,
]);

export function outputReasoningItemStatusUnionFromJSON(
  jsonString: string,
): SafeParseResult<OutputReasoningItemStatusUnion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OutputReasoningItemStatusUnion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OutputReasoningItemStatusUnion' from JSON`,
  );
}

/** @internal */
export const OutputReasoningItem$inboundSchema: z.ZodType<
  OutputReasoningItem,
  unknown
> = z.object({
  content: z.nullable(z.array(ReasoningTextContent$inboundSchema)).optional(),
  encrypted_content: z.nullable(z.string()).optional(),
  id: z.string(),
  status: z.union([
    OutputReasoningItemStatusCompleted$inboundSchema,
    OutputReasoningItemStatusIncomplete$inboundSchema,
    OutputReasoningItemStatusInProgress$inboundSchema,
  ]).optional(),
  summary: z.array(ReasoningSummaryText$inboundSchema),
  type: z.literal("reasoning"),
  format: z.nullable(ReasoningFormat$inboundSchema).optional(),
  signature: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "encrypted_content": "encryptedContent",
  });
});

export function outputReasoningItemFromJSON(
  jsonString: string,
): SafeParseResult<OutputReasoningItem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OutputReasoningItem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OutputReasoningItem' from JSON`,
  );
}
