/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 92114d9bad95
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  ToolCallStatus,
  ToolCallStatus$inboundSchema,
  ToolCallStatus$outboundSchema,
} from "./toolcallstatus.js";

export const OutputWebSearchServerToolItemType = {
  OpenrouterWebSearch: "openrouter:web_search",
} as const;
export type OutputWebSearchServerToolItemType = ClosedEnum<
  typeof OutputWebSearchServerToolItemType
>;

/**
 * An openrouter:web_search server tool output item
 */
export type OutputWebSearchServerToolItem = {
  id?: string | undefined;
  status: ToolCallStatus;
  type: OutputWebSearchServerToolItemType;
};

/** @internal */
export const OutputWebSearchServerToolItemType$inboundSchema: z.ZodEnum<
  typeof OutputWebSearchServerToolItemType
> = z.enum(OutputWebSearchServerToolItemType);
/** @internal */
export const OutputWebSearchServerToolItemType$outboundSchema: z.ZodEnum<
  typeof OutputWebSearchServerToolItemType
> = OutputWebSearchServerToolItemType$inboundSchema;

/** @internal */
export const OutputWebSearchServerToolItem$inboundSchema: z.ZodType<
  OutputWebSearchServerToolItem,
  unknown
> = z.object({
  id: z.string().optional(),
  status: ToolCallStatus$inboundSchema,
  type: OutputWebSearchServerToolItemType$inboundSchema,
});
/** @internal */
export type OutputWebSearchServerToolItem$Outbound = {
  id?: string | undefined;
  status: string;
  type: string;
};

/** @internal */
export const OutputWebSearchServerToolItem$outboundSchema: z.ZodType<
  OutputWebSearchServerToolItem$Outbound,
  OutputWebSearchServerToolItem
> = z.object({
  id: z.string().optional(),
  status: ToolCallStatus$outboundSchema,
  type: OutputWebSearchServerToolItemType$outboundSchema,
});

export function outputWebSearchServerToolItemToJSON(
  outputWebSearchServerToolItem: OutputWebSearchServerToolItem,
): string {
  return JSON.stringify(
    OutputWebSearchServerToolItem$outboundSchema.parse(
      outputWebSearchServerToolItem,
    ),
  );
}
export function outputWebSearchServerToolItemFromJSON(
  jsonString: string,
): SafeParseResult<OutputWebSearchServerToolItem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OutputWebSearchServerToolItem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OutputWebSearchServerToolItem' from JSON`,
  );
}
