/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: ab5ef16080c7
 */

import * as z from "zod/v4";

/**
 * Percentile-based latency cutoffs. All specified cutoffs must be met for an endpoint to be preferred.
 */
export type PercentileLatencyCutoffs = {
  /**
   * Maximum p50 latency (seconds)
   */
  p50?: number | undefined;
  /**
   * Maximum p75 latency (seconds)
   */
  p75?: number | undefined;
  /**
   * Maximum p90 latency (seconds)
   */
  p90?: number | undefined;
  /**
   * Maximum p99 latency (seconds)
   */
  p99?: number | undefined;
};

/** @internal */
export type PercentileLatencyCutoffs$Outbound = {
  p50?: number | undefined;
  p75?: number | undefined;
  p90?: number | undefined;
  p99?: number | undefined;
};

/** @internal */
export const PercentileLatencyCutoffs$outboundSchema: z.ZodType<
  PercentileLatencyCutoffs$Outbound,
  PercentileLatencyCutoffs
> = z.object({
  p50: z.number().optional(),
  p75: z.number().optional(),
  p90: z.number().optional(),
  p99: z.number().optional(),
});

export function percentileLatencyCutoffsToJSON(
  percentileLatencyCutoffs: PercentileLatencyCutoffs,
): string {
  return JSON.stringify(
    PercentileLatencyCutoffs$outboundSchema.parse(percentileLatencyCutoffs),
  );
}
