/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 2b2b6cf6a019
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Per-request token limits
 */
export type PerRequestLimits = {
  /**
   * Maximum completion tokens per request
   */
  completionTokens: number;
  /**
   * Maximum prompt tokens per request
   */
  promptTokens: number;
};

/** @internal */
export const PerRequestLimits$inboundSchema: z.ZodType<
  PerRequestLimits,
  unknown
> = z.object({
  completion_tokens: z.number(),
  prompt_tokens: z.number(),
}).transform((v) => {
  return remap$(v, {
    "completion_tokens": "completionTokens",
    "prompt_tokens": "promptTokens",
  });
});

export function perRequestLimitsFromJSON(
  jsonString: string,
): SafeParseResult<PerRequestLimits, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PerRequestLimits$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PerRequestLimits' from JSON`,
  );
}
