/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 6b7147491ff2
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  PreviewWebSearchUserLocation,
  PreviewWebSearchUserLocation$inboundSchema,
  PreviewWebSearchUserLocation$Outbound,
  PreviewWebSearchUserLocation$outboundSchema,
} from "./previewwebsearchuserlocation.js";
import {
  SearchContextSizeEnum,
  SearchContextSizeEnum$inboundSchema,
  SearchContextSizeEnum$outboundSchema,
} from "./searchcontextsizeenum.js";
import {
  WebSearchDomainFilter,
  WebSearchDomainFilter$inboundSchema,
  WebSearchDomainFilter$Outbound,
  WebSearchDomainFilter$outboundSchema,
} from "./websearchdomainfilter.js";
import {
  WebSearchEngineEnum,
  WebSearchEngineEnum$inboundSchema,
  WebSearchEngineEnum$outboundSchema,
} from "./websearchengineenum.js";

/**
 * Web search preview tool configuration
 */
export type PreviewWebSearchServerTool = {
  /**
   * Which search engine to use. "auto" (default) uses native if the provider supports it, otherwise Exa. "native" forces the provider's built-in search. "exa" forces the Exa search API. "firecrawl" uses Firecrawl (requires BYOK). "parallel" uses the Parallel search API.
   */
  engine?: WebSearchEngineEnum | undefined;
  filters?: WebSearchDomainFilter | null | undefined;
  /**
   * Maximum number of search results to return per search call. Defaults to 5. Applies to Exa, Firecrawl, and Parallel engines; ignored with native provider search.
   */
  maxResults?: number | undefined;
  /**
   * Size of the search context for web search tools
   */
  searchContextSize?: SearchContextSizeEnum | undefined;
  type: "web_search_preview";
  userLocation?: PreviewWebSearchUserLocation | null | undefined;
};

/** @internal */
export const PreviewWebSearchServerTool$inboundSchema: z.ZodType<
  PreviewWebSearchServerTool,
  unknown
> = z.object({
  engine: WebSearchEngineEnum$inboundSchema.optional(),
  filters: z.nullable(WebSearchDomainFilter$inboundSchema).optional(),
  max_results: z.int().optional(),
  search_context_size: SearchContextSizeEnum$inboundSchema.optional(),
  type: z.literal("web_search_preview"),
  user_location: z.nullable(PreviewWebSearchUserLocation$inboundSchema)
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "max_results": "maxResults",
    "search_context_size": "searchContextSize",
    "user_location": "userLocation",
  });
});
/** @internal */
export type PreviewWebSearchServerTool$Outbound = {
  engine?: string | undefined;
  filters?: WebSearchDomainFilter$Outbound | null | undefined;
  max_results?: number | undefined;
  search_context_size?: string | undefined;
  type: "web_search_preview";
  user_location?: PreviewWebSearchUserLocation$Outbound | null | undefined;
};

/** @internal */
export const PreviewWebSearchServerTool$outboundSchema: z.ZodType<
  PreviewWebSearchServerTool$Outbound,
  PreviewWebSearchServerTool
> = z.object({
  engine: WebSearchEngineEnum$outboundSchema.optional(),
  filters: z.nullable(WebSearchDomainFilter$outboundSchema).optional(),
  maxResults: z.int().optional(),
  searchContextSize: SearchContextSizeEnum$outboundSchema.optional(),
  type: z.literal("web_search_preview"),
  userLocation: z.nullable(PreviewWebSearchUserLocation$outboundSchema)
    .optional(),
}).transform((v) => {
  return remap$(v, {
    maxResults: "max_results",
    searchContextSize: "search_context_size",
    userLocation: "user_location",
  });
});

export function previewWebSearchServerToolToJSON(
  previewWebSearchServerTool: PreviewWebSearchServerTool,
): string {
  return JSON.stringify(
    PreviewWebSearchServerTool$outboundSchema.parse(previewWebSearchServerTool),
  );
}
export function previewWebSearchServerToolFromJSON(
  jsonString: string,
): SafeParseResult<PreviewWebSearchServerTool, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PreviewWebSearchServerTool$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PreviewWebSearchServerTool' from JSON`,
  );
}
