/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 64db0edfc37d
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const PreviewWebSearchUserLocationType = {
  Approximate: "approximate",
} as const;
export type PreviewWebSearchUserLocationType = ClosedEnum<
  typeof PreviewWebSearchUserLocationType
>;

export type PreviewWebSearchUserLocation = {
  city?: string | null | undefined;
  country?: string | null | undefined;
  region?: string | null | undefined;
  timezone?: string | null | undefined;
  type: PreviewWebSearchUserLocationType;
};

/** @internal */
export const PreviewWebSearchUserLocationType$inboundSchema: z.ZodEnum<
  typeof PreviewWebSearchUserLocationType
> = z.enum(PreviewWebSearchUserLocationType);
/** @internal */
export const PreviewWebSearchUserLocationType$outboundSchema: z.ZodEnum<
  typeof PreviewWebSearchUserLocationType
> = PreviewWebSearchUserLocationType$inboundSchema;

/** @internal */
export const PreviewWebSearchUserLocation$inboundSchema: z.ZodType<
  PreviewWebSearchUserLocation,
  unknown
> = z.object({
  city: z.nullable(z.string()).optional(),
  country: z.nullable(z.string()).optional(),
  region: z.nullable(z.string()).optional(),
  timezone: z.nullable(z.string()).optional(),
  type: PreviewWebSearchUserLocationType$inboundSchema,
});
/** @internal */
export type PreviewWebSearchUserLocation$Outbound = {
  city?: string | null | undefined;
  country?: string | null | undefined;
  region?: string | null | undefined;
  timezone?: string | null | undefined;
  type: string;
};

/** @internal */
export const PreviewWebSearchUserLocation$outboundSchema: z.ZodType<
  PreviewWebSearchUserLocation$Outbound,
  PreviewWebSearchUserLocation
> = z.object({
  city: z.nullable(z.string()).optional(),
  country: z.nullable(z.string()).optional(),
  region: z.nullable(z.string()).optional(),
  timezone: z.nullable(z.string()).optional(),
  type: PreviewWebSearchUserLocationType$outboundSchema,
});

export function previewWebSearchUserLocationToJSON(
  previewWebSearchUserLocation: PreviewWebSearchUserLocation,
): string {
  return JSON.stringify(
    PreviewWebSearchUserLocation$outboundSchema.parse(
      previewWebSearchUserLocation,
    ),
  );
}
export function previewWebSearchUserLocationFromJSON(
  jsonString: string,
): SafeParseResult<PreviewWebSearchUserLocation, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PreviewWebSearchUserLocation$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PreviewWebSearchUserLocation' from JSON`,
  );
}
