/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 3a47295d7b91
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import {
  PreferredMaxLatency,
  PreferredMaxLatency$Outbound,
  PreferredMaxLatency$outboundSchema,
} from "./preferredmaxlatency.js";
import {
  PreferredMinThroughput,
  PreferredMinThroughput$Outbound,
  PreferredMinThroughput$outboundSchema,
} from "./preferredminthroughput.js";
import { ProviderName, ProviderName$outboundSchema } from "./providername.js";
import { ProviderSort, ProviderSort$outboundSchema } from "./providersort.js";
import {
  ProviderSortConfig,
  ProviderSortConfig$Outbound,
  ProviderSortConfig$outboundSchema,
} from "./providersortconfig.js";
import { Quantization, Quantization$outboundSchema } from "./quantization.js";

/**
 * Data collection setting. If no available model provider meets the requirement, your request will return an error.
 *
 * @remarks
 * - allow: (default) allow providers which store user data non-transiently and may train on it
 *
 * - deny: use only providers which do not collect user data.
 */
export const DataCollection = {
  Deny: "deny",
  Allow: "allow",
} as const;
/**
 * Data collection setting. If no available model provider meets the requirement, your request will return an error.
 *
 * @remarks
 * - allow: (default) allow providers which store user data non-transiently and may train on it
 *
 * - deny: use only providers which do not collect user data.
 */
export type DataCollection = OpenEnum<typeof DataCollection>;

export type Ignore = ProviderName | string;

/**
 * The object specifying the maximum price you want to pay for this request. USD price per million tokens, for prompt and completion.
 */
export type MaxPrice = {
  audio?: string | undefined;
  completion?: string | undefined;
  image?: string | undefined;
  /**
   * Price per million prompt tokens
   */
  prompt?: string | undefined;
  request?: string | undefined;
};

export type Only = ProviderName | string;

export type Order = ProviderName | string;

/**
 * The sorting strategy to use for this request, if "order" is not specified. When set, no load balancing is performed.
 */
export type Sort = ProviderSort | ProviderSortConfig | any;

/**
 * When multiple model providers are available, optionally indicate your routing preference.
 */
export type ProviderPreferences = {
  /**
   * Whether to allow backup providers to serve requests
   *
   * @remarks
   * - true: (default) when the primary provider (or your custom providers in "order") is unavailable, use the next best provider.
   * - false: use only the primary/custom provider, and return the upstream error if it's unavailable.
   */
  allowFallbacks?: boolean | null | undefined;
  /**
   * Data collection setting. If no available model provider meets the requirement, your request will return an error.
   *
   * @remarks
   * - allow: (default) allow providers which store user data non-transiently and may train on it
   *
   * - deny: use only providers which do not collect user data.
   */
  dataCollection?: DataCollection | null | undefined;
  /**
   * Whether to restrict routing to only models that allow text distillation. When true, only models where the author has allowed distillation will be used.
   */
  enforceDistillableText?: boolean | null | undefined;
  /**
   * List of provider slugs to ignore. If provided, this list is merged with your account-wide ignored provider settings for this request.
   */
  ignore?: Array<ProviderName | string> | null | undefined;
  /**
   * The object specifying the maximum price you want to pay for this request. USD price per million tokens, for prompt and completion.
   */
  maxPrice?: MaxPrice | undefined;
  /**
   * List of provider slugs to allow. If provided, this list is merged with your account-wide allowed provider settings for this request.
   */
  only?: Array<ProviderName | string> | null | undefined;
  /**
   * An ordered list of provider slugs. The router will attempt to use the first provider in the subset of this list that supports your requested model, and fall back to the next if it is unavailable. If no providers are available, the request will fail with an error message.
   */
  order?: Array<ProviderName | string> | null | undefined;
  /**
   * Preferred maximum latency (in seconds). Can be a number (applies to p50) or an object with percentile-specific cutoffs. Endpoints above the threshold(s) may still be used, but are deprioritized in routing. When using fallback models, this may cause a fallback model to be used instead of the primary model if it meets the threshold.
   */
  preferredMaxLatency?: PreferredMaxLatency | null | undefined;
  /**
   * Preferred minimum throughput (in tokens per second). Can be a number (applies to p50) or an object with percentile-specific cutoffs. Endpoints below the threshold(s) may still be used, but are deprioritized in routing. When using fallback models, this may cause a fallback model to be used instead of the primary model if it meets the threshold.
   */
  preferredMinThroughput?: PreferredMinThroughput | null | undefined;
  /**
   * A list of quantization levels to filter the provider by.
   */
  quantizations?: Array<Quantization> | null | undefined;
  /**
   * Whether to filter providers to only those that support the parameters you've provided. If this setting is omitted or set to false, then providers will receive only the parameters they support, and ignore the rest.
   */
  requireParameters?: boolean | null | undefined;
  /**
   * The sorting strategy to use for this request, if "order" is not specified. When set, no load balancing is performed.
   */
  sort?: ProviderSort | ProviderSortConfig | any | null | undefined;
  /**
   * Whether to restrict routing to only ZDR (Zero Data Retention) endpoints. When true, only endpoints that do not retain prompts will be used.
   */
  zdr?: boolean | null | undefined;
};

/** @internal */
export const DataCollection$outboundSchema: z.ZodType<string, DataCollection> =
  openEnums.outboundSchema(DataCollection);

/** @internal */
export type Ignore$Outbound = string | string;

/** @internal */
export const Ignore$outboundSchema: z.ZodType<Ignore$Outbound, Ignore> = z
  .union([ProviderName$outboundSchema, z.string()]);

export function ignoreToJSON(ignore: Ignore): string {
  return JSON.stringify(Ignore$outboundSchema.parse(ignore));
}

/** @internal */
export type MaxPrice$Outbound = {
  audio?: string | undefined;
  completion?: string | undefined;
  image?: string | undefined;
  prompt?: string | undefined;
  request?: string | undefined;
};

/** @internal */
export const MaxPrice$outboundSchema: z.ZodType<MaxPrice$Outbound, MaxPrice> = z
  .object({
    audio: z.string().optional(),
    completion: z.string().optional(),
    image: z.string().optional(),
    prompt: z.string().optional(),
    request: z.string().optional(),
  });

export function maxPriceToJSON(maxPrice: MaxPrice): string {
  return JSON.stringify(MaxPrice$outboundSchema.parse(maxPrice));
}

/** @internal */
export type Only$Outbound = string | string;

/** @internal */
export const Only$outboundSchema: z.ZodType<Only$Outbound, Only> = z.union([
  ProviderName$outboundSchema,
  z.string(),
]);

export function onlyToJSON(only: Only): string {
  return JSON.stringify(Only$outboundSchema.parse(only));
}

/** @internal */
export type Order$Outbound = string | string;

/** @internal */
export const Order$outboundSchema: z.ZodType<Order$Outbound, Order> = z.union([
  ProviderName$outboundSchema,
  z.string(),
]);

export function orderToJSON(order: Order): string {
  return JSON.stringify(Order$outboundSchema.parse(order));
}

/** @internal */
export type Sort$Outbound = string | ProviderSortConfig$Outbound | any;

/** @internal */
export const Sort$outboundSchema: z.ZodType<Sort$Outbound, Sort> = z.union([
  ProviderSort$outboundSchema,
  ProviderSortConfig$outboundSchema,
  z.any(),
]);

export function sortToJSON(sort: Sort): string {
  return JSON.stringify(Sort$outboundSchema.parse(sort));
}

/** @internal */
export type ProviderPreferences$Outbound = {
  allow_fallbacks?: boolean | null | undefined;
  data_collection?: string | null | undefined;
  enforce_distillable_text?: boolean | null | undefined;
  ignore?: Array<string | string> | null | undefined;
  max_price?: MaxPrice$Outbound | undefined;
  only?: Array<string | string> | null | undefined;
  order?: Array<string | string> | null | undefined;
  preferred_max_latency?: PreferredMaxLatency$Outbound | null | undefined;
  preferred_min_throughput?: PreferredMinThroughput$Outbound | null | undefined;
  quantizations?: Array<string> | null | undefined;
  require_parameters?: boolean | null | undefined;
  sort?: string | ProviderSortConfig$Outbound | any | null | undefined;
  zdr?: boolean | null | undefined;
};

/** @internal */
export const ProviderPreferences$outboundSchema: z.ZodType<
  ProviderPreferences$Outbound,
  ProviderPreferences
> = z.object({
  allowFallbacks: z.nullable(z.boolean()).optional(),
  dataCollection: z.nullable(DataCollection$outboundSchema).optional(),
  enforceDistillableText: z.nullable(z.boolean()).optional(),
  ignore: z.nullable(
    z.array(z.union([ProviderName$outboundSchema, z.string()])),
  ).optional(),
  maxPrice: z.lazy(() => MaxPrice$outboundSchema).optional(),
  only: z.nullable(z.array(z.union([ProviderName$outboundSchema, z.string()])))
    .optional(),
  order: z.nullable(z.array(z.union([ProviderName$outboundSchema, z.string()])))
    .optional(),
  preferredMaxLatency: z.nullable(PreferredMaxLatency$outboundSchema)
    .optional(),
  preferredMinThroughput: z.nullable(PreferredMinThroughput$outboundSchema)
    .optional(),
  quantizations: z.nullable(z.array(Quantization$outboundSchema)).optional(),
  requireParameters: z.nullable(z.boolean()).optional(),
  sort: z.nullable(
    z.union([
      ProviderSort$outboundSchema,
      ProviderSortConfig$outboundSchema,
      z.any(),
    ]),
  ).optional(),
  zdr: z.nullable(z.boolean()).optional(),
}).transform((v) => {
  return remap$(v, {
    allowFallbacks: "allow_fallbacks",
    dataCollection: "data_collection",
    enforceDistillableText: "enforce_distillable_text",
    maxPrice: "max_price",
    preferredMaxLatency: "preferred_max_latency",
    preferredMinThroughput: "preferred_min_throughput",
    requireParameters: "require_parameters",
  });
});

export function providerPreferencesToJSON(
  providerPreferences: ProviderPreferences,
): string {
  return JSON.stringify(
    ProviderPreferences$outboundSchema.parse(providerPreferences),
  );
}
