/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a224fd99cdb5
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import * as discriminatedUnionTypes from "../types/discriminatedUnion.js";
import { discriminatedUnion } from "../types/discriminatedUnion.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  ReasoningDetailEncrypted,
  ReasoningDetailEncrypted$inboundSchema,
  ReasoningDetailEncrypted$Outbound,
  ReasoningDetailEncrypted$outboundSchema,
} from "./reasoningdetailencrypted.js";
import {
  ReasoningDetailSummary,
  ReasoningDetailSummary$inboundSchema,
  ReasoningDetailSummary$Outbound,
  ReasoningDetailSummary$outboundSchema,
} from "./reasoningdetailsummary.js";
import {
  ReasoningDetailText,
  ReasoningDetailText$inboundSchema,
  ReasoningDetailText$Outbound,
  ReasoningDetailText$outboundSchema,
} from "./reasoningdetailtext.js";

/**
 * Reasoning detail union schema
 */
export type ReasoningDetailUnion =
  | ReasoningDetailEncrypted
  | ReasoningDetailSummary
  | ReasoningDetailText
  | discriminatedUnionTypes.Unknown<"type">;

/** @internal */
export const ReasoningDetailUnion$inboundSchema: z.ZodType<
  ReasoningDetailUnion,
  unknown
> = discriminatedUnion("type", {
  ["reasoning.encrypted"]: ReasoningDetailEncrypted$inboundSchema,
  ["reasoning.summary"]: ReasoningDetailSummary$inboundSchema,
  ["reasoning.text"]: ReasoningDetailText$inboundSchema,
});
/** @internal */
export type ReasoningDetailUnion$Outbound =
  | ReasoningDetailEncrypted$Outbound
  | ReasoningDetailSummary$Outbound
  | ReasoningDetailText$Outbound;

/** @internal */
export const ReasoningDetailUnion$outboundSchema: z.ZodType<
  ReasoningDetailUnion$Outbound,
  ReasoningDetailUnion
> = z.union([
  ReasoningDetailEncrypted$outboundSchema,
  ReasoningDetailSummary$outboundSchema,
  ReasoningDetailText$outboundSchema,
]);

export function reasoningDetailUnionToJSON(
  reasoningDetailUnion: ReasoningDetailUnion,
): string {
  return JSON.stringify(
    ReasoningDetailUnion$outboundSchema.parse(reasoningDetailUnion),
  );
}
export function reasoningDetailUnionFromJSON(
  jsonString: string,
): SafeParseResult<ReasoningDetailUnion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ReasoningDetailUnion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ReasoningDetailUnion' from JSON`,
  );
}
