/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e5520210e3cb
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const ReasoningTextContentType = {
  ReasoningText: "reasoning_text",
} as const;
export type ReasoningTextContentType = ClosedEnum<
  typeof ReasoningTextContentType
>;

export type ReasoningTextContent = {
  text: string;
  type: ReasoningTextContentType;
};

/** @internal */
export const ReasoningTextContentType$inboundSchema: z.ZodEnum<
  typeof ReasoningTextContentType
> = z.enum(ReasoningTextContentType);
/** @internal */
export const ReasoningTextContentType$outboundSchema: z.ZodEnum<
  typeof ReasoningTextContentType
> = ReasoningTextContentType$inboundSchema;

/** @internal */
export const ReasoningTextContent$inboundSchema: z.ZodType<
  ReasoningTextContent,
  unknown
> = z.object({
  text: z.string(),
  type: ReasoningTextContentType$inboundSchema,
});
/** @internal */
export type ReasoningTextContent$Outbound = {
  text: string;
  type: string;
};

/** @internal */
export const ReasoningTextContent$outboundSchema: z.ZodType<
  ReasoningTextContent$Outbound,
  ReasoningTextContent
> = z.object({
  text: z.string(),
  type: ReasoningTextContentType$outboundSchema,
});

export function reasoningTextContentToJSON(
  reasoningTextContent: ReasoningTextContent,
): string {
  return JSON.stringify(
    ReasoningTextContent$outboundSchema.parse(reasoningTextContent),
  );
}
export function reasoningTextContentFromJSON(
  jsonString: string,
): SafeParseResult<ReasoningTextContent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ReasoningTextContent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ReasoningTextContent' from JSON`,
  );
}
