/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 347a000c48b1
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";
import {
  ReasoningFormat,
  ReasoningFormat$outboundSchema,
} from "./reasoningformat.js";
import {
  ReasoningSummaryText,
  ReasoningSummaryText$Outbound,
  ReasoningSummaryText$outboundSchema,
} from "./reasoningsummarytext.js";
import {
  ReasoningTextContent,
  ReasoningTextContent$Outbound,
  ReasoningTextContent$outboundSchema,
} from "./reasoningtextcontent.js";

export const ReasoningItemStatusInProgress = {
  InProgress: "in_progress",
} as const;
export type ReasoningItemStatusInProgress = ClosedEnum<
  typeof ReasoningItemStatusInProgress
>;

export const ReasoningItemStatusIncomplete = {
  Incomplete: "incomplete",
} as const;
export type ReasoningItemStatusIncomplete = ClosedEnum<
  typeof ReasoningItemStatusIncomplete
>;

export const ReasoningItemStatusCompleted = {
  Completed: "completed",
} as const;
export type ReasoningItemStatusCompleted = ClosedEnum<
  typeof ReasoningItemStatusCompleted
>;

export type ReasoningItemStatusUnion =
  | ReasoningItemStatusCompleted
  | ReasoningItemStatusIncomplete
  | ReasoningItemStatusInProgress;

export const ReasoningItemType = {
  Reasoning: "reasoning",
} as const;
export type ReasoningItemType = ClosedEnum<typeof ReasoningItemType>;

/**
 * Reasoning output item with signature and format extensions
 */
export type ReasoningItem = {
  content?: Array<ReasoningTextContent> | null | undefined;
  encryptedContent?: string | null | undefined;
  id: string;
  status?:
    | ReasoningItemStatusCompleted
    | ReasoningItemStatusIncomplete
    | ReasoningItemStatusInProgress
    | undefined;
  summary: Array<ReasoningSummaryText>;
  type: ReasoningItemType;
  format?: ReasoningFormat | null | undefined;
  signature?: string | null | undefined;
};

/** @internal */
export const ReasoningItemStatusInProgress$outboundSchema: z.ZodEnum<
  typeof ReasoningItemStatusInProgress
> = z.enum(ReasoningItemStatusInProgress);

/** @internal */
export const ReasoningItemStatusIncomplete$outboundSchema: z.ZodEnum<
  typeof ReasoningItemStatusIncomplete
> = z.enum(ReasoningItemStatusIncomplete);

/** @internal */
export const ReasoningItemStatusCompleted$outboundSchema: z.ZodEnum<
  typeof ReasoningItemStatusCompleted
> = z.enum(ReasoningItemStatusCompleted);

/** @internal */
export type ReasoningItemStatusUnion$Outbound = string | string | string;

/** @internal */
export const ReasoningItemStatusUnion$outboundSchema: z.ZodType<
  ReasoningItemStatusUnion$Outbound,
  ReasoningItemStatusUnion
> = z.union([
  ReasoningItemStatusCompleted$outboundSchema,
  ReasoningItemStatusIncomplete$outboundSchema,
  ReasoningItemStatusInProgress$outboundSchema,
]);

export function reasoningItemStatusUnionToJSON(
  reasoningItemStatusUnion: ReasoningItemStatusUnion,
): string {
  return JSON.stringify(
    ReasoningItemStatusUnion$outboundSchema.parse(reasoningItemStatusUnion),
  );
}

/** @internal */
export const ReasoningItemType$outboundSchema: z.ZodEnum<
  typeof ReasoningItemType
> = z.enum(ReasoningItemType);

/** @internal */
export type ReasoningItem$Outbound = {
  content?: Array<ReasoningTextContent$Outbound> | null | undefined;
  encrypted_content?: string | null | undefined;
  id: string;
  status?: string | string | string | undefined;
  summary: Array<ReasoningSummaryText$Outbound>;
  type: string;
  format?: string | null | undefined;
  signature?: string | null | undefined;
};

/** @internal */
export const ReasoningItem$outboundSchema: z.ZodType<
  ReasoningItem$Outbound,
  ReasoningItem
> = z.object({
  content: z.nullable(z.array(ReasoningTextContent$outboundSchema)).optional(),
  encryptedContent: z.nullable(z.string()).optional(),
  id: z.string(),
  status: z.union([
    ReasoningItemStatusCompleted$outboundSchema,
    ReasoningItemStatusIncomplete$outboundSchema,
    ReasoningItemStatusInProgress$outboundSchema,
  ]).optional(),
  summary: z.array(ReasoningSummaryText$outboundSchema),
  type: ReasoningItemType$outboundSchema,
  format: z.nullable(ReasoningFormat$outboundSchema).optional(),
  signature: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    encryptedContent: "encrypted_content",
  });
});

export function reasoningItemToJSON(reasoningItem: ReasoningItem): string {
  return JSON.stringify(ReasoningItem$outboundSchema.parse(reasoningItem));
}
