/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: dd747014f9d3
 */

import * as z from "zod/v4";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const ReasoningEffort = {
  Xhigh: "xhigh",
  High: "high",
  Medium: "medium",
  Low: "low",
  Minimal: "minimal",
  None: "none",
} as const;
export type ReasoningEffort = OpenEnum<typeof ReasoningEffort>;

/** @internal */
export const ReasoningEffort$inboundSchema: z.ZodType<
  ReasoningEffort,
  unknown
> = openEnums.inboundSchema(ReasoningEffort);
/** @internal */
export const ReasoningEffort$outboundSchema: z.ZodType<
  string,
  ReasoningEffort
> = openEnums.outboundSchema(ReasoningEffort);
