/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: b523cf757168
 */

import * as z from "zod/v4";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const ReasoningFormat = {
  Unknown: "unknown",
  OpenaiResponsesV1: "openai-responses-v1",
  AzureOpenaiResponsesV1: "azure-openai-responses-v1",
  XaiResponsesV1: "xai-responses-v1",
  AnthropicClaudeV1: "anthropic-claude-v1",
  GoogleGeminiV1: "google-gemini-v1",
} as const;
export type ReasoningFormat = OpenEnum<typeof ReasoningFormat>;

/** @internal */
export const ReasoningFormat$inboundSchema: z.ZodType<
  ReasoningFormat,
  unknown
> = openEnums.inboundSchema(ReasoningFormat);
/** @internal */
export const ReasoningFormat$outboundSchema: z.ZodType<
  string,
  ReasoningFormat
> = openEnums.outboundSchema(ReasoningFormat);
