/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 9c06c18de6d6
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const ReasoningSummaryTextType = {
  SummaryText: "summary_text",
} as const;
export type ReasoningSummaryTextType = ClosedEnum<
  typeof ReasoningSummaryTextType
>;

export type ReasoningSummaryText = {
  text: string;
  type: ReasoningSummaryTextType;
};

/** @internal */
export const ReasoningSummaryTextType$inboundSchema: z.ZodEnum<
  typeof ReasoningSummaryTextType
> = z.enum(ReasoningSummaryTextType);
/** @internal */
export const ReasoningSummaryTextType$outboundSchema: z.ZodEnum<
  typeof ReasoningSummaryTextType
> = ReasoningSummaryTextType$inboundSchema;

/** @internal */
export const ReasoningSummaryText$inboundSchema: z.ZodType<
  ReasoningSummaryText,
  unknown
> = z.object({
  text: z.string(),
  type: ReasoningSummaryTextType$inboundSchema,
});
/** @internal */
export type ReasoningSummaryText$Outbound = {
  text: string;
  type: string;
};

/** @internal */
export const ReasoningSummaryText$outboundSchema: z.ZodType<
  ReasoningSummaryText$Outbound,
  ReasoningSummaryText
> = z.object({
  text: z.string(),
  type: ReasoningSummaryTextType$outboundSchema,
});

export function reasoningSummaryTextToJSON(
  reasoningSummaryText: ReasoningSummaryText,
): string {
  return JSON.stringify(
    ReasoningSummaryText$outboundSchema.parse(reasoningSummaryText),
  );
}
export function reasoningSummaryTextFromJSON(
  jsonString: string,
): SafeParseResult<ReasoningSummaryText, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ReasoningSummaryText$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ReasoningSummaryText' from JSON`,
  );
}
