/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 888dc7b3074b
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Event emitted when reasoning summary text delta is streamed
 */
export type ReasoningSummaryTextDeltaEvent = {
  delta: string;
  itemId: string;
  outputIndex: number;
  sequenceNumber: number;
  summaryIndex: number;
  type: "response.reasoning_summary_text.delta";
};

/** @internal */
export const ReasoningSummaryTextDeltaEvent$inboundSchema: z.ZodType<
  ReasoningSummaryTextDeltaEvent,
  unknown
> = z.object({
  delta: z.string(),
  item_id: z.string(),
  output_index: z.int(),
  sequence_number: z.int(),
  summary_index: z.int(),
  type: z.literal("response.reasoning_summary_text.delta"),
}).transform((v) => {
  return remap$(v, {
    "item_id": "itemId",
    "output_index": "outputIndex",
    "sequence_number": "sequenceNumber",
    "summary_index": "summaryIndex",
  });
});

export function reasoningSummaryTextDeltaEventFromJSON(
  jsonString: string,
): SafeParseResult<ReasoningSummaryTextDeltaEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ReasoningSummaryTextDeltaEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ReasoningSummaryTextDeltaEvent' from JSON`,
  );
}
