/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 8b6bd4c64a66
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  ReasoningFormat,
  ReasoningFormat$inboundSchema,
  ReasoningFormat$outboundSchema,
} from "./reasoningformat.js";

/**
 * Reasoning detail text schema
 */
export type ReasoningDetailText = {
  format?: ReasoningFormat | null | undefined;
  id?: string | null | undefined;
  index?: number | undefined;
  signature?: string | null | undefined;
  text?: string | null | undefined;
  type: "reasoning.text";
};

/** @internal */
export const ReasoningDetailText$inboundSchema: z.ZodType<
  ReasoningDetailText,
  unknown
> = z.object({
  format: z.nullable(ReasoningFormat$inboundSchema).optional(),
  id: z.nullable(z.string()).optional(),
  index: z.int().optional(),
  signature: z.nullable(z.string()).optional(),
  text: z.nullable(z.string()).optional(),
  type: z.literal("reasoning.text"),
});
/** @internal */
export type ReasoningDetailText$Outbound = {
  format?: string | null | undefined;
  id?: string | null | undefined;
  index?: number | undefined;
  signature?: string | null | undefined;
  text?: string | null | undefined;
  type: "reasoning.text";
};

/** @internal */
export const ReasoningDetailText$outboundSchema: z.ZodType<
  ReasoningDetailText$Outbound,
  ReasoningDetailText
> = z.object({
  format: z.nullable(ReasoningFormat$outboundSchema).optional(),
  id: z.nullable(z.string()).optional(),
  index: z.int().optional(),
  signature: z.nullable(z.string()).optional(),
  text: z.nullable(z.string()).optional(),
  type: z.literal("reasoning.text"),
});

export function reasoningDetailTextToJSON(
  reasoningDetailText: ReasoningDetailText,
): string {
  return JSON.stringify(
    ReasoningDetailText$outboundSchema.parse(reasoningDetailText),
  );
}
export function reasoningDetailTextFromJSON(
  jsonString: string,
): SafeParseResult<ReasoningDetailText, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ReasoningDetailText$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ReasoningDetailText' from JSON`,
  );
}
