/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: aca3bffec6c2
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  ReasoningSummaryText,
  ReasoningSummaryText$inboundSchema,
} from "./reasoningsummarytext.js";

/**
 * Event emitted when a reasoning summary part is added
 */
export type ReasoningSummaryPartAddedEvent = {
  itemId: string;
  outputIndex: number;
  part: ReasoningSummaryText;
  sequenceNumber: number;
  summaryIndex: number;
  type: "response.reasoning_summary_part.added";
};

/** @internal */
export const ReasoningSummaryPartAddedEvent$inboundSchema: z.ZodType<
  ReasoningSummaryPartAddedEvent,
  unknown
> = z.object({
  item_id: z.string(),
  output_index: z.int(),
  part: ReasoningSummaryText$inboundSchema,
  sequence_number: z.int(),
  summary_index: z.int(),
  type: z.literal("response.reasoning_summary_part.added"),
}).transform((v) => {
  return remap$(v, {
    "item_id": "itemId",
    "output_index": "outputIndex",
    "sequence_number": "sequenceNumber",
    "summary_index": "summaryIndex",
  });
});

export function reasoningSummaryPartAddedEventFromJSON(
  jsonString: string,
): SafeParseResult<ReasoningSummaryPartAddedEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ReasoningSummaryPartAddedEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ReasoningSummaryPartAddedEvent' from JSON`,
  );
}
