/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4945c757d284
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Event emitted when reasoning summary text streaming is complete
 */
export type ReasoningSummaryTextDoneEvent = {
  itemId: string;
  outputIndex: number;
  sequenceNumber: number;
  summaryIndex: number;
  text: string;
  type: "response.reasoning_summary_text.done";
};

/** @internal */
export const ReasoningSummaryTextDoneEvent$inboundSchema: z.ZodType<
  ReasoningSummaryTextDoneEvent,
  unknown
> = z.object({
  item_id: z.string(),
  output_index: z.int(),
  sequence_number: z.int(),
  summary_index: z.int(),
  text: z.string(),
  type: z.literal("response.reasoning_summary_text.done"),
}).transform((v) => {
  return remap$(v, {
    "item_id": "itemId",
    "output_index": "outputIndex",
    "sequence_number": "sequenceNumber",
    "summary_index": "summaryIndex",
  });
});

export function reasoningSummaryTextDoneEventFromJSON(
  jsonString: string,
): SafeParseResult<ReasoningSummaryTextDoneEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ReasoningSummaryTextDoneEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ReasoningSummaryTextDoneEvent' from JSON`,
  );
}
