/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 2d5e61e53c46
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  OpenAIResponsesAnnotation,
  OpenAIResponsesAnnotation$inboundSchema,
  OpenAIResponsesAnnotation$Outbound,
  OpenAIResponsesAnnotation$outboundSchema,
} from "./openairesponsesannotation.js";

export type ResponseOutputTextTopLogprob = {
  bytes: Array<number>;
  logprob: number;
  token: string;
};

export type Logprob = {
  bytes: Array<number>;
  logprob: number;
  token: string;
  topLogprobs: Array<ResponseOutputTextTopLogprob>;
};

export type ResponseOutputText = {
  annotations?: Array<OpenAIResponsesAnnotation> | undefined;
  logprobs?: Array<Logprob> | undefined;
  text: string;
  type: "output_text";
};

/** @internal */
export const ResponseOutputTextTopLogprob$inboundSchema: z.ZodType<
  ResponseOutputTextTopLogprob,
  unknown
> = z.object({
  bytes: z.array(z.int()),
  logprob: z.number(),
  token: z.string(),
});
/** @internal */
export type ResponseOutputTextTopLogprob$Outbound = {
  bytes: Array<number>;
  logprob: number;
  token: string;
};

/** @internal */
export const ResponseOutputTextTopLogprob$outboundSchema: z.ZodType<
  ResponseOutputTextTopLogprob$Outbound,
  ResponseOutputTextTopLogprob
> = z.object({
  bytes: z.array(z.int()),
  logprob: z.number(),
  token: z.string(),
});

export function responseOutputTextTopLogprobToJSON(
  responseOutputTextTopLogprob: ResponseOutputTextTopLogprob,
): string {
  return JSON.stringify(
    ResponseOutputTextTopLogprob$outboundSchema.parse(
      responseOutputTextTopLogprob,
    ),
  );
}
export function responseOutputTextTopLogprobFromJSON(
  jsonString: string,
): SafeParseResult<ResponseOutputTextTopLogprob, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResponseOutputTextTopLogprob$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResponseOutputTextTopLogprob' from JSON`,
  );
}

/** @internal */
export const Logprob$inboundSchema: z.ZodType<Logprob, unknown> = z.object({
  bytes: z.array(z.int()),
  logprob: z.number(),
  token: z.string(),
  top_logprobs: z.array(
    z.lazy(() => ResponseOutputTextTopLogprob$inboundSchema),
  ),
}).transform((v) => {
  return remap$(v, {
    "top_logprobs": "topLogprobs",
  });
});
/** @internal */
export type Logprob$Outbound = {
  bytes: Array<number>;
  logprob: number;
  token: string;
  top_logprobs: Array<ResponseOutputTextTopLogprob$Outbound>;
};

/** @internal */
export const Logprob$outboundSchema: z.ZodType<Logprob$Outbound, Logprob> = z
  .object({
    bytes: z.array(z.int()),
    logprob: z.number(),
    token: z.string(),
    topLogprobs: z.array(
      z.lazy(() => ResponseOutputTextTopLogprob$outboundSchema),
    ),
  }).transform((v) => {
    return remap$(v, {
      topLogprobs: "top_logprobs",
    });
  });

export function logprobToJSON(logprob: Logprob): string {
  return JSON.stringify(Logprob$outboundSchema.parse(logprob));
}
export function logprobFromJSON(
  jsonString: string,
): SafeParseResult<Logprob, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Logprob$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Logprob' from JSON`,
  );
}

/** @internal */
export const ResponseOutputText$inboundSchema: z.ZodType<
  ResponseOutputText,
  unknown
> = z.object({
  annotations: z.array(OpenAIResponsesAnnotation$inboundSchema).optional(),
  logprobs: z.array(z.lazy(() => Logprob$inboundSchema)).optional(),
  text: z.string(),
  type: z.literal("output_text"),
});
/** @internal */
export type ResponseOutputText$Outbound = {
  annotations?: Array<OpenAIResponsesAnnotation$Outbound> | undefined;
  logprobs?: Array<Logprob$Outbound> | undefined;
  text: string;
  type: "output_text";
};

/** @internal */
export const ResponseOutputText$outboundSchema: z.ZodType<
  ResponseOutputText$Outbound,
  ResponseOutputText
> = z.object({
  annotations: z.array(OpenAIResponsesAnnotation$outboundSchema).optional(),
  logprobs: z.array(z.lazy(() => Logprob$outboundSchema)).optional(),
  text: z.string(),
  type: z.literal("output_text"),
});

export function responseOutputTextToJSON(
  responseOutputText: ResponseOutputText,
): string {
  return JSON.stringify(
    ResponseOutputText$outboundSchema.parse(responseOutputText),
  );
}
export function responseOutputTextFromJSON(
  jsonString: string,
): SafeParseResult<ResponseOutputText, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResponseOutputText$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResponseOutputText' from JSON`,
  );
}
