/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 622c12ba88e2
 */

import * as z from "zod/v4";

export type ResponseHealingPlugin = {
  /**
   * Set to false to disable the response-healing plugin for this request. Defaults to true.
   */
  enabled?: boolean | undefined;
  id: "response-healing";
};

/** @internal */
export type ResponseHealingPlugin$Outbound = {
  enabled?: boolean | undefined;
  id: "response-healing";
};

/** @internal */
export const ResponseHealingPlugin$outboundSchema: z.ZodType<
  ResponseHealingPlugin$Outbound,
  ResponseHealingPlugin
> = z.object({
  enabled: z.boolean().optional(),
  id: z.literal("response-healing"),
});

export function responseHealingPluginToJSON(
  responseHealingPlugin: ResponseHealingPlugin,
): string {
  return JSON.stringify(
    ResponseHealingPlugin$outboundSchema.parse(responseHealingPlugin),
  );
}
