/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4aa1487f961f
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import * as discriminatedUnionTypes from "../types/discriminatedUnion.js";
import { discriminatedUnion } from "../types/discriminatedUnion.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  AnnotationAddedEvent,
  AnnotationAddedEvent$inboundSchema,
} from "./annotationaddedevent.js";
import {
  ContentPartAddedEvent,
  ContentPartAddedEvent$inboundSchema,
} from "./contentpartaddedevent.js";
import {
  ContentPartDoneEvent,
  ContentPartDoneEvent$inboundSchema,
} from "./contentpartdoneevent.js";
import { ErrorEvent, ErrorEvent$inboundSchema } from "./errorevent.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  FunctionCallArgsDeltaEvent,
  FunctionCallArgsDeltaEvent$inboundSchema,
} from "./functioncallargsdeltaevent.js";
import {
  FunctionCallArgsDoneEvent,
  FunctionCallArgsDoneEvent$inboundSchema,
} from "./functioncallargsdoneevent.js";
import {
  ImageGenCallCompletedEvent,
  ImageGenCallCompletedEvent$inboundSchema,
} from "./imagegencallcompletedevent.js";
import {
  ImageGenCallGeneratingEvent,
  ImageGenCallGeneratingEvent$inboundSchema,
} from "./imagegencallgeneratingevent.js";
import {
  ImageGenCallInProgressEvent,
  ImageGenCallInProgressEvent$inboundSchema,
} from "./imagegencallinprogressevent.js";
import {
  ImageGenCallPartialImageEvent,
  ImageGenCallPartialImageEvent$inboundSchema,
} from "./imagegencallpartialimageevent.js";
import {
  OpenResponsesCreatedEvent,
  OpenResponsesCreatedEvent$inboundSchema,
} from "./openresponsescreatedevent.js";
import {
  OpenResponsesInProgressEvent,
  OpenResponsesInProgressEvent$inboundSchema,
} from "./openresponsesinprogressevent.js";
import {
  ReasoningDeltaEvent,
  ReasoningDeltaEvent$inboundSchema,
} from "./reasoningdeltaevent.js";
import {
  ReasoningDoneEvent,
  ReasoningDoneEvent$inboundSchema,
} from "./reasoningdoneevent.js";
import {
  ReasoningSummaryPartAddedEvent,
  ReasoningSummaryPartAddedEvent$inboundSchema,
} from "./reasoningsummarypartaddedevent.js";
import {
  ReasoningSummaryPartDoneEvent,
  ReasoningSummaryPartDoneEvent$inboundSchema,
} from "./reasoningsummarypartdoneevent.js";
import {
  ReasoningSummaryTextDeltaEvent,
  ReasoningSummaryTextDeltaEvent$inboundSchema,
} from "./reasoningsummarytextdeltaevent.js";
import {
  ReasoningSummaryTextDoneEvent,
  ReasoningSummaryTextDoneEvent$inboundSchema,
} from "./reasoningsummarytextdoneevent.js";
import {
  RefusalDeltaEvent,
  RefusalDeltaEvent$inboundSchema,
} from "./refusaldeltaevent.js";
import {
  RefusalDoneEvent,
  RefusalDoneEvent$inboundSchema,
} from "./refusaldoneevent.js";
import {
  StreamEventsResponseCompleted,
  StreamEventsResponseCompleted$inboundSchema,
} from "./streameventsresponsecompleted.js";
import {
  StreamEventsResponseFailed,
  StreamEventsResponseFailed$inboundSchema,
} from "./streameventsresponsefailed.js";
import {
  StreamEventsResponseIncomplete,
  StreamEventsResponseIncomplete$inboundSchema,
} from "./streameventsresponseincomplete.js";
import {
  StreamEventsResponseOutputItemAdded,
  StreamEventsResponseOutputItemAdded$inboundSchema,
} from "./streameventsresponseoutputitemadded.js";
import {
  StreamEventsResponseOutputItemDone,
  StreamEventsResponseOutputItemDone$inboundSchema,
} from "./streameventsresponseoutputitemdone.js";
import {
  TextDeltaEvent,
  TextDeltaEvent$inboundSchema,
} from "./textdeltaevent.js";
import { TextDoneEvent, TextDoneEvent$inboundSchema } from "./textdoneevent.js";
import {
  WebSearchCallCompletedEvent,
  WebSearchCallCompletedEvent$inboundSchema,
} from "./websearchcallcompletedevent.js";
import {
  WebSearchCallInProgressEvent,
  WebSearchCallInProgressEvent$inboundSchema,
} from "./websearchcallinprogressevent.js";
import {
  WebSearchCallSearchingEvent,
  WebSearchCallSearchingEvent$inboundSchema,
} from "./websearchcallsearchingevent.js";

/**
 * Union of all possible event types emitted during response streaming
 */
export type StreamEvents =
  | ErrorEvent
  | StreamEventsResponseCompleted
  | ContentPartAddedEvent
  | ContentPartDoneEvent
  | OpenResponsesCreatedEvent
  | StreamEventsResponseFailed
  | FunctionCallArgsDeltaEvent
  | FunctionCallArgsDoneEvent
  | ImageGenCallCompletedEvent
  | ImageGenCallGeneratingEvent
  | ImageGenCallInProgressEvent
  | ImageGenCallPartialImageEvent
  | OpenResponsesInProgressEvent
  | StreamEventsResponseIncomplete
  | StreamEventsResponseOutputItemAdded
  | StreamEventsResponseOutputItemDone
  | AnnotationAddedEvent
  | TextDeltaEvent
  | TextDoneEvent
  | ReasoningSummaryPartAddedEvent
  | ReasoningSummaryPartDoneEvent
  | ReasoningSummaryTextDeltaEvent
  | ReasoningSummaryTextDoneEvent
  | ReasoningDeltaEvent
  | ReasoningDoneEvent
  | RefusalDeltaEvent
  | RefusalDoneEvent
  | WebSearchCallCompletedEvent
  | WebSearchCallInProgressEvent
  | WebSearchCallSearchingEvent
  | discriminatedUnionTypes.Unknown<"type">;

/** @internal */
export const StreamEvents$inboundSchema: z.ZodType<StreamEvents, unknown> =
  discriminatedUnion("type", {
    error: ErrorEvent$inboundSchema,
    ["response.completed"]: StreamEventsResponseCompleted$inboundSchema,
    ["response.content_part.added"]: ContentPartAddedEvent$inboundSchema,
    ["response.content_part.done"]: ContentPartDoneEvent$inboundSchema,
    ["response.created"]: OpenResponsesCreatedEvent$inboundSchema,
    ["response.failed"]: StreamEventsResponseFailed$inboundSchema,
    ["response.function_call_arguments.delta"]:
      FunctionCallArgsDeltaEvent$inboundSchema,
    ["response.function_call_arguments.done"]:
      FunctionCallArgsDoneEvent$inboundSchema,
    ["response.image_generation_call.completed"]:
      ImageGenCallCompletedEvent$inboundSchema,
    ["response.image_generation_call.generating"]:
      ImageGenCallGeneratingEvent$inboundSchema,
    ["response.image_generation_call.in_progress"]:
      ImageGenCallInProgressEvent$inboundSchema,
    ["response.image_generation_call.partial_image"]:
      ImageGenCallPartialImageEvent$inboundSchema,
    ["response.in_progress"]: OpenResponsesInProgressEvent$inboundSchema,
    ["response.incomplete"]: StreamEventsResponseIncomplete$inboundSchema,
    ["response.output_item.added"]:
      StreamEventsResponseOutputItemAdded$inboundSchema,
    ["response.output_item.done"]:
      StreamEventsResponseOutputItemDone$inboundSchema,
    ["response.output_text.annotation.added"]:
      AnnotationAddedEvent$inboundSchema,
    ["response.output_text.delta"]: TextDeltaEvent$inboundSchema,
    ["response.output_text.done"]: TextDoneEvent$inboundSchema,
    ["response.reasoning_summary_part.added"]:
      ReasoningSummaryPartAddedEvent$inboundSchema,
    ["response.reasoning_summary_part.done"]:
      ReasoningSummaryPartDoneEvent$inboundSchema,
    ["response.reasoning_summary_text.delta"]:
      ReasoningSummaryTextDeltaEvent$inboundSchema,
    ["response.reasoning_summary_text.done"]:
      ReasoningSummaryTextDoneEvent$inboundSchema,
    ["response.reasoning_text.delta"]: ReasoningDeltaEvent$inboundSchema,
    ["response.reasoning_text.done"]: ReasoningDoneEvent$inboundSchema,
    ["response.refusal.delta"]: RefusalDeltaEvent$inboundSchema,
    ["response.refusal.done"]: RefusalDoneEvent$inboundSchema,
    ["response.web_search_call.completed"]:
      WebSearchCallCompletedEvent$inboundSchema,
    ["response.web_search_call.in_progress"]:
      WebSearchCallInProgressEvent$inboundSchema,
    ["response.web_search_call.searching"]:
      WebSearchCallSearchingEvent$inboundSchema,
  });

export function streamEventsFromJSON(
  jsonString: string,
): SafeParseResult<StreamEvents, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => StreamEvents$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StreamEvents' from JSON`,
  );
}
