/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 16cdc9efe2b8
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { OutputItems, OutputItems$inboundSchema } from "./outputitems.js";

/**
 * Event emitted when a new output item is added to the response
 */
export type StreamEventsResponseOutputItemAdded = {
  /**
   * An output item from the response
   */
  item: OutputItems;
  outputIndex: number;
  sequenceNumber: number;
  type: "response.output_item.added";
};

/** @internal */
export const StreamEventsResponseOutputItemAdded$inboundSchema: z.ZodType<
  StreamEventsResponseOutputItemAdded,
  unknown
> = z.object({
  item: OutputItems$inboundSchema,
  output_index: z.int(),
  sequence_number: z.int(),
  type: z.literal("response.output_item.added"),
}).transform((v) => {
  return remap$(v, {
    "output_index": "outputIndex",
    "sequence_number": "sequenceNumber",
  });
});

export function streamEventsResponseOutputItemAddedFromJSON(
  jsonString: string,
): SafeParseResult<StreamEventsResponseOutputItemAdded, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      StreamEventsResponseOutputItemAdded$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StreamEventsResponseOutputItemAdded' from JSON`,
  );
}
