/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 3b88c304514b
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Alternative token with its log probability
 */
export type StreamLogprobTopLogprob = {
  bytes?: Array<number> | undefined;
  logprob?: number | undefined;
  token?: string | undefined;
};

/** @internal */
export const StreamLogprobTopLogprob$inboundSchema: z.ZodType<
  StreamLogprobTopLogprob,
  unknown
> = z.object({
  bytes: z.array(z.int()).optional(),
  logprob: z.number().optional(),
  token: z.string().optional(),
});

export function streamLogprobTopLogprobFromJSON(
  jsonString: string,
): SafeParseResult<StreamLogprobTopLogprob, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => StreamLogprobTopLogprob$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StreamLogprobTopLogprob' from JSON`,
  );
}
