/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: cef4030a60c2
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { OutputItems, OutputItems$inboundSchema } from "./outputitems.js";

/**
 * Event emitted when an output item is complete
 */
export type StreamEventsResponseOutputItemDone = {
  /**
   * An output item from the response
   */
  item: OutputItems;
  outputIndex: number;
  sequenceNumber: number;
  type: "response.output_item.done";
};

/** @internal */
export const StreamEventsResponseOutputItemDone$inboundSchema: z.ZodType<
  StreamEventsResponseOutputItemDone,
  unknown
> = z.object({
  item: OutputItems$inboundSchema,
  output_index: z.int(),
  sequence_number: z.int(),
  type: z.literal("response.output_item.done"),
}).transform((v) => {
  return remap$(v, {
    "output_index": "outputIndex",
    "sequence_number": "sequenceNumber",
  });
});

export function streamEventsResponseOutputItemDoneFromJSON(
  jsonString: string,
): SafeParseResult<StreamEventsResponseOutputItemDone, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      StreamEventsResponseOutputItemDone$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StreamEventsResponseOutputItemDone' from JSON`,
  );
}
