/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 63748aa9f88e
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  OpenResponsesResult,
  OpenResponsesResult$inboundSchema,
} from "./openresponsesresult.js";

/**
 * Event emitted when a response has failed
 */
export type StreamEventsResponseFailed = {
  /**
   * Complete non-streaming response from the Responses API
   */
  response: OpenResponsesResult;
  sequenceNumber: number;
  type: "response.failed";
};

/** @internal */
export const StreamEventsResponseFailed$inboundSchema: z.ZodType<
  StreamEventsResponseFailed,
  unknown
> = z.object({
  response: OpenResponsesResult$inboundSchema,
  sequence_number: z.int(),
  type: z.literal("response.failed"),
}).transform((v) => {
  return remap$(v, {
    "sequence_number": "sequenceNumber",
  });
});

export function streamEventsResponseFailedFromJSON(
  jsonString: string,
): SafeParseResult<StreamEventsResponseFailed, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => StreamEventsResponseFailed$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StreamEventsResponseFailed' from JSON`,
  );
}
