/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 82ee236509d6
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const ModeRequired = {
  Required: "required",
} as const;
export type ModeRequired = ClosedEnum<typeof ModeRequired>;

export const ModeAuto = {
  Auto: "auto",
} as const;
export type ModeAuto = ClosedEnum<typeof ModeAuto>;

export type Mode = ModeAuto | ModeRequired;

export const ToolChoiceAllowedType = {
  AllowedTools: "allowed_tools",
} as const;
export type ToolChoiceAllowedType = ClosedEnum<typeof ToolChoiceAllowedType>;

/**
 * Constrains the model to a pre-defined set of allowed tools
 */
export type ToolChoiceAllowed = {
  mode: ModeAuto | ModeRequired;
  tools: Array<{ [k: string]: any | null }>;
  type: ToolChoiceAllowedType;
};

/** @internal */
export const ModeRequired$inboundSchema: z.ZodEnum<typeof ModeRequired> = z
  .enum(ModeRequired);
/** @internal */
export const ModeRequired$outboundSchema: z.ZodEnum<typeof ModeRequired> =
  ModeRequired$inboundSchema;

/** @internal */
export const ModeAuto$inboundSchema: z.ZodEnum<typeof ModeAuto> = z.enum(
  ModeAuto,
);
/** @internal */
export const ModeAuto$outboundSchema: z.ZodEnum<typeof ModeAuto> =
  ModeAuto$inboundSchema;

/** @internal */
export const Mode$inboundSchema: z.ZodType<Mode, unknown> = z.union([
  ModeAuto$inboundSchema,
  ModeRequired$inboundSchema,
]);
/** @internal */
export type Mode$Outbound = string | string;

/** @internal */
export const Mode$outboundSchema: z.ZodType<Mode$Outbound, Mode> = z.union([
  ModeAuto$outboundSchema,
  ModeRequired$outboundSchema,
]);

export function modeToJSON(mode: Mode): string {
  return JSON.stringify(Mode$outboundSchema.parse(mode));
}
export function modeFromJSON(
  jsonString: string,
): SafeParseResult<Mode, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Mode$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Mode' from JSON`,
  );
}

/** @internal */
export const ToolChoiceAllowedType$inboundSchema: z.ZodEnum<
  typeof ToolChoiceAllowedType
> = z.enum(ToolChoiceAllowedType);
/** @internal */
export const ToolChoiceAllowedType$outboundSchema: z.ZodEnum<
  typeof ToolChoiceAllowedType
> = ToolChoiceAllowedType$inboundSchema;

/** @internal */
export const ToolChoiceAllowed$inboundSchema: z.ZodType<
  ToolChoiceAllowed,
  unknown
> = z.object({
  mode: z.union([ModeAuto$inboundSchema, ModeRequired$inboundSchema]),
  tools: z.array(z.record(z.string(), z.nullable(z.any()))),
  type: ToolChoiceAllowedType$inboundSchema,
});
/** @internal */
export type ToolChoiceAllowed$Outbound = {
  mode: string | string;
  tools: Array<{ [k: string]: any | null }>;
  type: string;
};

/** @internal */
export const ToolChoiceAllowed$outboundSchema: z.ZodType<
  ToolChoiceAllowed$Outbound,
  ToolChoiceAllowed
> = z.object({
  mode: z.union([ModeAuto$outboundSchema, ModeRequired$outboundSchema]),
  tools: z.array(z.record(z.string(), z.nullable(z.any()))),
  type: ToolChoiceAllowedType$outboundSchema,
});

export function toolChoiceAllowedToJSON(
  toolChoiceAllowed: ToolChoiceAllowed,
): string {
  return JSON.stringify(
    ToolChoiceAllowed$outboundSchema.parse(toolChoiceAllowed),
  );
}
export function toolChoiceAllowedFromJSON(
  jsonString: string,
): SafeParseResult<ToolChoiceAllowed, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ToolChoiceAllowed$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ToolChoiceAllowed' from JSON`,
  );
}
