/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 50ce6e8a7bcd
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";

/**
 * Metadata for observability and tracing. Known keys (trace_id, trace_name, span_name, generation_name, parent_span_id) have special handling. Additional keys are passed through as custom metadata to configured broadcast destinations.
 */
export type TraceConfig = {
  generationName?: string | undefined;
  parentSpanId?: string | undefined;
  spanName?: string | undefined;
  traceId?: string | undefined;
  traceName?: string | undefined;
  additionalProperties?: { [k: string]: any | null } | undefined;
};

/** @internal */
export type TraceConfig$Outbound = {
  generation_name?: string | undefined;
  parent_span_id?: string | undefined;
  span_name?: string | undefined;
  trace_id?: string | undefined;
  trace_name?: string | undefined;
  [additionalProperties: string]: unknown;
};

/** @internal */
export const TraceConfig$outboundSchema: z.ZodType<
  TraceConfig$Outbound,
  TraceConfig
> = z.object({
  generationName: z.string().optional(),
  parentSpanId: z.string().optional(),
  spanName: z.string().optional(),
  traceId: z.string().optional(),
  traceName: z.string().optional(),
  additionalProperties: z.record(z.string(), z.nullable(z.any())).optional(),
}).transform((v) => {
  return {
    ...v.additionalProperties,
    ...remap$(v, {
      generationName: "generation_name",
      parentSpanId: "parent_span_id",
      spanName: "span_name",
      traceId: "trace_id",
      traceName: "trace_name",
      additionalProperties: null,
    }),
  };
});

export function traceConfigToJSON(traceConfig: TraceConfig): string {
  return JSON.stringify(TraceConfig$outboundSchema.parse(traceConfig));
}
