/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: ccd6ecd62c64
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type URLCitation = {
  endIndex: number;
  startIndex: number;
  title: string;
  type: "url_citation";
  url: string;
};

/** @internal */
export const URLCitation$inboundSchema: z.ZodType<URLCitation, unknown> = z
  .object({
    end_index: z.int(),
    start_index: z.int(),
    title: z.string(),
    type: z.literal("url_citation"),
    url: z.string(),
  }).transform((v) => {
    return remap$(v, {
      "end_index": "endIndex",
      "start_index": "startIndex",
    });
  });
/** @internal */
export type URLCitation$Outbound = {
  end_index: number;
  start_index: number;
  title: string;
  type: "url_citation";
  url: string;
};

/** @internal */
export const URLCitation$outboundSchema: z.ZodType<
  URLCitation$Outbound,
  URLCitation
> = z.object({
  endIndex: z.int(),
  startIndex: z.int(),
  title: z.string(),
  type: z.literal("url_citation"),
  url: z.string(),
}).transform((v) => {
  return remap$(v, {
    endIndex: "end_index",
    startIndex: "start_index",
  });
});

export function urlCitationToJSON(urlCitation: URLCitation): string {
  return JSON.stringify(URLCitation$outboundSchema.parse(urlCitation));
}
export function urlCitationFromJSON(
  jsonString: string,
): SafeParseResult<URLCitation, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => URLCitation$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'URLCitation' from JSON`,
  );
}
