/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 7d556ab96faf
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type InputTokensDetails = {
  cachedTokens: number;
};

export type OutputTokensDetails = {
  reasoningTokens: number;
};

export type CostDetails = {
  upstreamInferenceCost?: number | undefined;
  upstreamInferenceInputCost: number;
  upstreamInferenceOutputCost: number;
};

/**
 * Token usage information for the response
 */
export type Usage = {
  inputTokens: number;
  inputTokensDetails: InputTokensDetails;
  outputTokens: number;
  outputTokensDetails: OutputTokensDetails;
  totalTokens: number;
  /**
   * Cost of the completion
   */
  cost?: number | undefined;
  costDetails?: CostDetails | undefined;
  /**
   * Whether a request was made using a Bring Your Own Key configuration
   */
  isByok?: boolean | undefined;
};

/** @internal */
export const InputTokensDetails$inboundSchema: z.ZodType<
  InputTokensDetails,
  unknown
> = z.object({
  cached_tokens: z.int(),
}).transform((v) => {
  return remap$(v, {
    "cached_tokens": "cachedTokens",
  });
});

export function inputTokensDetailsFromJSON(
  jsonString: string,
): SafeParseResult<InputTokensDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InputTokensDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InputTokensDetails' from JSON`,
  );
}

/** @internal */
export const OutputTokensDetails$inboundSchema: z.ZodType<
  OutputTokensDetails,
  unknown
> = z.object({
  reasoning_tokens: z.int(),
}).transform((v) => {
  return remap$(v, {
    "reasoning_tokens": "reasoningTokens",
  });
});

export function outputTokensDetailsFromJSON(
  jsonString: string,
): SafeParseResult<OutputTokensDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OutputTokensDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OutputTokensDetails' from JSON`,
  );
}

/** @internal */
export const CostDetails$inboundSchema: z.ZodType<CostDetails, unknown> = z
  .object({
    upstream_inference_cost: z.number().optional(),
    upstream_inference_input_cost: z.number(),
    upstream_inference_output_cost: z.number(),
  }).transform((v) => {
    return remap$(v, {
      "upstream_inference_cost": "upstreamInferenceCost",
      "upstream_inference_input_cost": "upstreamInferenceInputCost",
      "upstream_inference_output_cost": "upstreamInferenceOutputCost",
    });
  });

export function costDetailsFromJSON(
  jsonString: string,
): SafeParseResult<CostDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CostDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CostDetails' from JSON`,
  );
}

/** @internal */
export const Usage$inboundSchema: z.ZodType<Usage, unknown> = z.object({
  input_tokens: z.int(),
  input_tokens_details: z.lazy(() => InputTokensDetails$inboundSchema),
  output_tokens: z.int(),
  output_tokens_details: z.lazy(() => OutputTokensDetails$inboundSchema),
  total_tokens: z.int(),
  cost: z.number().optional(),
  cost_details: z.lazy(() => CostDetails$inboundSchema).optional(),
  is_byok: z.boolean().optional(),
}).transform((v) => {
  return remap$(v, {
    "input_tokens": "inputTokens",
    "input_tokens_details": "inputTokensDetails",
    "output_tokens": "outputTokens",
    "output_tokens_details": "outputTokensDetails",
    "total_tokens": "totalTokens",
    "cost_details": "costDetails",
    "is_byok": "isByok",
  });
});

export function usageFromJSON(
  jsonString: string,
): SafeParseResult<Usage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Usage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Usage' from JSON`,
  );
}
