/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 9a49f28f7c9c
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Usage and cost information for the video generation. Available once the job has completed.
 */
export type VideoGenerationUsage = {
  /**
   * The cost of the video generation in USD.
   */
  cost?: number | undefined;
  /**
   * Whether the request was made using a Bring Your Own Key configuration.
   */
  isByok?: boolean | undefined;
};

/** @internal */
export const VideoGenerationUsage$inboundSchema: z.ZodType<
  VideoGenerationUsage,
  unknown
> = z.object({
  cost: z.number().optional(),
  is_byok: z.boolean().optional(),
}).transform((v) => {
  return remap$(v, {
    "is_byok": "isByok",
  });
});

export function videoGenerationUsageFromJSON(
  jsonString: string,
): SafeParseResult<VideoGenerationUsage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VideoGenerationUsage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VideoGenerationUsage' from JSON`,
  );
}
