/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e72ea2e4c5b3
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import {
  ContentPartImage,
  ContentPartImage$Outbound,
  ContentPartImage$outboundSchema,
} from "./contentpartimage.js";

/**
 * Aspect ratio of the generated video
 */
export const AspectRatio = {
  OneHundredAndSixtyNine: "16:9",
  NineHundredAndSixteen: "9:16",
  Eleven: "1:1",
  FortyThree: "4:3",
  ThirtyFour: "3:4",
  TwoHundredAndNineteen: "21:9",
  NineHundredAndTwentyOne: "9:21",
} as const;
/**
 * Aspect ratio of the generated video
 */
export type AspectRatio = OpenEnum<typeof AspectRatio>;

/**
 * Provider-specific options keyed by provider slug. The options for the matched provider are spread into the upstream request body.
 */
export type Options = {
  oneai?: { [k: string]: any | null } | undefined;
  ai21?: { [k: string]: any | null } | undefined;
  aionLabs?: { [k: string]: any | null } | undefined;
  akashml?: { [k: string]: any | null } | undefined;
  alibaba?: { [k: string]: any | null } | undefined;
  amazonBedrock?: { [k: string]: any | null } | undefined;
  amazonNova?: { [k: string]: any | null } | undefined;
  ambient?: { [k: string]: any | null } | undefined;
  anthropic?: { [k: string]: any | null } | undefined;
  anyscale?: { [k: string]: any | null } | undefined;
  arceeAi?: { [k: string]: any | null } | undefined;
  atlasCloud?: { [k: string]: any | null } | undefined;
  atoma?: { [k: string]: any | null } | undefined;
  avian?: { [k: string]: any | null } | undefined;
  azure?: { [k: string]: any | null } | undefined;
  baseten?: { [k: string]: any | null } | undefined;
  blackForestLabs?: { [k: string]: any | null } | undefined;
  byteplus?: { [k: string]: any | null } | undefined;
  centml?: { [k: string]: any | null } | undefined;
  cerebras?: { [k: string]: any | null } | undefined;
  chutes?: { [k: string]: any | null } | undefined;
  cirrascale?: { [k: string]: any | null } | undefined;
  clarifai?: { [k: string]: any | null } | undefined;
  cloudflare?: { [k: string]: any | null } | undefined;
  cohere?: { [k: string]: any | null } | undefined;
  crofai?: { [k: string]: any | null } | undefined;
  crusoe?: { [k: string]: any | null } | undefined;
  deepinfra?: { [k: string]: any | null } | undefined;
  deepseek?: { [k: string]: any | null } | undefined;
  enfer?: { [k: string]: any | null } | undefined;
  fakeProvider?: { [k: string]: any | null } | undefined;
  featherless?: { [k: string]: any | null } | undefined;
  fireworks?: { [k: string]: any | null } | undefined;
  friendli?: { [k: string]: any | null } | undefined;
  gmicloud?: { [k: string]: any | null } | undefined;
  googleAiStudio?: { [k: string]: any | null } | undefined;
  googleVertex?: { [k: string]: any | null } | undefined;
  gopomelo?: { [k: string]: any | null } | undefined;
  groq?: { [k: string]: any | null } | undefined;
  huggingface?: { [k: string]: any | null } | undefined;
  hyperbolic?: { [k: string]: any | null } | undefined;
  hyperbolicQuantized?: { [k: string]: any | null } | undefined;
  inception?: { [k: string]: any | null } | undefined;
  inceptron?: { [k: string]: any | null } | undefined;
  inferenceNet?: { [k: string]: any | null } | undefined;
  infermatic?: { [k: string]: any | null } | undefined;
  inflection?: { [k: string]: any | null } | undefined;
  inocloud?: { [k: string]: any | null } | undefined;
  ioNet?: { [k: string]: any | null } | undefined;
  ionstream?: { [k: string]: any | null } | undefined;
  klusterai?: { [k: string]: any | null } | undefined;
  lambda?: { [k: string]: any | null } | undefined;
  lepton?: { [k: string]: any | null } | undefined;
  liquid?: { [k: string]: any | null } | undefined;
  lynn?: { [k: string]: any | null } | undefined;
  lynnPrivate?: { [k: string]: any | null } | undefined;
  mancer?: { [k: string]: any | null } | undefined;
  mancerOld?: { [k: string]: any | null } | undefined;
  mara?: { [k: string]: any | null } | undefined;
  meta?: { [k: string]: any | null } | undefined;
  minimax?: { [k: string]: any | null } | undefined;
  mistral?: { [k: string]: any | null } | undefined;
  modal?: { [k: string]: any | null } | undefined;
  modelrun?: { [k: string]: any | null } | undefined;
  modular?: { [k: string]: any | null } | undefined;
  moonshotai?: { [k: string]: any | null } | undefined;
  morph?: { [k: string]: any | null } | undefined;
  ncompass?: { [k: string]: any | null } | undefined;
  nebius?: { [k: string]: any | null } | undefined;
  nextbit?: { [k: string]: any | null } | undefined;
  nineteen?: { [k: string]: any | null } | undefined;
  novita?: { [k: string]: any | null } | undefined;
  nvidia?: { [k: string]: any | null } | undefined;
  octoai?: { [k: string]: any | null } | undefined;
  openInference?: { [k: string]: any | null } | undefined;
  openai?: { [k: string]: any | null } | undefined;
  parasail?: { [k: string]: any | null } | undefined;
  perplexity?: { [k: string]: any | null } | undefined;
  phala?: { [k: string]: any | null } | undefined;
  recursal?: { [k: string]: any | null } | undefined;
  reflection?: { [k: string]: any | null } | undefined;
  reka?: { [k: string]: any | null } | undefined;
  relace?: { [k: string]: any | null } | undefined;
  replicate?: { [k: string]: any | null } | undefined;
  sambanova?: { [k: string]: any | null } | undefined;
  sambanovaCloaked?: { [k: string]: any | null } | undefined;
  seed?: { [k: string]: any | null } | undefined;
  sfCompute?: { [k: string]: any | null } | undefined;
  siliconflow?: { [k: string]: any | null } | undefined;
  sourceful?: { [k: string]: any | null } | undefined;
  stealth?: { [k: string]: any | null } | undefined;
  stepfun?: { [k: string]: any | null } | undefined;
  streamlake?: { [k: string]: any | null } | undefined;
  switchpoint?: { [k: string]: any | null } | undefined;
  targon?: { [k: string]: any | null } | undefined;
  together?: { [k: string]: any | null } | undefined;
  togetherLite?: { [k: string]: any | null } | undefined;
  ubicloud?: { [k: string]: any | null } | undefined;
  upstage?: { [k: string]: any | null } | undefined;
  venice?: { [k: string]: any | null } | undefined;
  wandb?: { [k: string]: any | null } | undefined;
  xai?: { [k: string]: any | null } | undefined;
  xiaomi?: { [k: string]: any | null } | undefined;
  zAi?: { [k: string]: any | null } | undefined;
};

/**
 * Provider-specific passthrough configuration
 */
export type Provider = {
  /**
   * Provider-specific options keyed by provider slug. The options for the matched provider are spread into the upstream request body.
   */
  options?: Options | undefined;
};

/**
 * Resolution of the generated video
 */
export const Resolution = {
  FourHundredAndEightyp: "480p",
  SevenHundredAndTwentyp: "720p",
  OneThousandAndEightyp: "1080p",
  OneK: "1K",
  TwoK: "2K",
  FourK: "4K",
} as const;
/**
 * Resolution of the generated video
 */
export type Resolution = OpenEnum<typeof Resolution>;

export type VideoGenerationRequest = {
  /**
   * Aspect ratio of the generated video
   */
  aspectRatio?: AspectRatio | undefined;
  /**
   * Duration of the generated video in seconds
   */
  duration?: number | undefined;
  /**
   * Whether to generate audio alongside the video. Defaults to true for models that support audio output, false otherwise.
   */
  generateAudio?: boolean | undefined;
  /**
   * Reference images to guide video generation
   */
  inputReferences?: Array<ContentPartImage> | undefined;
  model: string;
  prompt: string;
  /**
   * Provider-specific passthrough configuration
   */
  provider?: Provider | undefined;
  /**
   * Resolution of the generated video
   */
  resolution?: Resolution | undefined;
  /**
   * If specified, the generation will sample deterministically, such that repeated requests with the same seed and parameters should return the same result. Determinism is not guaranteed for all providers.
   */
  seed?: number | undefined;
  /**
   * Exact pixel dimensions of the generated video in "WIDTHxHEIGHT" format (e.g. "1280x720"). Interchangeable with resolution + aspect_ratio.
   */
  size?: string | undefined;
};

/** @internal */
export const AspectRatio$outboundSchema: z.ZodType<string, AspectRatio> =
  openEnums.outboundSchema(AspectRatio);

/** @internal */
export type Options$Outbound = {
  "01ai"?: { [k: string]: any | null } | undefined;
  ai21?: { [k: string]: any | null } | undefined;
  "aion-labs"?: { [k: string]: any | null } | undefined;
  akashml?: { [k: string]: any | null } | undefined;
  alibaba?: { [k: string]: any | null } | undefined;
  "amazon-bedrock"?: { [k: string]: any | null } | undefined;
  "amazon-nova"?: { [k: string]: any | null } | undefined;
  ambient?: { [k: string]: any | null } | undefined;
  anthropic?: { [k: string]: any | null } | undefined;
  anyscale?: { [k: string]: any | null } | undefined;
  "arcee-ai"?: { [k: string]: any | null } | undefined;
  "atlas-cloud"?: { [k: string]: any | null } | undefined;
  atoma?: { [k: string]: any | null } | undefined;
  avian?: { [k: string]: any | null } | undefined;
  azure?: { [k: string]: any | null } | undefined;
  baseten?: { [k: string]: any | null } | undefined;
  "black-forest-labs"?: { [k: string]: any | null } | undefined;
  byteplus?: { [k: string]: any | null } | undefined;
  centml?: { [k: string]: any | null } | undefined;
  cerebras?: { [k: string]: any | null } | undefined;
  chutes?: { [k: string]: any | null } | undefined;
  cirrascale?: { [k: string]: any | null } | undefined;
  clarifai?: { [k: string]: any | null } | undefined;
  cloudflare?: { [k: string]: any | null } | undefined;
  cohere?: { [k: string]: any | null } | undefined;
  crofai?: { [k: string]: any | null } | undefined;
  crusoe?: { [k: string]: any | null } | undefined;
  deepinfra?: { [k: string]: any | null } | undefined;
  deepseek?: { [k: string]: any | null } | undefined;
  enfer?: { [k: string]: any | null } | undefined;
  "fake-provider"?: { [k: string]: any | null } | undefined;
  featherless?: { [k: string]: any | null } | undefined;
  fireworks?: { [k: string]: any | null } | undefined;
  friendli?: { [k: string]: any | null } | undefined;
  gmicloud?: { [k: string]: any | null } | undefined;
  "google-ai-studio"?: { [k: string]: any | null } | undefined;
  "google-vertex"?: { [k: string]: any | null } | undefined;
  gopomelo?: { [k: string]: any | null } | undefined;
  groq?: { [k: string]: any | null } | undefined;
  huggingface?: { [k: string]: any | null } | undefined;
  hyperbolic?: { [k: string]: any | null } | undefined;
  "hyperbolic-quantized"?: { [k: string]: any | null } | undefined;
  inception?: { [k: string]: any | null } | undefined;
  inceptron?: { [k: string]: any | null } | undefined;
  "inference-net"?: { [k: string]: any | null } | undefined;
  infermatic?: { [k: string]: any | null } | undefined;
  inflection?: { [k: string]: any | null } | undefined;
  inocloud?: { [k: string]: any | null } | undefined;
  "io-net"?: { [k: string]: any | null } | undefined;
  ionstream?: { [k: string]: any | null } | undefined;
  klusterai?: { [k: string]: any | null } | undefined;
  lambda?: { [k: string]: any | null } | undefined;
  lepton?: { [k: string]: any | null } | undefined;
  liquid?: { [k: string]: any | null } | undefined;
  lynn?: { [k: string]: any | null } | undefined;
  "lynn-private"?: { [k: string]: any | null } | undefined;
  mancer?: { [k: string]: any | null } | undefined;
  "mancer-old"?: { [k: string]: any | null } | undefined;
  mara?: { [k: string]: any | null } | undefined;
  meta?: { [k: string]: any | null } | undefined;
  minimax?: { [k: string]: any | null } | undefined;
  mistral?: { [k: string]: any | null } | undefined;
  modal?: { [k: string]: any | null } | undefined;
  modelrun?: { [k: string]: any | null } | undefined;
  modular?: { [k: string]: any | null } | undefined;
  moonshotai?: { [k: string]: any | null } | undefined;
  morph?: { [k: string]: any | null } | undefined;
  ncompass?: { [k: string]: any | null } | undefined;
  nebius?: { [k: string]: any | null } | undefined;
  nextbit?: { [k: string]: any | null } | undefined;
  nineteen?: { [k: string]: any | null } | undefined;
  novita?: { [k: string]: any | null } | undefined;
  nvidia?: { [k: string]: any | null } | undefined;
  octoai?: { [k: string]: any | null } | undefined;
  "open-inference"?: { [k: string]: any | null } | undefined;
  openai?: { [k: string]: any | null } | undefined;
  parasail?: { [k: string]: any | null } | undefined;
  perplexity?: { [k: string]: any | null } | undefined;
  phala?: { [k: string]: any | null } | undefined;
  recursal?: { [k: string]: any | null } | undefined;
  reflection?: { [k: string]: any | null } | undefined;
  reka?: { [k: string]: any | null } | undefined;
  relace?: { [k: string]: any | null } | undefined;
  replicate?: { [k: string]: any | null } | undefined;
  sambanova?: { [k: string]: any | null } | undefined;
  "sambanova-cloaked"?: { [k: string]: any | null } | undefined;
  seed?: { [k: string]: any | null } | undefined;
  "sf-compute"?: { [k: string]: any | null } | undefined;
  siliconflow?: { [k: string]: any | null } | undefined;
  sourceful?: { [k: string]: any | null } | undefined;
  stealth?: { [k: string]: any | null } | undefined;
  stepfun?: { [k: string]: any | null } | undefined;
  streamlake?: { [k: string]: any | null } | undefined;
  switchpoint?: { [k: string]: any | null } | undefined;
  targon?: { [k: string]: any | null } | undefined;
  together?: { [k: string]: any | null } | undefined;
  "together-lite"?: { [k: string]: any | null } | undefined;
  ubicloud?: { [k: string]: any | null } | undefined;
  upstage?: { [k: string]: any | null } | undefined;
  venice?: { [k: string]: any | null } | undefined;
  wandb?: { [k: string]: any | null } | undefined;
  xai?: { [k: string]: any | null } | undefined;
  xiaomi?: { [k: string]: any | null } | undefined;
  "z-ai"?: { [k: string]: any | null } | undefined;
};

/** @internal */
export const Options$outboundSchema: z.ZodType<Options$Outbound, Options> = z
  .object({
    oneai: z.record(z.string(), z.nullable(z.any())).optional(),
    ai21: z.record(z.string(), z.nullable(z.any())).optional(),
    aionLabs: z.record(z.string(), z.nullable(z.any())).optional(),
    akashml: z.record(z.string(), z.nullable(z.any())).optional(),
    alibaba: z.record(z.string(), z.nullable(z.any())).optional(),
    amazonBedrock: z.record(z.string(), z.nullable(z.any())).optional(),
    amazonNova: z.record(z.string(), z.nullable(z.any())).optional(),
    ambient: z.record(z.string(), z.nullable(z.any())).optional(),
    anthropic: z.record(z.string(), z.nullable(z.any())).optional(),
    anyscale: z.record(z.string(), z.nullable(z.any())).optional(),
    arceeAi: z.record(z.string(), z.nullable(z.any())).optional(),
    atlasCloud: z.record(z.string(), z.nullable(z.any())).optional(),
    atoma: z.record(z.string(), z.nullable(z.any())).optional(),
    avian: z.record(z.string(), z.nullable(z.any())).optional(),
    azure: z.record(z.string(), z.nullable(z.any())).optional(),
    baseten: z.record(z.string(), z.nullable(z.any())).optional(),
    blackForestLabs: z.record(z.string(), z.nullable(z.any())).optional(),
    byteplus: z.record(z.string(), z.nullable(z.any())).optional(),
    centml: z.record(z.string(), z.nullable(z.any())).optional(),
    cerebras: z.record(z.string(), z.nullable(z.any())).optional(),
    chutes: z.record(z.string(), z.nullable(z.any())).optional(),
    cirrascale: z.record(z.string(), z.nullable(z.any())).optional(),
    clarifai: z.record(z.string(), z.nullable(z.any())).optional(),
    cloudflare: z.record(z.string(), z.nullable(z.any())).optional(),
    cohere: z.record(z.string(), z.nullable(z.any())).optional(),
    crofai: z.record(z.string(), z.nullable(z.any())).optional(),
    crusoe: z.record(z.string(), z.nullable(z.any())).optional(),
    deepinfra: z.record(z.string(), z.nullable(z.any())).optional(),
    deepseek: z.record(z.string(), z.nullable(z.any())).optional(),
    enfer: z.record(z.string(), z.nullable(z.any())).optional(),
    fakeProvider: z.record(z.string(), z.nullable(z.any())).optional(),
    featherless: z.record(z.string(), z.nullable(z.any())).optional(),
    fireworks: z.record(z.string(), z.nullable(z.any())).optional(),
    friendli: z.record(z.string(), z.nullable(z.any())).optional(),
    gmicloud: z.record(z.string(), z.nullable(z.any())).optional(),
    googleAiStudio: z.record(z.string(), z.nullable(z.any())).optional(),
    googleVertex: z.record(z.string(), z.nullable(z.any())).optional(),
    gopomelo: z.record(z.string(), z.nullable(z.any())).optional(),
    groq: z.record(z.string(), z.nullable(z.any())).optional(),
    huggingface: z.record(z.string(), z.nullable(z.any())).optional(),
    hyperbolic: z.record(z.string(), z.nullable(z.any())).optional(),
    hyperbolicQuantized: z.record(z.string(), z.nullable(z.any())).optional(),
    inception: z.record(z.string(), z.nullable(z.any())).optional(),
    inceptron: z.record(z.string(), z.nullable(z.any())).optional(),
    inferenceNet: z.record(z.string(), z.nullable(z.any())).optional(),
    infermatic: z.record(z.string(), z.nullable(z.any())).optional(),
    inflection: z.record(z.string(), z.nullable(z.any())).optional(),
    inocloud: z.record(z.string(), z.nullable(z.any())).optional(),
    ioNet: z.record(z.string(), z.nullable(z.any())).optional(),
    ionstream: z.record(z.string(), z.nullable(z.any())).optional(),
    klusterai: z.record(z.string(), z.nullable(z.any())).optional(),
    lambda: z.record(z.string(), z.nullable(z.any())).optional(),
    lepton: z.record(z.string(), z.nullable(z.any())).optional(),
    liquid: z.record(z.string(), z.nullable(z.any())).optional(),
    lynn: z.record(z.string(), z.nullable(z.any())).optional(),
    lynnPrivate: z.record(z.string(), z.nullable(z.any())).optional(),
    mancer: z.record(z.string(), z.nullable(z.any())).optional(),
    mancerOld: z.record(z.string(), z.nullable(z.any())).optional(),
    mara: z.record(z.string(), z.nullable(z.any())).optional(),
    meta: z.record(z.string(), z.nullable(z.any())).optional(),
    minimax: z.record(z.string(), z.nullable(z.any())).optional(),
    mistral: z.record(z.string(), z.nullable(z.any())).optional(),
    modal: z.record(z.string(), z.nullable(z.any())).optional(),
    modelrun: z.record(z.string(), z.nullable(z.any())).optional(),
    modular: z.record(z.string(), z.nullable(z.any())).optional(),
    moonshotai: z.record(z.string(), z.nullable(z.any())).optional(),
    morph: z.record(z.string(), z.nullable(z.any())).optional(),
    ncompass: z.record(z.string(), z.nullable(z.any())).optional(),
    nebius: z.record(z.string(), z.nullable(z.any())).optional(),
    nextbit: z.record(z.string(), z.nullable(z.any())).optional(),
    nineteen: z.record(z.string(), z.nullable(z.any())).optional(),
    novita: z.record(z.string(), z.nullable(z.any())).optional(),
    nvidia: z.record(z.string(), z.nullable(z.any())).optional(),
    octoai: z.record(z.string(), z.nullable(z.any())).optional(),
    openInference: z.record(z.string(), z.nullable(z.any())).optional(),
    openai: z.record(z.string(), z.nullable(z.any())).optional(),
    parasail: z.record(z.string(), z.nullable(z.any())).optional(),
    perplexity: z.record(z.string(), z.nullable(z.any())).optional(),
    phala: z.record(z.string(), z.nullable(z.any())).optional(),
    recursal: z.record(z.string(), z.nullable(z.any())).optional(),
    reflection: z.record(z.string(), z.nullable(z.any())).optional(),
    reka: z.record(z.string(), z.nullable(z.any())).optional(),
    relace: z.record(z.string(), z.nullable(z.any())).optional(),
    replicate: z.record(z.string(), z.nullable(z.any())).optional(),
    sambanova: z.record(z.string(), z.nullable(z.any())).optional(),
    sambanovaCloaked: z.record(z.string(), z.nullable(z.any())).optional(),
    seed: z.record(z.string(), z.nullable(z.any())).optional(),
    sfCompute: z.record(z.string(), z.nullable(z.any())).optional(),
    siliconflow: z.record(z.string(), z.nullable(z.any())).optional(),
    sourceful: z.record(z.string(), z.nullable(z.any())).optional(),
    stealth: z.record(z.string(), z.nullable(z.any())).optional(),
    stepfun: z.record(z.string(), z.nullable(z.any())).optional(),
    streamlake: z.record(z.string(), z.nullable(z.any())).optional(),
    switchpoint: z.record(z.string(), z.nullable(z.any())).optional(),
    targon: z.record(z.string(), z.nullable(z.any())).optional(),
    together: z.record(z.string(), z.nullable(z.any())).optional(),
    togetherLite: z.record(z.string(), z.nullable(z.any())).optional(),
    ubicloud: z.record(z.string(), z.nullable(z.any())).optional(),
    upstage: z.record(z.string(), z.nullable(z.any())).optional(),
    venice: z.record(z.string(), z.nullable(z.any())).optional(),
    wandb: z.record(z.string(), z.nullable(z.any())).optional(),
    xai: z.record(z.string(), z.nullable(z.any())).optional(),
    xiaomi: z.record(z.string(), z.nullable(z.any())).optional(),
    zAi: z.record(z.string(), z.nullable(z.any())).optional(),
  }).transform((v) => {
    return remap$(v, {
      oneai: "01ai",
      aionLabs: "aion-labs",
      amazonBedrock: "amazon-bedrock",
      amazonNova: "amazon-nova",
      arceeAi: "arcee-ai",
      atlasCloud: "atlas-cloud",
      blackForestLabs: "black-forest-labs",
      fakeProvider: "fake-provider",
      googleAiStudio: "google-ai-studio",
      googleVertex: "google-vertex",
      hyperbolicQuantized: "hyperbolic-quantized",
      inferenceNet: "inference-net",
      ioNet: "io-net",
      lynnPrivate: "lynn-private",
      mancerOld: "mancer-old",
      openInference: "open-inference",
      sambanovaCloaked: "sambanova-cloaked",
      sfCompute: "sf-compute",
      togetherLite: "together-lite",
      zAi: "z-ai",
    });
  });

export function optionsToJSON(options: Options): string {
  return JSON.stringify(Options$outboundSchema.parse(options));
}

/** @internal */
export type Provider$Outbound = {
  options?: Options$Outbound | undefined;
};

/** @internal */
export const Provider$outboundSchema: z.ZodType<Provider$Outbound, Provider> = z
  .object({
    options: z.lazy(() => Options$outboundSchema).optional(),
  });

export function providerToJSON(provider: Provider): string {
  return JSON.stringify(Provider$outboundSchema.parse(provider));
}

/** @internal */
export const Resolution$outboundSchema: z.ZodType<string, Resolution> =
  openEnums.outboundSchema(Resolution);

/** @internal */
export type VideoGenerationRequest$Outbound = {
  aspect_ratio?: string | undefined;
  duration?: number | undefined;
  generate_audio?: boolean | undefined;
  input_references?: Array<ContentPartImage$Outbound> | undefined;
  model: string;
  prompt: string;
  provider?: Provider$Outbound | undefined;
  resolution?: string | undefined;
  seed?: number | undefined;
  size?: string | undefined;
};

/** @internal */
export const VideoGenerationRequest$outboundSchema: z.ZodType<
  VideoGenerationRequest$Outbound,
  VideoGenerationRequest
> = z.object({
  aspectRatio: AspectRatio$outboundSchema.optional(),
  duration: z.int().optional(),
  generateAudio: z.boolean().optional(),
  inputReferences: z.array(ContentPartImage$outboundSchema).optional(),
  model: z.string(),
  prompt: z.string(),
  provider: z.lazy(() => Provider$outboundSchema).optional(),
  resolution: Resolution$outboundSchema.optional(),
  seed: z.int().optional(),
  size: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    aspectRatio: "aspect_ratio",
    generateAudio: "generate_audio",
    inputReferences: "input_references",
  });
});

export function videoGenerationRequestToJSON(
  videoGenerationRequest: VideoGenerationRequest,
): string {
  return JSON.stringify(
    VideoGenerationRequest$outboundSchema.parse(videoGenerationRequest),
  );
}
