/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 0a96c6ee9eea
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  VideoGenerationUsage,
  VideoGenerationUsage$inboundSchema,
} from "./videogenerationusage.js";

export const VideoGenerationResponseStatus = {
  Pending: "pending",
  InProgress: "in_progress",
  Completed: "completed",
  Failed: "failed",
  Cancelled: "cancelled",
  Expired: "expired",
} as const;
export type VideoGenerationResponseStatus = OpenEnum<
  typeof VideoGenerationResponseStatus
>;

export type VideoGenerationResponse = {
  error?: string | undefined;
  /**
   * The generation ID associated with this video generation job. Available once the job has been processed.
   */
  generationId?: string | undefined;
  id: string;
  pollingUrl: string;
  status: VideoGenerationResponseStatus;
  unsignedUrls?: Array<string> | undefined;
  /**
   * Usage and cost information for the video generation. Available once the job has completed.
   */
  usage?: VideoGenerationUsage | undefined;
};

/** @internal */
export const VideoGenerationResponseStatus$inboundSchema: z.ZodType<
  VideoGenerationResponseStatus,
  unknown
> = openEnums.inboundSchema(VideoGenerationResponseStatus);

/** @internal */
export const VideoGenerationResponse$inboundSchema: z.ZodType<
  VideoGenerationResponse,
  unknown
> = z.object({
  error: z.string().optional(),
  generation_id: z.string().optional(),
  id: z.string(),
  polling_url: z.string(),
  status: VideoGenerationResponseStatus$inboundSchema,
  unsigned_urls: z.array(z.string()).optional(),
  usage: VideoGenerationUsage$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "generation_id": "generationId",
    "polling_url": "pollingUrl",
    "unsigned_urls": "unsignedUrls",
  });
});

export function videoGenerationResponseFromJSON(
  jsonString: string,
): SafeParseResult<VideoGenerationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VideoGenerationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VideoGenerationResponse' from JSON`,
  );
}
