/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: faa6555bfcd9
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Web search call in progress
 */
export type WebSearchCallInProgressEvent = {
  itemId: string;
  outputIndex: number;
  sequenceNumber: number;
  type: "response.web_search_call.in_progress";
};

/** @internal */
export const WebSearchCallInProgressEvent$inboundSchema: z.ZodType<
  WebSearchCallInProgressEvent,
  unknown
> = z.object({
  item_id: z.string(),
  output_index: z.int(),
  sequence_number: z.int(),
  type: z.literal("response.web_search_call.in_progress"),
}).transform((v) => {
  return remap$(v, {
    "item_id": "itemId",
    "output_index": "outputIndex",
    "sequence_number": "sequenceNumber",
  });
});

export function webSearchCallInProgressEventFromJSON(
  jsonString: string,
): SafeParseResult<WebSearchCallInProgressEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WebSearchCallInProgressEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebSearchCallInProgressEvent' from JSON`,
  );
}
