/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d43f37b9a707
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import {
  SearchQualityLevel,
  SearchQualityLevel$outboundSchema,
} from "./searchqualitylevel.js";
import {
  WebSearchEngineEnum,
  WebSearchEngineEnum$outboundSchema,
} from "./websearchengineenum.js";
import {
  WebSearchUserLocationServerTool,
  WebSearchUserLocationServerTool$Outbound,
  WebSearchUserLocationServerTool$outboundSchema,
} from "./websearchuserlocationservertool.js";

export type WebSearchConfig = {
  /**
   * Limit search results to these domains. Supported by Exa, Parallel, and most native providers (Anthropic, OpenAI, xAI). Not supported with Firecrawl or Perplexity.
   */
  allowedDomains?: Array<string> | undefined;
  /**
   * Which search engine to use. "auto" (default) uses native if the provider supports it, otherwise Exa. "native" forces the provider's built-in search. "exa" forces the Exa search API. "firecrawl" uses Firecrawl (requires BYOK). "parallel" uses the Parallel search API.
   */
  engine?: WebSearchEngineEnum | undefined;
  /**
   * Exclude search results from these domains. Supported by Exa, Parallel, Anthropic, and xAI. Not supported with Firecrawl, OpenAI (silently ignored), or Perplexity.
   */
  excludedDomains?: Array<string> | undefined;
  /**
   * Maximum number of search results to return per search call. Defaults to 5. Applies to Exa, Firecrawl, and Parallel engines; ignored with native provider search.
   */
  maxResults?: number | undefined;
  /**
   * Maximum total number of search results across all search calls in a single request. Once this limit is reached, the tool will stop returning new results. Useful for controlling cost and context size in agentic loops.
   */
  maxTotalResults?: number | undefined;
  /**
   * How much context to retrieve per result. Defaults to medium (15000 chars). Only applies when using the Exa engine; ignored with native provider search.
   */
  searchContextSize?: SearchQualityLevel | undefined;
  /**
   * Approximate user location for location-biased results.
   */
  userLocation?: WebSearchUserLocationServerTool | undefined;
};

/** @internal */
export type WebSearchConfig$Outbound = {
  allowed_domains?: Array<string> | undefined;
  engine?: string | undefined;
  excluded_domains?: Array<string> | undefined;
  max_results?: number | undefined;
  max_total_results?: number | undefined;
  search_context_size?: string | undefined;
  user_location?: WebSearchUserLocationServerTool$Outbound | undefined;
};

/** @internal */
export const WebSearchConfig$outboundSchema: z.ZodType<
  WebSearchConfig$Outbound,
  WebSearchConfig
> = z.object({
  allowedDomains: z.array(z.string()).optional(),
  engine: WebSearchEngineEnum$outboundSchema.optional(),
  excludedDomains: z.array(z.string()).optional(),
  maxResults: z.int().optional(),
  maxTotalResults: z.int().optional(),
  searchContextSize: SearchQualityLevel$outboundSchema.optional(),
  userLocation: WebSearchUserLocationServerTool$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    allowedDomains: "allowed_domains",
    excludedDomains: "excluded_domains",
    maxResults: "max_results",
    maxTotalResults: "max_total_results",
    searchContextSize: "search_context_size",
    userLocation: "user_location",
  });
});

export function webSearchConfigToJSON(
  webSearchConfig: WebSearchConfig,
): string {
  return JSON.stringify(WebSearchConfig$outboundSchema.parse(webSearchConfig));
}
