/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: fa32581277e2
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import {
  WebSearchEngine,
  WebSearchEngine$outboundSchema,
} from "./websearchengine.js";

export type WebSearchPlugin = {
  /**
   * Set to false to disable the web-search plugin for this request. Defaults to true.
   */
  enabled?: boolean | undefined;
  /**
   * The search engine to use for web search.
   */
  engine?: WebSearchEngine | undefined;
  /**
   * A list of domains to exclude from web search results. Supports wildcards (e.g. "*.substack.com") and path filtering (e.g. "openai.com/blog").
   */
  excludeDomains?: Array<string> | undefined;
  id: "web";
  /**
   * A list of domains to restrict web search results to. Supports wildcards (e.g. "*.substack.com") and path filtering (e.g. "openai.com/blog").
   */
  includeDomains?: Array<string> | undefined;
  maxResults?: number | undefined;
  searchPrompt?: string | undefined;
};

/** @internal */
export type WebSearchPlugin$Outbound = {
  enabled?: boolean | undefined;
  engine?: string | undefined;
  exclude_domains?: Array<string> | undefined;
  id: "web";
  include_domains?: Array<string> | undefined;
  max_results?: number | undefined;
  search_prompt?: string | undefined;
};

/** @internal */
export const WebSearchPlugin$outboundSchema: z.ZodType<
  WebSearchPlugin$Outbound,
  WebSearchPlugin
> = z.object({
  enabled: z.boolean().optional(),
  engine: WebSearchEngine$outboundSchema.optional(),
  excludeDomains: z.array(z.string()).optional(),
  id: z.literal("web"),
  includeDomains: z.array(z.string()).optional(),
  maxResults: z.int().optional(),
  searchPrompt: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    excludeDomains: "exclude_domains",
    includeDomains: "include_domains",
    maxResults: "max_results",
    searchPrompt: "search_prompt",
  });
});

export function webSearchPluginToJSON(
  webSearchPlugin: WebSearchPlugin,
): string {
  return JSON.stringify(WebSearchPlugin$outboundSchema.parse(webSearchPlugin));
}
