/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 273c8df02654
 */

import * as z from "zod/v4";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

/**
 * Which search engine to use. "auto" (default) uses native if the provider supports it, otherwise Exa. "native" forces the provider's built-in search. "exa" forces the Exa search API. "firecrawl" uses Firecrawl (requires BYOK). "parallel" uses the Parallel search API.
 */
export const WebSearchEngineEnum = {
  Auto: "auto",
  Native: "native",
  Exa: "exa",
  Firecrawl: "firecrawl",
  Parallel: "parallel",
} as const;
/**
 * Which search engine to use. "auto" (default) uses native if the provider supports it, otherwise Exa. "native" forces the provider's built-in search. "exa" forces the Exa search API. "firecrawl" uses Firecrawl (requires BYOK). "parallel" uses the Parallel search API.
 */
export type WebSearchEngineEnum = OpenEnum<typeof WebSearchEngineEnum>;

/** @internal */
export const WebSearchEngineEnum$inboundSchema: z.ZodType<
  WebSearchEngineEnum,
  unknown
> = openEnums.inboundSchema(WebSearchEngineEnum);
/** @internal */
export const WebSearchEngineEnum$outboundSchema: z.ZodType<
  string,
  WebSearchEngineEnum
> = openEnums.outboundSchema(WebSearchEngineEnum);
