/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: cc946a3064e3
 */

import * as z from "zod/v4";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const WebSearchUserLocationType = {
  Approximate: "approximate",
} as const;
export type WebSearchUserLocationType = ClosedEnum<
  typeof WebSearchUserLocationType
>;

/**
 * User location information for web search
 */
export type WebSearchUserLocation = {
  city?: string | null | undefined;
  country?: string | null | undefined;
  region?: string | null | undefined;
  timezone?: string | null | undefined;
  type?: WebSearchUserLocationType | undefined;
};

/** @internal */
export const WebSearchUserLocationType$inboundSchema: z.ZodEnum<
  typeof WebSearchUserLocationType
> = z.enum(WebSearchUserLocationType);
/** @internal */
export const WebSearchUserLocationType$outboundSchema: z.ZodEnum<
  typeof WebSearchUserLocationType
> = WebSearchUserLocationType$inboundSchema;

/** @internal */
export const WebSearchUserLocation$inboundSchema: z.ZodType<
  WebSearchUserLocation,
  unknown
> = z.object({
  city: z.nullable(z.string()).optional(),
  country: z.nullable(z.string()).optional(),
  region: z.nullable(z.string()).optional(),
  timezone: z.nullable(z.string()).optional(),
  type: WebSearchUserLocationType$inboundSchema.optional(),
});
/** @internal */
export type WebSearchUserLocation$Outbound = {
  city?: string | null | undefined;
  country?: string | null | undefined;
  region?: string | null | undefined;
  timezone?: string | null | undefined;
  type?: string | undefined;
};

/** @internal */
export const WebSearchUserLocation$outboundSchema: z.ZodType<
  WebSearchUserLocation$Outbound,
  WebSearchUserLocation
> = z.object({
  city: z.nullable(z.string()).optional(),
  country: z.nullable(z.string()).optional(),
  region: z.nullable(z.string()).optional(),
  timezone: z.nullable(z.string()).optional(),
  type: WebSearchUserLocationType$outboundSchema.optional(),
});

export function webSearchUserLocationToJSON(
  webSearchUserLocation: WebSearchUserLocation,
): string {
  return JSON.stringify(
    WebSearchUserLocation$outboundSchema.parse(webSearchUserLocation),
  );
}
export function webSearchUserLocationFromJSON(
  jsonString: string,
): SafeParseResult<WebSearchUserLocation, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WebSearchUserLocation$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebSearchUserLocation' from JSON`,
  );
}
