/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 5137f6f83524
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Web search call completed
 */
export type WebSearchCallCompletedEvent = {
  itemId: string;
  outputIndex: number;
  sequenceNumber: number;
  type: "response.web_search_call.completed";
};

/** @internal */
export const WebSearchCallCompletedEvent$inboundSchema: z.ZodType<
  WebSearchCallCompletedEvent,
  unknown
> = z.object({
  item_id: z.string(),
  output_index: z.int(),
  sequence_number: z.int(),
  type: z.literal("response.web_search_call.completed"),
}).transform((v) => {
  return remap$(v, {
    "item_id": "itemId",
    "output_index": "outputIndex",
    "sequence_number": "sequenceNumber",
  });
});

export function webSearchCallCompletedEventFromJSON(
  jsonString: string,
): SafeParseResult<WebSearchCallCompletedEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WebSearchCallCompletedEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebSearchCallCompletedEvent' from JSON`,
  );
}
